export const de = {
  appTitle: "Ressourcen & Präsenzplanung",
  appSubtitle: "Operationsplanung für IT-Ressourcen, Präsenz und Kapazität",
  appLogoAlt: "App-Logo M365 Ressourcen & Präsenzplanung",
  themeLight: "Hell",
  themeDark: "Dunkel",
  themeToggle: "Darstellung wechseln",
  headerSearch: "Suche",
  headerSearchPlaceholder: "Suche (Strg+E)",
  moreActions: "Weitere Aktionen",
  help: "Hilfe",
  teamsRailLabel: "Microsoft Teams Navigation",
  teamsRailActivity: "Aktivität",
  teamsRailChat: "Chat",
  teamsRailTeams: "Teams",
  teamsRailCalendar: "Kalender",
  teamsRailCalls: "Anrufe",
  teamsRailFiles: "Dateien",
  teamsRailResources: "Ressourcen",
  teamsRailApprovals: "Genehmigungen",
  teamsRailApps: "Apps",
  primaryNavigation: "Hauptnavigation",
  navOverview: "Übersicht",
  navTeamCapacity: "Team-Kapazität",
  navMyAbsences: "Meine Abwesenheiten",
  navApprovals: "Genehmigungen",
  navTeamAdmin: "Team Admin Center",
  navReports: "Reports",
  navSettings: "Einstellungen",
  navInfo: "Info",
  pageOverviewDescription: "Operative Planungsübersicht mit Timeline, Ressourcen, Teams und Präsenzereignissen.",
  pageTeamCapacityDescription: "Wochenbasierte Teamkapazität mit Verfügbarkeit, Abwesenheitsanteil und Risikostatus.",
  pageMyAbsencesDescription: "Platzhalter für persönliche Abwesenheiten und spätere Antragsübersicht.",
  pageApprovalsDescription: "Platzhalter für spätere Genehmigungen und Entscheidungsprozesse.",
  pageTeamAdminDescription: "Zentrale Administration für Team-Genehmiger, Stellvertretungen, Richtlinien und Ferienübersicht.",
  pageReportsDescription: "Platzhalter für Reporting, Analysen und Exportansichten.",
  pageSettingsDescription: "Persönliche Einstellungen für Ferienanträge, Genehmiger, Benachrichtigungen und Outlook-Synchronisation.",
  pageInfoDescription: "Informationen zur Anwendung, Architektur und Design-System-Grundlage.",
  infoPageDescription: "Mit RPP planen Sie Personen, Präsenz und Kapazität – direkt in Microsoft Teams.",
  infoPageBadge: "Friends & Family",
  infoPageTitle: "RPP – Ressourcen & Präsenzplanung",
  infoPageGoToTimeline: "Zur Timeline",
  infoPageGoToReports: "Zu den Reports",
  infoPageStatTeamsLabel: "Organisationen & Teams",
  infoPageStatTeamsValue: "Frei konfigurierbar",
  infoPageStatModeLabel: "Ihr Gewinn",
  infoPageStatModeMock: "Wer ist wann verfügbar",
  infoPageStatModeApi: "Wer ist wann verfügbar",
  infoPageStatDeploymentLabel: "Wo Sie arbeiten",
  infoPageStatDeploymentValue: "Direkt in Microsoft Teams",
  infoCardPeopleTitle: "Personen & Teams",
  infoCardPeopleDescription: "Jede Person kann mehreren Teams angehören und mehrere Rollen tragen. Timeline, Team-Kapazität und Reports arbeiten auf derselben Mitgliedschaftsbasis – organisationsübergreifend und konsistent.",
  infoCardPeopleStatus: "Multi-Team, Multi-Rolle",
  infoCardDataTitle: "Ihre Planungsdaten",
  infoCardDataDescription: "Abwesenheiten, Ferienstände, Feiertage und Teamregeln speichert RPP zuverlässig. Personen und Profilbilder kommen aus Microsoft 365 – die Planung bleibt an einem Ort, klar und nachvollziehbar.",
  infoCardDataStatus: "Sicher und konsistent",
  infoCardDeliveryTitle: "Immer der aktuelle Stand",
  infoCardDeliveryDescription: "Neue Versionen kommen als Ganzes. Was Sie in Teams sehen, ist genau der freigegebene Stand – ohne Abweichungen zwischen App und Server.",
  infoCardDeliveryStatus: "Klare Versionen",
  infoCardWhatIsRppTitle: "Was ist RPP?",
  infoCardWhatIsRppDescription: "Mit RPP planen Teams Ressourcen, Präsenz und Kapazitäten in einer einzigen Anwendung. Alle wichtigen Funktionen wie Planung, Genehmigungen und Administration sind zentral verfügbar.",
  infoCardWhatIsRppStatus: "Operations Planning Platform",
  infoCardValueTitle: "Wozu dient RPP?",
  infoCardValueDescription: "RPP schafft operative Transparenz über Organisationsgrenzen hinweg. Teamleiter sehen auf einen Blick, wer wann verfügbar ist, wo Kapazitätsengpässe drohen und welche Abwesenheiten genehmigt sind – ohne Mails, Excel oder Nachfragen.",
  infoCardValueStatus: "Sichtbarkeit & Entscheidungsgrundlage",
  infoCardGetItTitle: "Wie erhalten Sie Zugang?",
  infoCardGetItDescription: "Ihre Organisation stellt RPP in Microsoft Teams bereit. Danach finden Sie die App in der Teams-Navigation. Teamleiter richten ihre Teams selbst im Team Admin Center ein – ohne Extra-Ticket an die IT.",
  infoCardGetItStatus: "Über Microsoft Teams",
  infoFactsTitle: "Auf einen Blick",
  infoFactsDescription: "Architektur, Module und Betrieb der Plattform.",
  infoFactArchitectureLabel: "Architektur",
  infoFactArchitectureValue: "React · Vite · Fluent UI · ASP.NET Core · SQL Server",
  infoFactArchitectureText: "Das Frontend läuft als Teams Tab (Vite SPA, Fluent UI v9). Die Web API (ASP.NET Core 8) übernimmt sämtliche Geschäftslogik, Persistenz und Graph-Integration. SQL Server speichert alle Planungsdaten.",
  infoFactRolesLabel: "Module",
  infoFactRolesValue: "Timeline · Kalender · Team-Kapazität · Team Admin · App Admin · Reports · Approvals · Einstellungen",
  infoFactRolesText: "Jedes Modul hat einen klar abgegrenzten Zweck: Planung, Verwaltung, Analyse, Genehmigung, Konfiguration und persönliche Einstellungen.",
  infoFactLocalizationLabel: "Lokalisierung",
  infoFactLocalizationValue: "Deutsch, Englisch + 36 weitere Sprachdateien",
  infoFactLocalizationText: "Alle sichtbaren Texte sind lokalisierbar. Primäre Sprachen sind Deutsch und Englisch; das Übersetzungsframework unterstützt 38 Locales.",
  infoFactTeamsLabel: "Mandantenfähigkeit",
  infoFactTeamsValue: "Mehrere Organisationen · erweiterbar",
  infoFactTeamsText: "Organisationen, Standorte und Teams sind konfigurierbar – ohne Code-Änderungen. Die Plattform ist darauf ausgelegt, weitere Organisationen aufzunehmen.",
  infoRuntimeCardTitle: "Effektive Konfiguration & Backend-Diagnose",
  infoRuntimeCardDescription: "Laufende Frontend-/Backend-Metadaten, Provider-Status und Infrastrukturziele für schnelle Betriebsprüfungen.",
  infoRuntimeFrontendTitle: "Frontend (Teams Tab)",
  infoRuntimeBackendTitle: "Backend (RPP Web API)",
  infoRuntimeLabelEffectiveProvider: "Aktiver Provider-Modus",
  infoRuntimeLabelEnvironment: "Umgebung",
  infoRuntimeLabelApiBaseUrl: "API-Basis-URL",
  infoRuntimeLabelSharePointSiteUrl: "SharePoint-Site-URL",
  infoRuntimeLabelHealthEndpoint: "Health-Endpunkt",
  infoRuntimeLabelFrontendRelease: "Frontend Release",
  infoRuntimeLabelFrontendRevision: "Frontend Revision",
  infoRuntimeLabelFrontendBuild: "Frontend Build-Zeit",
  infoRuntimeLabelBackendStatus: "Backend Status",
  infoRuntimeLabelBackendVersion: "Backend Version",
  infoRuntimeLabelBackendRevision: "Backend Revision",
  infoRuntimeLabelBackendBuild: "Backend Build-Zeit",
  infoRuntimeLabelBackendEnvironment: "Backend Umgebung",
  infoRuntimeLabelBackendProvider: "Backend Provider",
  infoRuntimeLabelBackendDatabaseServer: "Datenbank-Server",
  infoRuntimeLabelBackendDatabaseName: "Datenbank-Name",
  infoRuntimeLabelBackendWebServer: "Webserver-Name",
  infoRuntimeLoading: "Backend-Metadaten werden geladen ...",
  infoRuntimeNotAvailable: "Nicht verfügbar",
  shellOnlyBadge: "EO-009-C",
  timelineAriaLabel: "Timeline-Grundlage",
  timelineTitle: "Planungstimeline",
  timelineThreeMonthView: "3-Monats-Ansicht",
  timelinePeriodLabel: "Zeitraum",
  timelinePeriodNext30Days: "30 Tage",
  timelinePeriodNextThreeMonths: "Nächste 3 Monate",
  timelinePeriodNextSixMonths: "Nächste 6 Monate",
  timelinePeriodFullYear: "Ganzes Jahr",
  timelinePeriodWeek: "Woche",
  timelinePeriodMonth: "Monat",
  timelineGroupByLabel: "Gruppieren nach",
  timelineGroupByTeams: "Teams",
  timelineGroupByPeople: "Personen",
  timelineViewLabel: "Ansicht",
  timelineViewGantt: "Balken (Gantt)",
  timelineViewList: "Liste",
  timelineViewCalendar: "Kalender (Monat)",
  timelineToday: "Heute",
  timelineCalendarPrev: "Vorheriger Monat",
  timelineCalendarNext: "Nächster Monat",
  timelineCalendarOverflow: "+{count} weitere",
  timelineFilter: "Filter",
  timelineFilterLabel: "Filter",
  timelineFilterPlaceholder: "Team oder Person suchen",
  timelineLegendSchoolHolidaySg: "Schulferien St. Gallen",
  timelineLegendSchoolHolidayDubendorf: "Schulferien Dübendorf",
  timelineLegendPublicHoliday: "Feiertage",
  timelineAvailablePeople: "Verfügbare Personen (gesamt)",
  timelineMinimumStaffing: "Benötigte Mindestbesetzung",
  timelineCalendarWeekPrefix: "KW",
  timelineEmployeeColumn: "Mitarbeiter",
  resourceCompetencies: "Rollen und Kompetenzen",
  resourceVacationSummary: "Ferienübersicht: Anspruch, gebucht, Rest",
  resourceVacationIcon: "🌴",
  resourceVacationEntitlement: "A",
  resourceVacationBooked: "G",
  resourceVacationRemaining: "R",
  resourceVacationEntitlementTooltip: "Ferienanspruch",
  resourceVacationBookedTooltip: "Gebucht",
  resourceVacationRemainingTooltip: "Resttage",
  teamGroupingResourceCount: "Ressourcen",
  teamGroupingResourceCountCompact: "MA",
  teamGroupingExpand: "Teamgruppe erweitern",
  teamGroupingCollapse: "Teamgruppe reduzieren",
  eventTypeVacation: "Ferien",
  eventTypeCompensation: "Kompensation",
  eventTypeEducation: "Ausbildung",
  eventTypeHomeOffice: "Home Office",
  eventTypeTraining: "Weiterbildung",
  eventTypeMilitary: "Militär",
  eventTypeUnpaidLeave: "Unbezahlter Urlaub",
  eventTypeOtherAbsence: "Sonstige Abwesenheit",
  eventTypeProject: "Projekt",
  eventTypeMaintenance: "Wartung",
  eventTypeOnCall: "Pikett",
  eventTypeStandby: "Standby",
  detailsClose: "Schließen",
  detailsResourceTitle: "Ressourcendetails",
  detailsPresenceTitle: "Ereignisdetails",
  detailsResourceSection: "Ressource",
  detailsPresenceSection: "Präsenzereignis",
  detailsOrganisation: "Organisation",
  detailsPrimaryTeam: "Primäres Team",
  detailsSecondaryTeams: "Weitere Teams",
  detailsVacation: "Ferien",
  detailsEventType: "Ereignistyp",
  detailsEventTitle: "Titel",
  detailsStartDate: "Startdatum",
  detailsEndDate: "Enddatum",
  detailsDuration: "Dauer",
  detailsDays: "Tage",
  absenceNew: "Neue Abwesenheit",
  absencePersistError: "Die Abwesenheit konnte nicht gespeichert werden. Bitte erneut versuchen.",
  approvalSubmitPending: "Der Antrag wurde zur Genehmigung an Microsoft 365 übermittelt. Der Genehmiger findet ihn in der Teams-App „Approvals“.",
  approvalSubmitAutoApproved: "Die Abwesenheit wurde gespeichert – für diese Person ist keine Genehmigung erforderlich.",
  approvalSubmitError: "Der Antrag konnte nicht eingereicht werden. Bitte Genehmiger im Team Admin Center prüfen und erneut versuchen.",
  myApprovalsTitle: "Meine Anträge",
  myApprovalsDescription: "Ihre Ferienanträge und deren Microsoft-365-Status. Der Genehmiger entscheidet in der Teams-App „Approvals“ (bei ihm unter Eingehend; Sie sehen Gesendet).",
  myApprovalsRefresh: "Status aktualisieren",
  myApprovalsOpenTeams: "Approvals in Teams öffnen",
  myApprovalsEmpty: "Noch keine Anträge vorhanden. Neue Anträge entstehen über die Timeline („Genehmigung anfordern“).",
  myApprovalsLoadError: "Die Anträge konnten nicht geladen werden. Bitte erneut versuchen.",
  myApprovalsColPeriod: "Zeitraum",
  myApprovalsColModified: "Zuletzt geändert",
  myApprovalsColM365: "M365 Approvals",
  myApprovalsM365Linked: "Verknüpft",
  myApprovalsM365Missing: "Kein Graph-Eintrag",
  myApprovalsGraphId: "Graph-Id",
  myApprovalsWhereToFind: "In der Teams-App „Approvals“: Als Genehmiger unter „Erhalten“, als Antragsteller unter „Gesendet“. Umgebung/Filter oben rechts prüfen (Tenant). Der Eintrag erscheint nur beim Konto des gewählten Genehmigers.",
  absenceApproverPolicyManaged: "Durch die Team-Richtlinie festgelegt",
  absenceApproverNone: "Genehmiger wählen",
  absenceApproverRequired: "Bitte einen Genehmiger wählen oder im Team Admin Center einen Standard-Genehmiger festlegen.",
  orgConfigTitle: "Organisationen & Standorte",
  orgConfigDescription: "Konfigurierbare Listen für Partnerorganisationen und Standorte. Die Werte der Mitglieder werden aus dem Microsoft-365-Profil (Firma, Büro) abgeleitet und hier zugeordnet.",
  orgConfigOrganisations: "Organisationen",
  orgConfigLocations: "Standorte",
  orgConfigOrganisationMappings: "Zuordnung Profilwert → Organisation",
  orgConfigLocationMappings: "Zuordnung Profilwert → Standort",
  orgConfigUnassigned: "Nicht zugeordnet",
  orgConfigAdd: "Hinzufügen",
  orgConfigRemove: "Entfernen",
  orgConfigSave: "Organisationen & Standorte speichern",
  orgConfigSaved: "Gespeichert. Die Zuordnungen sind sofort wirksam.",
  orgConfigLoadError: "Die Konfiguration konnte nicht geladen werden.",
  orgConfigSaveError: "Die Konfiguration konnte nicht gespeichert werden.",
  myApprovalsColOutlook: "Outlook",
  teamCapacityAbsentPersons: "Abwesende Personen",
  teamCapacityAbsenceDays: "Abwesenheit (Personentage)",
  teamCapacityAvailableDays: "Verfügbar (Personentage)",
  absenceCreateTitle: "Abwesenheit beantragen",
  absenceEditTitle: "Abwesenheit bearbeiten",
  absenceCreate: "Speichern",
  absenceRequestApproval: "Genehmigung beantragen",
  absenceUpdate: "Änderungen speichern",
  absenceDelete: "Löschen",
  absenceDeleteConfirm: "Löschen bestätigen",
  absenceFieldType: "Abwesenheitstyp",
  absenceFieldStartDate: "Startdatum",
  absenceFieldStartHalf: "Start-Tageshälfte",
  absenceFieldEndDate: "Enddatum",
  absenceFieldEndHalf: "End-Tageshälfte",
  absenceFieldSubstitute: "Stellvertretung",
  absenceFieldComment: "Bemerkung",
  absenceSubstituteNone: "Keine Stellvertretung",
  absenceCalculatedWorkdays: "Arbeitstage",
  absenceSyncTitle: "Synchronisation",
  absenceSyncOutlook: "Mit Outlook synchronisieren",
  absenceApprovalStatus: "Antragsstatus",
  absenceApprovalStatusDraft: "Entwurf",
  absenceApprovalStatusPending: "Pendent",
  absenceApprovalStatusApproved: "Genehmigt",
  absenceApprovalStatusRejected: "Abgelehnt",
  absenceVacationEntitlementTitle: "Ferienanspruch 2026",
  absenceVacationAvailable: "Verfügbar",
  absenceVacationBooked: "Bereits gebucht",
  absenceVacationAfterBooking: "Nach dieser Buchung",
  absenceCancel: "Abbrechen",
  vacationRequestStatus: "Antragsstatus",
  vacationRequestApprovalSection: "Genehmigung",
  vacationRequestApprover: "Genehmiger",
  vacationRequestCommentToApprover: "Kommentar an Genehmiger",
  vacationRequestSaveDraft: "Entwurf speichern",
  vacationRequestSubmitForApproval: "Zur Genehmigung einreichen",
  approvalPrototypeTitle: "Klickbarer Genehmigungsworkflow",
  approvalPrototypeBadge: "EO-202-A Mock Workflow",
  approvalLiveModeBadge: "Microsoft 365 Genehmigungsprozess",
  approvalPrototypeTimeline: "Genehmigungsfortschritt",
  approvalPrototypeStepPrepare: "Vorbereiten",
  approvalPrototypeStepReview: "Prüfen",
  approvalPrototypeStepSubmitted: "Eingereicht",
  approvalPrototypeStepTeamLead: "Abteilungsleiter",
  approvalPrototypeStepDecision: "Entscheid",
  approvalPrototypePrepareTitle: "Ferienantrag vorbereiten",
  approvalPrototypePrepareDescription: "Erfasse die Antragsdaten wie in der späteren produktiven Oberfläche. Alles bleibt lokal im Browser.",
  approvalPrototypeReviewTitle: "Antrag prüfen",
  approvalPrototypeReviewDescription: "Kontrolliere Zeitraum, Dauer und Genehmiger, bevor der Antrag simuliert eingereicht wird.",
  approvalPrototypeSubmittedTitle: "Antrag eingereicht",
  approvalPrototypeSubmittedDescription: "Der Antrag liegt im Mock-Workflow beim Abteilungsleiter. Es wurde keine echte Genehmigung gestartet.",
  approvalPrototypeTeamLeadTitle: "Abteilungsleiter-Entscheid simulieren",
  approvalPrototypeTeamLeadDescription: "Wechsle in die Perspektive des Abteilungsleiters und simuliere Genehmigung oder Ablehnung.",
  approvalPrototypeDecisionTitle: "Workflow abgeschlossen",
  approvalPrototypeDecisionDescription: "Der Mock-Workflow zeigt den finalen Status. Es wurden keine produktiven Daten verändert.",
  approvalPrototypeReviewRequest: "Antrag prüfen",
  approvalPrototypeBackToEdit: "Zurück zur Bearbeitung",
  approvalPrototypeBackToPending: "Zurück zu eingereicht",
  approvalPrototypeOpenTeamLead: "Abteilungsleiter-Ansicht öffnen",
  approvalPrototypeCancelRequest: "Antrag stornieren",
  approvalPrototypeApprove: "Genehmigen",
  approvalPrototypeReject: "Ablehnen",
  approvalPrototypeStartNew: "Neuen Mock-Workflow starten",
  approvalPrototypeRoutingHint: "Der Genehmiger stammt aus der simulierten Team Policy und kann später durch die produktive API ersetzt werden.",
  approvalPrototypeSubmittedMessage: "Der Antrag wartet sichtbar auf den Abteilungsleiter-Entscheid. Dieser Zustand ist nur temporärer UI-State.",
  approvalPrototypeDecisionComment: "Entscheidungskommentar",
  approvalPrototypeApprovedMessage: "Der Antrag wurde im Mock-Workflow genehmigt.",
  approvalPrototypeRejectedMessage: "Der Antrag wurde im Mock-Workflow abgelehnt.",
  approvalPrototypeCancelledMessage: "Der Antrag wurde im Mock-Workflow storniert.",
  approvalPrototypeApprovedPersistedMessage: "Die genehmigten Ferien wurden in der Mock-Timeline gespeichert.",
  approvalPrototypePersistError: "Die genehmigten Ferien konnten nicht im Mock-Zustand gespeichert werden.",
  approvalPrototypeSummaryTitle: "Antragsübersicht",
  approvalPrototypeSummaryDescription: "Aktueller Mock-Zustand für Demo und Usability Review.",
  approvalPrototypeRequester: "Antragsteller",
  approvalPrototypeMockOnly: "Nur Mock, kein produktiver Prozess",
  approvalStatusDraft: "Entwurf",
  approvalStatusSubmitted: "Eingereicht",
  approvalStatusPendingApproval: "Wartet auf Genehmigung",
  approvalStatusApproved: "Genehmigt",
  approvalStatusRejected: "Abgelehnt",
  approvalStatusCancelled: "Storniert",
  approvalStatusFailed: "Fehlgeschlagen",
  absenceCalculatedRemainingVacation: "Restferien nach Buchung",
  absenceValidationRequired: "Bitte alle Pflichtfelder ausfüllen.",
  absenceValidationEndBeforeStart: "Das Enddatum darf nicht vor dem Startdatum liegen.",
  absenceValidationDuration: "Die ausgewählte Halbtageskombination ergibt keine gültige Dauer.",
  absenceValidationOutsideTimeline: "Die Änderung liegt außerhalb des sichtbaren Zeitraums.",
  absenceValidationMoveDuration: "Die Verschiebung darf die Dauer der Abwesenheit nicht verändern.",
  absenceTypeVacation: "Ferien",
  absenceTypeCompensation: "Kompensation",
  absenceTypeEducation: "Ausbildung",
  absenceTypeTraining: "Weiterbildung",
  absenceTypeMilitary: "Militär",
  absenceTypeUnpaidLeave: "Unbezahlter Urlaub",
  absenceTypeOther: "Sonstige",
  dayHalfMorning: "Vormittag",
  dayHalfAfternoon: "Nachmittag",
  dayHalfFullDay: "Ganzer Tag",
  capacityAvailable: "Verfügbare Kapazität",
  teamCapacityDashboardTitle: "Team-Kapazität",
  teamCapacityDashboardDescription: "Aggregierte Wochenübersicht auf Basis der zentralen Capacity Engine.",
  teamCapacityTeamLabel: "Team",
  teamCapacityAvailable: "Verfügbar",
  teamCapacityAbsent: "Abwesend",
  teamCapacityUtilization: "Abdeckung",
  teamCapacityMembers: "Teammitglieder",
  teamCapacityNominal: "Nominal",
  teamCapacityCriticalWeeks: "Kritische Wochen",
  teamCapacityCriticalWeeksShort: "Kritische Wochen",
  teamCapacityWeeklyOverview: "Wochenübersicht",
  teamCapacityStatus: "Status",
  teamCapacityMetric: "Kennzahl",
  teamCapacityAffectedResources: "Betroffene Mitarbeitende",
  teamCapacityNoAffectedResources: "Keine betroffenen Mitarbeitenden in dieser Kalenderwoche.",
  teamCapacityStatusOk: "OK",
  teamCapacityStatusWarning: "Warnung",
  teamCapacityStatusCritical: "Kritisch",
  designSystemSectionTitle: "Design-System-Grundlagen",
  designSystemSectionDescription: "Wiederverwendbare visuelle Muster für kommende Engineering Orders.",
  designCardLayoutTitle: "Layout",
  designCardLayoutDescription: "Shell, Seitenkopf, Inhaltsbereich und responsive Abstände folgen einem einheitlichen Raster.",
  designCardThemeTitle: "Theme",
  designCardThemeDescription: "Light und Dark Mode basieren auf Fluent UI Tokens und bleiben erweiterbar.",
  designCardTypographyTitle: "Typografie",
  designCardTypographyDescription: "Titel, Abschnitte und Hilfetexte nutzen konsistente Größen und Gewichte.",
  statusReady: "Bereit",
  statusFoundation: "Grundlage",
  statusReserved: "Reserviert",
  placeholderSurfaceTitle: "Application Shell",
  placeholderSurfaceText: "Diese Seite ist bewusst ein Platzhalter. Fachfunktionalität folgt in späteren Engineering Orders.",
  errorBoundaryTitle: "Etwas ist schiefgelaufen.",
  errorBoundaryMessage: "Die Ansicht konnte nicht geladen werden. Bitte versuchen Sie es erneut oder melden Sie die Referenz an den Support.",
  errorReferenceLabel: "Referenz",
  errorRetryAction: "Erneut versuchen",
  runtimeConfigUnavailableTitle: "Anwendungskonfiguration nicht verfügbar",
  runtimeConfigUnavailableDescription: "Die Anwendung kann ohne eine gültige Bereitstellungskonfiguration keine verlässlichen Planungsdaten anzeigen.",
  planningBootstrapLoading: "Planungsdaten werden geladen ...",
  planningBootstrapEmptyTitle: "Keine planbaren Personen gefunden.",
  planningBootstrapEmptyMessage: "Die Planungsansicht benötigt Teammitglieder, bevor Kapazität und Abwesenheiten angezeigt werden können.",
  planningBootstrapNoTeamContextTitle: "Kein Team ausgewählt.",
  planningBootstrapNoTeamContextMessage: "Die Planungsansicht weiss noch nicht, welches Team sie zeigen soll. Öffnen Sie RPP als Registerkarte in einem Team, oder wählen Sie ein Team aus.",
  planningBootstrapUnauthenticatedTitle: "Anmeldung erforderlich.",
  planningBootstrapUnauthenticatedMessage: "RPP konnte sich nicht bei Microsoft 365 anmelden. Bestätigen Sie den Zustimmungsdialog von Microsoft Teams und versuchen Sie es erneut.",
  planningBootstrapForbiddenTitle: "Kein Zugriff auf dieses Team.",
  planningBootstrapForbiddenMessage: "Ihr Konto ist bekannt, hat aber keinen Zugriff auf die Daten dieses Teams. Wenden Sie sich an Ihre Teamleitung.",
  teamContextPickerLoading: "Ihre Teams werden geladen …",
  teamContextPickerPrompt: "Welches Team möchten Sie planen?",
  teamContextPickerNoTeams: "Sie gehören noch keinem Team an. Bitten Sie Ihre Teamleitung, Sie einem Team hinzuzufügen.",
  teamContextPickerFailed: "Ihre Teams konnten nicht geladen werden. Bitte versuchen Sie es erneut.",
  mySettingsTitle: "Meine Einstellungen",
  mySettingsLoading: "Einstellungen werden geladen ...",
  mySettingsProfileTitle: "Profil",
  mySettingsName: "Name",
  mySettingsEmail: "E-Mail-Adresse",
  mySettingsTeam: "Team",
  mySettingsApprovalTitle: "Genehmigung",
  mySettingsApprovalDescription: "Standard-Genehmiger und Fallback für Ferienanträge.",
  mySettingsDefaultApprover: "Standard-Genehmiger",
  mySettingsFallbackApprover: "Fallback-Genehmiger",
  mySettingsApproverSource: "Quelle",
  mySettingsApproverSourceUser: "Persönliche Einstellung",
  mySettingsApproverSourceTeamPolicy: "Team Policy",
  mySettingsApproverSourceTeamLead: "Abteilungsleiter",
  mySettingsApproverSourceFallback: "Fallback",
  mySettingsNoApproverWarning: "Kein Genehmiger konfiguriert. Bitte Team-Admin kontaktieren.",
  mySettingsNotificationsTitle: "Benachrichtigungen",
  mySettingsNotificationsDescription: "Wie du über Statusänderungen deiner Anträge informiert wirst.",
  mySettingsNotificationInApp: "In-App-Benachrichtigung",
  mySettingsNotificationEmail: "E-Mail-Benachrichtigung",
  mySettingsNotificationTeams: "Teams-Benachrichtigung",
  mySettingsOutlookTitle: "Outlook-Kalender",
  mySettingsOutlookDescription: "Standardverhalten für genehmigte Absenzen.",
  mySettingsOutlookSync: "Genehmigte Ferien mit Outlook synchronisieren",
  mySettingsOutlookEnabled: "Aktiviert",
  mySettingsOutlookDisabled: "Deaktiviert",
  mySettingsOutlookManaged: "Durch Team Policy verwaltet",
  mySettingsRegionalTitle: "Regional",
  mySettingsRegionalDescription: "Sprache und Zeitzone werden aus Microsoft 365 oder dem Browser übernommen.",
  mySettingsLanguage: "Sprache",
  mySettingsTimeZone: "Zeitzone",
  mySettingsManagedByTeamPolicy: "Durch Team Policy verwaltet",
  mySettingsNotConfigured: "Nicht konfiguriert",
  mySettingsSaveChanges: "Änderungen speichern",
  mySettingsResetToDefaults: "Auf Standardwerte zurücksetzen",
  mySettingsSavedToast: "Einstellungen gespeichert",
  mySettingsResetToast: "Einstellungen zurückgesetzt",
  mySettingsSaveError: "Einstellungen konnten nicht gespeichert werden",
  outlookSyncStatusNotRequired: "Keine Outlook-Synchronisation",
  outlookSyncStatusPending: "Synchronisierung läuft",
  outlookSyncStatusSynced: "Outlook-Kalender aktualisiert",
  outlookSyncStatusFailed: "Outlook-Synchronisierung fehlgeschlagen",
  outlookSyncRetry: "Synchronisierung erneut versuchen",
  vacationBalanceTitle: "Ferienguthaben",
  vacationBalanceAnnualEntitlement: "Jahresanspruch",
  vacationBalanceCarryForward: "Übertrag",
  vacationBalanceManualAdjustments: "Manuelle Anpassungen",
  vacationBalancePendingVacation: "Beantragte Ferien",
  vacationBalanceApprovedVacation: "Genehmigte Ferien",
  vacationBalanceRemainingBalance: "Verbleibender Saldo",
  vacationBalancePreviewTitle: "Saldo-Vorschau",
  vacationBalanceCurrentBalance: "Aktueller Saldo",
  vacationBalanceRequestedVacation: "Beantragte Ferientage",
  vacationBalanceRemainingAfterSubmission: "Saldo nach Einreichung",
  vacationBalanceExceedsWarning: "Die Anfrage überschreitet das verfügbare Ferienguthaben. Die Einreichung wird in Sprint 3 noch nicht blockiert.",
  vacationBalanceAdjustmentTitle: "Saldo anpassen",
  vacationBalanceAdjustmentValue: "Anpassung",
  vacationBalanceAdjustmentReason: "Grund",
  vacationBalanceSaveAdjustment: "Anpassung speichern",
  vacationBalanceHistoryTitle: "Anpassungshistorie",
  vacationBalanceHistoryPrevious: "Vorher",
  vacationBalanceHistoryNew: "Neu",
  vacationBalanceHistoryEmpty: "Noch keine manuellen Anpassungen vorhanden.",
  vacationBalancePreviewControlsTitle: "Ferienanfrage prüfen",
  teamAdminTitle: "Team Admin Center",
  teamAdminLoading: "Team Admin Center wird geladen ...",
  teamAdminLoadError: "Team Admin Center konnte nicht geladen werden.",
  teamAdminSaveError: "Team-Einstellungen konnten nicht gespeichert werden.",
  teamAdminSavedToast: "Team-Einstellungen gespeichert",
  teamAdminAutoSaveEnabled: "Automatisches Speichern aktiv",
  teamAdminAutoSaveSaving: "Änderungen werden gespeichert ...",
  teamAdminNoManagedTeams: "Keine verwaltbaren Teams gefunden.",
  teamAdminTeamSelection: "Team-Auswahl",
  teamAdminTeamSelectionDescription: "Teams, für die du als Abteilungsleiter oder delegierter Administrator berechtigt bist.",
  teamAdminActiveTeam: "Aktives Team",
  teamAdminManagedTeam: "Verwaltetes Team",
  teamAdminAllTeams: "Alle Teams",
  teamAdminAllTeamsDescription: "Alphabetische Übersicht aller Teammitglieder für Demo-Datenpflege.",
  teamAdminTeamInformation: "Team-Informationen",
  teamAdminTeamLead: "Abteilungsleiter",
  teamAdminMemberCount: "Mitglieder",
  teamAdminDefaultApprover: "Standard-Genehmiger",
  teamAdminBackupApprover: "Backup-Genehmiger",
  teamAdminNoBackupApprover: "Kein Backup-Genehmiger",
  teamAdminDisplaySettings: "Anzeige",
  teamAdminDisplaySettingsDescription: "Anzeigeoptionen für die Planungstimeline. Gelten für die gesamte Installation.",
  teamAdminShowVacationSummary: "Ferien-Kennzahlen in der Timeline anzeigen",
  teamAdminEventColorMode: "Ereignisfarben",
  teamAdminEventColorByType: "Nach Abwesenheitstyp",
  teamAdminEventColorByTeam: "Nach Team",
  teamAdminTeamColor: "Farbe",
  teamAdminTeamColorAuto: "Automatisch",
  teamColorBlue: "Blau",
  teamColorGreen: "Grün",
  teamColorMarigold: "Gelb",
  teamColorBerry: "Beere",
  teamColorTeal: "Türkis",
  teamColorPumpkin: "Orange",
  teamColorLavender: "Violett",
  teamColorSeafoam: "Mint",
  teamColorCranberry: "Rot",
  teamColorPlatinum: "Grau",
  teamAdminApprovalPolicy: "Genehmigungsrichtlinie",
  teamAdminApprovalPolicyDescription: "Diese Richtlinie beeinflusst neue Ferienanträge und persönliche Einstellungen der Teammitglieder.",
  teamAdminAllowUserOverride: "Benutzer dürfen einen anderen Genehmiger wählen",
  teamAdminOutlookSyncPolicy: "Outlook-Synchronisation",
  teamAdminOutlookSyncOptional: "Optional",
  teamAdminOutlookSyncMandatory: "Obligatorisch",
  teamAdminOutlookSyncDisabled: "Deaktiviert",
  teamAdminAbsenceEntryTypes: "Abwesenheitstypen",
  teamAdminAbsenceEntryTypesDescription: "Abwesenheitstypen, Genehmigungspflicht und Ferienguthaben-Verhalten zentral verwalten.",
  teamAdminEntryTypeName: "Typ",
  teamAdminEntryTypeActive: "Aktiv",
  teamAdminEntryTypeRequiresApproval: "Genehmigung",
  teamAdminEntryTypeConsumesVacation: "Ferienguthaben",
  teamAdminEntryTypeActions: "Aktion",
  teamAdminEntryTypeNew: "Neuer Abwesenheitstyp",
  teamAdminEntryTypeNewPlaceholder: "z.B. Konferenz",
  teamAdminEntryTypeAdd: "Hinzufügen",
  teamAdminEntryTypeDelete: "Abwesenheitstyp löschen",
  teamAdminTeamMembers: "Teammitglieder",
  teamAdminTeamMembersDescription: "Zuordnung von Default Team, Zusatzpositionen, Pensum, Ferienguthaben, Genehmigungsbefreiung und effektivem Genehmiger.",
  teamAdminMemberAdd: "Mitglied hinzufügen",
  teamAdminMemberAddPlaceholder: "Person aus Teams Space wählen",
  teamAdminMemberAddButton: "Hinzufügen",
  teamAdminMemberName: "Name",
  teamAdminMemberEmail: "E-Mail",
  teamAdminMemberPosition: "Position",
  teamAdminMemberActions: "Aktionen",
  teamAdminMemberRemove: "Entfernen",
  teamAdminMemberRemoveConfirm: "„{name}“ aus der RPP-Planung entfernen? Die Person bleibt ggf. im M365-Team; Abwesenheits-Historie bleibt erhalten.",
  teamAdminMemberRemoveHint: "Entfernt die Person aus allen RPP-Teams dieses Hosts (nach Speichern).",
  teamAdminMemberRemoveError: "Die Person konnte nicht aus der RPP-Planung entfernt werden. Bitte erneut versuchen oder die Seite neu laden.",
  teamAdminMemberRemoveEmpty: "Für diese Person war keine RPP-Zuordnung mehr vorhanden (bereits entfernt).",
  teamAdminPrimaryTeam: "Default Team",
  teamAdminAdditionalPositions: "Zusatzpositionen",
  teamAdminEmploymentPercentage: "Pensum",
  teamAdminVacationBalance: "Ferienguthaben",
  teamAdminActiveVacationRequests: "Aktive Anträge",
  teamAdminApprovalExempt: "Keine Genehmigung erforderlich",
  teamAdminNoApprovalRequired: "Keine Genehmigung erforderlich",
  teamAdminEffectiveApprover: "Effektiver Genehmiger",
  teamAdminNotAvailable: "Nicht verfügbar",
  teamAdminSaveChanges: "Änderungen speichern",
  teamAdminTeamManagement: "Team-Verwaltung",
  teamAdminTeamManagementDescription: "Teams erstellen, umbenennen, löschen und die Anzeigereihenfolge unabhängig von der alphabetischen Sortierung festlegen.",
  teamAdminTeamManagementOrder: "Reihenfolge",
  teamAdminTeamManagementName: "Team",
  teamAdminTeamManagementOrganization: "Organisation",
  teamAdminTeamMoveUp: "Nach oben verschieben",
  teamAdminTeamMoveDown: "Nach unten verschieben",
  teamAdminTeamNew: "Neues Team",
  teamAdminTeamNewPlaceholder: "z.B. Cloud Engineering",
  teamAdminTeamAdd: "Team hinzufügen",
  teamAdminTeamDelete: "Team löschen",
  teamAdminTeamManagementUpdatedToast: "Team-Verwaltung aktualisiert",
  teamAdminTeamNameRequired: "Der Teamname darf nicht leer sein.",
  teamAdminTeamNameDuplicate: "Ein Team mit diesem Namen existiert bereits.",
  teamAdminTeamHasMembers: "Teams mit zugewiesenen Mitgliedern können nicht gelöscht werden.",
  teamAdminTeamLastTeam: "Das letzte Team kann nicht gelöscht werden.",
  teamAdminTeamRequiredStaffing: "Mindestbesetzung",
  teamCapacityRequiredStaffing: "Mindestbesetzung",
  reportsSharedPlanningTitle: "Gemeinsame Planung über Organisationen",
  reportsSharedPlanningSubtitle: "Klare Trennung/Filter nach Organisation und Standort",
  reportsOrganizationLabel: "Organisation",
  reportsOrgFilterAll: "Alle",
  reportsTableEmployee: "Mitarbeiter",
  reportsTableLocation: "Standort",
  reportsTableTeamsRoles: "Teams / Rollen",
  reportsTeamFilter: "Team",
  reportsFilterHint: "Filterbar nach Organisation, Standort und Team",
  reportsAnalysisTitle: "Analyse – Kritische Unterbesetzungen",
  reportsAnalysisSubtitle: "Visuelle Analyse & Trends (später mit Power BI)",
  reportsCriticalWeeks: "Kritische Wochen",
  reportsCriticalWeeksHint: "Unter Mindestbesetzung",
  reportsWarnings: "Warnungen",
  reportsWarningsHint: "Unter Warnschwelle",
  reportsUtilization: "Auslastung",
  reportsUtilizationHint: "Nächste 3 Monate",
  reportsChartTitle: "Auslastung über Zeit (alle Teams)",
  reportsLegendUtilization: "Auslastung",
  reportsLegendMinStaffing: "Mindestbesetzung",
  reportsLegendWarnThreshold: "Warnschwelle",
  reportsCriticalWeeksLabel: "Kritische Wochen:",
  reportsNoCriticalWeeks: "Keine kritischen Wochen",
  reportsToPowerBi: "Zu Power BI",
  reportsCriticalTeams: "kritische Teams",
  reportsCriticalWeekUtilization: "Auslastung",
  reportsMinimumAvailable: "Minimum verfügbar",
  reportsAvailableCapacity: "Verfügbar",
  reportsMyAbsencesTitle: "Meine Abwesenheiten & Outlook-Sync",
  reportsMyAbsencesSubtitle: "Persönliche Übersicht und Synchronisation",
  reportsMyAbsencesHeading: "Meine Abwesenheiten 2026",
  reportsMyAbsencesEmpty: "Keine persönlichen Abwesenheiten im aktuellen Zeitraum.",
  reportsDays: "Tage",
  reportsStatusRequested: "Beantragt",
  reportsStatusPlanned: "Geplant",
  reportsOutlookSyncTitle: "Outlook-Synchronisation",
  reportsOutlookSyncText: "Ihre Abwesenheiten werden mit Outlook synchronisiert.",
  reportsOutlookLastSync: "Letzte Synchronisation: Heute, 08:45",
  reportsOutlookSyncPending: "Wartet auf Genehmigung",
  personCardTabOverview: "Übersicht",
  personCardTabContact: "Kontakt",
  personCardTabOrganization: "Organisation",
  personCardSendQuickMessage: "Eine schnelle Nachricht senden",
  personCardLastOnline: "Zuletzt online: Vor 14 Minuten • Verfügbar um 12:00",
  personCardWorkHours: "Arbeitszeiten: 06:30 - 16:00",
  personCardInOffice: "Im Büro geplant",
  personCardSameTimezone: "Dieselbe Zeitzone wie Sie",
  personCardContactInformation: "Kontaktinformationen",
  personCardAssistant: "Assistent",
  personCardEmail: "E-Mail",
  personCardChat: "Chat",
  personCardPhoneBusiness: "Telefon (geschäftlich)",
  personCardWorkLocation: "Arbeitsort",
  personCardCompany: "Firma",
  personCardMoreContact: "Mehr Kontaktinformationen anzeigen",
  personCardDepartment: "Abteilung",
  personCardBusinessAddress: "Adresse (geschäftlich)",
  personCardClose: "Schliessen",
  personCardTeams: "Teams",
  personCardManager: "Vorgesetzte Person",
  demoDataSectionTitle: "Demo-Daten",
  demoDataSectionDescription: "Änderungen an Mock-Daten (Teams, Mindestbesetzung, Abwesenheiten, Einstellungen, Ferienguthaben, Feiertage und Schulferien) werden lokal im Browser gespeichert und überleben einen Neustart. Über Export/Import kannst du insbesondere den JSON-Block publicHolidays pflegen.",
  demoDataChangesPresent: "Es sind lokale Änderungen vorhanden.",
  demoDataResetButton: "Demo-Daten zurücksetzen",
  demoDataExportButton: "Demo-Daten exportieren",
  demoDataImportButton: "Demo-Daten importieren",
  demoDataExportFailed: "Export fehlgeschlagen. Bitte prüfen Sie Ihren Browser.",
  demoDataImportFailed: "Import fehlgeschlagen. Bitte prüfen Sie die JSON-Datei.",
  teamAdminSchoolHolidaySyncTitle: "Schulferienkalender aktualisieren",
  teamAdminSchoolHolidaySyncDescription: "Lädt die Schulferien für St. Gallen und Dübendorf/Zürich aus den hinterlegten Open-Data-JSON-Quellen und speichert sie im lokalen Mock-Kalender.",
  teamAdminSchoolHolidaySyncYear: "Kalenderjahr",
  teamAdminSchoolHolidaySyncButton: "Schulferien holen",
  teamAdminSchoolHolidaySyncRunning: "Schulferien werden geladen...",
  teamAdminSchoolHolidaySyncSuccess: "Schulferien aktualisiert für",
  teamAdminSchoolHolidaySyncDays: "Kalendertage",
  teamAdminSchoolHolidaySyncError: "Schulferien konnten nicht geladen werden. Bitte prüfen Sie Netzwerk/CORS oder nutzen Sie den JSON Import.",
  teamAdminHolidayCalendarsTitle: "Feiertagskalender",
  teamAdminHolidayCalendarsDescription: "Jeden Kalender separat konfigurieren, inklusive Farbe und eigener Abruf-Schaltfläche.",
  teamAdminCalendarRefreshButton: "Holen",
  teamAdminCalendarRefreshError: "Der Kalender konnte nicht aktualisiert werden.",
  teamAdminCalendarSourceUrl: "Kalender-URL",
  teamAdminCalendarSourceUrlPlaceholder: "https://.../calendar.json oder https://.../calendar.ics",
  teamAdminCalendarSourceType: "Format",
  teamAdminSchoolHolidaySyncStGallenNoData: "Hinweis: St. Gallen lieferte für dieses Jahr keine Einträge.",
  teamAdminSchoolHolidaySyncZurichNoData: "Hinweis: Zürich/Dübendorf lieferte für dieses Jahr keine Einträge.",
  teamAdminFederalHolidaySyncButton: "Default Feiertage Zürich holen",
  teamAdminFederalHolidaySyncRunning: "Default Feiertage Zürich werden aktualisiert...",
  teamAdminFederalHolidaySyncSuccess: "Default Feiertage Zürich aktualisiert für",
  teamAdminFederalHolidaySyncError: "Default Feiertage Zürich konnten nicht aktualisiert werden.",
  teamAdminAbsenceEntryTypesSaveHint: "Neue oder geänderte Abwesenheitstypen werden automatisch übernommen und erscheinen danach im Abwesenheitsformular.",
  navAppAdmin: "App Admin Center",
  pageAppAdminDescription: "Zentrale Anwendungsadministration für Backend-Provider, Konfiguration und Diagnose.",
  appAdminEffectiveConfigTitle: "Effektive Konfiguration",
  appAdminEffectiveConfigDescription: "Aktuell wirksame Anwendungskonfiguration inklusive Herkunft jedes Werts.",
  appAdminFieldDataSource: "Daten-Provider",
  appAdminFieldMembershipSource: "Mitgliedschaftsquelle",
  appAdminFieldSharePointSiteUrl: "SharePoint-Site-URL",
  appAdminFieldApiBaseUrl: "API-Basis-URL",
  appAdminFieldEnvironment: "Umgebung",
  appAdminFieldRelease: "Release",
  appAdminFieldRevision: "Revision",
  appAdminOriginLocalOverride: "Lokale Übersteuerung",
  appAdminOriginDeployment: "Deployment",
  appAdminOriginBuild: "Build",
  appAdminOriginDefault: "Standard",
  appAdminOriginStandaloneBrowser: "Standalone-Browser (Mock-Demo)",
  appAdminFieldStandaloneBrowserUsesMock: "Mock im Standalone-Browser",
  appAdminStandaloneBrowserUsesMockOn: "An (Browser → Mock, Teams → Deployment)",
  appAdminStandaloneBrowserUsesMockOff: "Aus",
  appAdminProviderMock: "Mock-Daten (Demo)",
  appAdminProviderSharePoint: "SharePoint-Listen",
  appAdminProviderApi: "RPP Web API",
  appAdminMembershipMock: "Mock",
  appAdminMembershipGraph: "Microsoft Graph",
  appAdminProviderConfigTitle: "Backend-Provider",
  appAdminProviderConfigDescription: "Provider-Auswahl als lokale Übersteuerung für diesen Browser. Die Deployment-Konfiguration bleibt unverändert.",
  appAdminAccessDeniedTitle: "Unberechtigt",
  appAdminAccessDeniedDescription: "Das App Admin Center erfordert die Microsoft-Entra-Rolle „Teams Administrator“ (oder „Global Administrator“). Bitte wende dich an deine IT-Administration.",
  teamAdminAccessDeniedTitle: "Unberechtigt",
  teamAdminAccessDeniedDescription: "Das Team Admin Center erfordert die Besitzer-Rolle (Owner) im aktiven Microsoft-Teams-Team.",
  activeTeamChipLabel: "Aktives Team",
  appAdminHolidayResetTitle: "Feiertagskalender zurücksetzen",
  appAdminHolidayResetDescription: "Leert den zentralen Feiertags- und Schulferienkalender dieses Tenants, damit individuelle Kalender frisch geladen werden können (Team Admin Center → Kalender-Aktionen).",
  appAdminHolidayResetButton: "Feiertagskalender leeren",
  appAdminHolidayResetConfirm: "Wirklich leeren",
  appAdminHolidayResetSuccess: "Der Kalender wurde geleert. Lade die Kalender im Team Admin Center neu.",
  appAdminHolidayResetError: "Der Kalender konnte nicht geleert werden (Berechtigung oder Verbindung prüfen).",
  appAdminSharePointSiteUrlHint: "Nur https und *.sharepoint.com.",
  appAdminApiBaseUrlHint: "Nur https (http nur für localhost).",
  appAdminCspHint: "Hinweis: Die Content-Security-Policy des Deployments muss die API-Origin in connect-src erlauben.",
  appAdminSaveOverride: "Lokal übernehmen",
  appAdminResetOverride: "Übersteuerung zurücksetzen",
  appAdminOverrideActive: "Für diesen Browser ist eine lokale Übersteuerung aktiv.",
  appAdminReloadPrompt: "Die Konfiguration wurde geändert. Die Anwendung muss neu geladen werden, damit sie wirksam wird.",
  appAdminReloadNow: "Jetzt neu laden",
  appAdminValidationSharePointUrl: "Bitte eine gültige SharePoint-Site-URL angeben (https, *.sharepoint.com).",
  appAdminValidationApiUrl: "Bitte eine gültige API-Basis-URL angeben (https, http nur für localhost).",
  appAdminConnectionTestTitle: "Verbindungstest",
  appAdminConnectionTestDescription: "Erreichbarkeit der Provider prüfen. Ergebnisse zeigen Status und Latenz.",
  appAdminTestConnection: "Verbindung testen",
  appAdminTestRunning: "Test läuft…",
  appAdminTestHealthy: "Erreichbar",
  appAdminTestFailed: "Fehlgeschlagen",
  appAdminExportTitle: "Deployment-Konfiguration",
  appAdminExportDescription: "Erzeugt eine deploybare config/runtime-config.js aus der effektiven Konfiguration.",
  appAdminExportButton: "runtime-config.js herunterladen",
  appAdminNotConfigured: "Nicht konfiguriert",
  footerText: "Microsoft Teams App Shell • Sprint 1 • Observability EO-010",

  // EO-424: Mailbox Sync
  appAdminMailboxSyncTitle: "Outlook Postfach-Synchronisation",
  appAdminMailboxSyncDescription: "Status und manuelle Steuerung des eingehenden Outlook-Abgleichs über das zentrale Postfach. E-Mails mit .ics-Kalenderanhängen werden automatisch als Abwesenheiten importiert.",
  appAdminMailboxSyncBeta: "Beta",
  appAdminMailboxSyncBetaNote: "Beta-Funktion: geprüft mit Microsoft 365. Andere Absender und Nachrichtenformate sind noch nicht vollständig getestet — bitte importierte Abwesenheiten kontrollieren.",
  appAdminMailboxSyncEnabled: "Status",
  appAdminMailboxSyncEnabledYes: "Aktiviert",
  appAdminMailboxSyncEnabledNo: "Deaktiviert",
  appAdminMailboxSyncRunning: "Läuft gerade",
  appAdminMailboxSyncRunningYes: "Ja",
  appAdminMailboxSyncRunningNo: "Nein",
  appAdminMailboxSyncLastRun: "Letzte Ausführung",
  appAdminMailboxSyncNever: "Noch nie",
  appAdminMailboxSyncProcessed: "E-Mails verarbeitet",
  appAdminMailboxSyncCreated: "Abwesenheiten erstellt",
  appAdminMailboxSyncUpdated: "Abwesenheiten aktualisiert",
  appAdminMailboxSyncDeleted: "Abwesenheiten gelöscht",
  appAdminMailboxSyncErrors: "Fehler",
  appAdminMailboxSyncSkipped: "Übersprungen",
  appAdminMailboxSyncLastError: "Grund des letzten Fehlschlags",
  appAdminMailboxSyncEntries: "Letzte Einträge",
  appAdminMailboxSyncNoData: "Keine Synchronisationsdaten vorhanden. Klicke \u201eStatus aktualisieren\u201c.",
  appAdminMailboxSyncRefresh: "Status aktualisieren",
  appAdminMailboxSyncRefreshing: "Wird geladen…",
  appAdminMailboxSyncTrigger: "Jetzt synchronisieren",
  appAdminMailboxSyncTriggering: "Synchronisation läuft…",
  appAdminMailboxSyncStatusError: "Synchronisationsstatus konnte nicht geladen werden.",
  appAdminMailboxSyncTriggerError: "Synchronisation konnte nicht gestartet werden.",
  appAdminMailboxSyncAddress: "Postfach-E-Mail-Adresse",
  appAdminMailboxSyncAddressHint: "E-Mail-Adresse des gemeinsam genutzten Postfachs, das der Sync-Dienst abfragt.",
  appAdminMailboxSyncAddressSave: "Adresse speichern",
  appAdminMailboxSyncAddressSaving: "Wird gespeichert…",
  appAdminMailboxSyncAddressSaved: "Adresse gespeichert.",
  appAdminMailboxSyncAddressError: "Adresse konnte nicht gespeichert werden.",
  appAdminMailboxSyncAddressValidation: "Bitte eine gültige E-Mail-Adresse eingeben.",

  // EO-450: Help Assistant
  navHelp: "Hilfe ?",
  pageHelpDescription: "Fragen zu RPP in natürlicher Sprache – beantwortet aus der RPP-Hilfe.",
  helpPageTitle: "Hilfe",
  helpPageDescription: "Stellen Sie Ihre Frage in eigenen Worten. Die Antworten stammen ausschliesslich aus der RPP-Hilfe.",
  helpIntroText: "Womit können wir helfen? Wählen Sie eine Frage oder schreiben Sie Ihre eigene.",
  helpAboutThisPage: "Hilfe zu dieser Seite",
  helpInputLabel: "Ihre Frage",
  helpInputPlaceholder: "Zum Beispiel: Wie erfasse ich eine halbtägige Abwesenheit?",
  helpSend: "Senden",
  helpThinking: "Antwort wird gesucht ...",
  helpAuthorYou: "Sie",
  helpAuthorAssistant: "RPP-Hilfe",
  helpSourceLabel: "Quelle",
  helpOpenPage: "Öffnen",
  helpFeedbackQuestion: "War das hilfreich?",
  helpFeedbackHelpful: "Hilfreich",
  helpFeedbackNotHelpful: "Nicht hilfreich",
  helpFeedbackThanks: "Danke für die Rückmeldung.",
  helpErrorRequestFailed: "Die Anfrage konnte nicht beantwortet werden. Bitte erneut versuchen.",
  helpOpenLabel: "Hilfe öffnen",
  helpPanelClose: "Hilfe schliessen",
  helpDisclaimer: "Die Hilfe beantwortet Fragen zur Bedienung von RPP. Sie kann keine Abwesenheiten erfassen, Anträge genehmigen oder Einstellungen ändern.",
  helpStarterHalfDay: "Wie erfasse ich eine halbtägige Abwesenheit?",
  helpStarterApproval: "Warum muss meine Ferienanfrage genehmigt werden?",
  helpStarterSecondaryTeam: "Was bedeutet «Sekundäres Team»?",
  helpStarterOutlook: "Wie synchronisiere ich eine Abwesenheit mit Outlook?",
  helpStarterPersonMissing: "Weshalb sehe ich eine Person nicht in der Planung?",
  helpStarterPresence: "Was ist der Unterschied zwischen Abwesenheit und Präsenzstatus?",
  helpMockSourceAbsences: "Abwesenheiten erfassen und bearbeiten",
  helpMockSourceApprovals: "Genehmigungen",
  helpMockSourceCapacity: "Team-Kapazität",
  helpMockSourceOutlookSync: "Outlook-Synchronisation",
  helpMockSourceTimeline: "Planungstimeline (Übersicht)",
  helpMockSourceGlossary: "RPP-Begriffslexikon",
  helpMockSourceReports: "Reports und Auswertungen",
  helpMockSourceTeamsAndRoles: "Teams, Organisationen und Rollen",
  helpMockSourceSettings: "Persönliche Einstellungen",
  helpMockSourceGettingStarted: "Erste Schritte in RPP",
  helpMockSourceTeamAdmin: "Team Admin Center für Team-Besitzer",
  helpMockAnswerHalfDay: "Setzen Sie Start und Ende auf denselben Tag und wählen Sie bei beiden dieselbe Tageshälfte – zweimal «Vormittag» oder zweimal «Nachmittag». Das sind 0,5 Tage. Mehrtägig erst nachmittags starten oder vormittags enden: nur die passende Tageshälfte setzen.",
  helpMockAnswerApprovalRequired: "Ob eine Genehmigung nötig ist, steuern drei Dinge: die Genehmigungsrichtlinie Ihres Teams, der Abwesenheitstyp und eine mögliche persönliche Befreiung. Entschieden wird in der Teams-App «Approvals». Den Stand sehen Sie unter «Genehmigungen».",
  helpMockAnswerSecondaryTeam: "Ein sekundäres Team ist jedes Team ausser dem primären. In der Oberfläche heisst es «Weitere Teams» oder «Zusatzpositionen», im Admin oft «Default Team» für das Primäre. Die Timeline-Zeile und die Kapazität hängen nur am primären Team – keine Doppelzählung.",
  helpMockAnswerOutlookSync: "In den Einstellungen unter «Outlook-Kalender» können genehmigte Abwesenheiten mit Outlook synchronisiert werden. Im Formular gibt es oft «Mit Outlook synchronisieren». Das Team kann optional, obligatorisch oder deaktiviert vorgeben – dann ist der Schalter ggf. gesperrt.",
  helpMockAnswerPersonMissing: "Prüfen Sie Filter, Zeitraum, Teamzuordnung, zugeklappte Gruppen und die M365-Teammitgliedschaft. Häufig: Die Person hat Ihr Team nur als weiteres Team – dann erscheint sie unter ihrem primären Team (Default Team).",
  helpMockAnswerPresenceVsAbsence: "Abwesenheit = nicht da (z. B. Ferien) – kann genehmigt werden und reduziert Kapazität. Präsenz = da, aber gebunden (z. B. Home Office, Projekt) – in der Regel ohne dieselbe Kapazitätswirkung.",
  helpMockAnswerWhyRed: "Rot in der Team-Kapazität heisst «Kritisch»: unter der kritischen Schwelle oder – oft – unter der Mindestbesetzung an mindestens einem Tag der Woche. Wer betroffen ist, steht unter «Betroffene Mitarbeitende».",
  helpMockAnswerVacationBalance: "Jahresanspruch, Übertrag und Anpassungen abzüglich beantragter und genehmigter Ferien. In der Timeline oft A / G / R. Immer berechnet – Abwesenheit korrigieren, nicht den Saldo «drehen».",
  helpMockAnswerReports: "«Reports» zeigt den Überblick über Teams und Organisationen: Personen, Filter, kritische Wochen. Dieselbe Kapazitätslogik wie unter Team-Kapazität.",
  helpMockAnswerRoles: "Team Admin Center: Owner im aktiven Microsoft-Teams-Team. App Admin Center: IT-Rollen in Microsoft 365. Fehlt die Rolle, fehlt der Menüpunkt. Rollen vergibt Microsoft 365, nicht RPP.",
  helpMockAnswerSettings: "Unter Einstellungen: Genehmiger (wenn erlaubt), Benachrichtigungen, Outlook-Sync. Sprache und Zeitzone kommen aus Microsoft 365 – kein Sprachumschalter in RPP.",
  helpMockAnswerGettingStarted: "RPP läuft in Microsoft Teams. Oben navigieren Sie zu Übersicht, Team-Kapazität, Genehmigungen und mehr. Abwesenheiten erfassen Sie in der Übersicht; Anträge verfolgen Sie unter Genehmigungen; Engpässe unter Team-Kapazität.",
  helpMockAnswerTeamAdmin: "Im Team Admin Center steuern Sie als Owner Genehmiger, Abwesenheitstypen, Mindestbesetzung, Outlook-Vorgabe und Teammitglieder (Default Team und Zusatzpositionen). Wechseln Sie zuerst das aktive Team. Anträge entscheiden Sie weiterhin in der Teams-App Approvals – nicht im Admin Center.",
  helpMockAnswerTeamAdminRestricted: "Das Team Admin Center und die zugehörige Anleitung sind nur für Team-Besitzer (Owner) im Microsoft-Teams-Team. Bitte wenden Sie sich an Ihren Team-Owner oder die IT, wenn Sie Regeln ändern lassen möchten.",
  helpMockAnswerUnknown: "Dazu finde ich nichts in der RPP-Hilfe. Bitte anders formulieren oder Ihre Team-Administration fragen.",
  helpStarterTeamAdmin: "Was kann ich im Team Admin Center einstellen?",
  helpStarterMinimumStaffing: "Was bewirkt die Mindestbesetzung?",
} as const;
