import type { de } from "./de";

export const en = {
  appTitle: "Resources & Presence Planning",
  appSubtitle: "Operations planning for IT resources, presence, and capacity",
  appLogoAlt: "M365 Resources & Presence Planning app logo",
  themeLight: "Light",
  themeDark: "Dark",
  themeToggle: "Toggle appearance",
  headerSearch: "Search",
  headerSearchPlaceholder: "Search (Ctrl+E)",
  moreActions: "More actions",
  help: "Help",
  teamsRailLabel: "Microsoft Teams navigation",
  teamsRailActivity: "Activity",
  teamsRailChat: "Chat",
  teamsRailTeams: "Teams",
  teamsRailCalendar: "Calendar",
  teamsRailCalls: "Calls",
  teamsRailFiles: "Files",
  teamsRailResources: "Resources",
  teamsRailApprovals: "Approvals",
  teamsRailApps: "Apps",
  primaryNavigation: "Primary navigation",
  navOverview: "Overview",
  navTeamCapacity: "Team capacity",
  navMyAbsences: "My absences",
  navApprovals: "Approvals",
  navTeamAdmin: "Team Admin Center",
  navReports: "Reports",
  navSettings: "Settings",
  navInfo: "Info",
  pageOverviewDescription: "Operational planning overview with timeline, resources, teams, and presence events.",
  pageTeamCapacityDescription: "Weekly team capacity with availability, absence share, and risk status.",
  pageMyAbsencesDescription: "Placeholder for personal absences and future request overview.",
  pageApprovalsDescription: "Placeholder for future approvals and decision workflows.",
  pageTeamAdminDescription: "Central administration for team approvers, backups, policies, and vacation visibility.",
  pageReportsDescription: "Placeholder for reporting, analytics, and export views.",
  pageSettingsDescription: "Personal settings for absence requests, approvers, notifications, and Outlook synchronization.",
  pageInfoDescription: "Information about the application, architecture, and design system foundation.",
  infoPageDescription: "RPP plans people, presence and capacity – right inside Microsoft Teams.",
  infoPageBadge: "Friends & Family",
  infoPageTitle: "RPP in Microsoft Teams",
  infoPageGoToTimeline: "Go to timeline",
  infoPageGoToReports: "Go to reports",
  infoPageStatTeamsLabel: "Organisations & teams",
  infoPageStatTeamsValue: "Fully configurable",
  infoPageStatModeLabel: "Your benefit",
  infoPageStatModeMock: "See who is available when",
  infoPageStatModeApi: "See who is available when",
  infoPageStatDeploymentLabel: "Where you work",
  infoPageStatDeploymentValue: "Right inside Microsoft Teams",
  infoCardPeopleTitle: "People and teams",
  infoCardPeopleDescription: "Timeline, team capacity, and reports use the same team and membership data. That keeps multiple organisations visible and assignments consistent.",
  infoCardPeopleStatus: "Planning view",
  infoCardDataTitle: "Your planning data",
  infoCardDataDescription: "RPP stores absences, vacation balances, holidays and team rules reliably. People and profile photos come from Microsoft 365 — planning stays in one clear place.",
  infoCardDataStatus: "Secure and consistent",
  infoCardDeliveryTitle: "Always the current version",
  infoCardDeliveryDescription: "Updates ship as one package. What you see in Teams matches the released version — no surprises between app and server.",
  infoCardDeliveryStatus: "Clear versioning",
  infoCardWhatIsRppTitle: "What is RPP Resources and Presence Planning?",
  infoCardWhatIsRppDescription: "RPP brings resource, attendance, and capacity planning together in a single application. All essential functions, from planning and approvals to administration, are available in one central place.",
  infoCardWhatIsRppStatus: "Teams-native planning",
  infoCardValueTitle: "What is the value of RPP?",
  infoCardValueDescription: "The solution creates operational visibility across multiple organisations, reduces coordination overhead, and keeps teams, roles, and absences aligned in one reliable view.",
  infoCardValueStatus: "More transparency",
  infoCardGetItTitle: "How do I get access?",
  infoCardGetItDescription: "Your organisation makes RPP available in Microsoft Teams. After that, you find the app in the Teams navigation. Team leads set up their own teams in the Team Admin Center — no extra IT ticket needed.",
  infoCardGetItStatus: "Via Microsoft Teams",
  infoFactsTitle: "What this application is about",
  infoFactsDescription: "A short overview of the architecture, operation, and collaboration between the key modules.",
  infoFactArchitectureLabel: "Architecture",
  infoFactArchitectureValue: "Teams UI, React, Vite, ASP.NET Core API",
  infoFactArchitectureText: "The experience runs as a Microsoft Teams tab and uses Fluent UI for product interactions, while the API handles delivery and persistence.",
  infoFactRolesLabel: "Roles and views",
  infoFactRolesValue: "Timeline, Team Admin, Reports, Approvals",
  infoFactRolesText: "Each tab has a clear purpose: operational planning, administration, analysis, approvals, and personal settings.",
  infoFactLocalizationLabel: "Localization",
  infoFactLocalizationValue: "German, Swiss German, English, Spanish, French, Italian, and Chinese",
  infoFactLocalizationText: "Every visible string is localizable. Spanish, French, Italian, and Chinese are also added as additional locales.",
  infoFactTeamsLabel: "Teams",
  infoFactTeamsValue: "Multiple organisations visible",
  infoFactTeamsText: "The info page reflects the product goal: platform, service, and domain teams should remain visible and understandable in one product.",
  infoRuntimeCardTitle: "Effective Configuration & Backend Diagnostics",
  infoRuntimeCardDescription: "Live frontend/backend metadata, provider status, and infrastructure targets for quick operational checks.",
  infoRuntimeFrontendTitle: "Frontend (Teams tab)",
  infoRuntimeBackendTitle: "Backend (RPP Web API)",
  infoRuntimeLabelEffectiveProvider: "Active provider mode",
  infoRuntimeLabelEnvironment: "Environment",
  infoRuntimeLabelApiBaseUrl: "API base URL",
  infoRuntimeLabelSharePointSiteUrl: "SharePoint site URL",
  infoRuntimeLabelHealthEndpoint: "Health endpoint",
  infoRuntimeLabelFrontendRelease: "Frontend release",
  infoRuntimeLabelFrontendRevision: "Frontend revision",
  infoRuntimeLabelFrontendBuild: "Frontend build time",
  infoRuntimeLabelBackendStatus: "Backend status",
  infoRuntimeLabelBackendVersion: "Backend version",
  infoRuntimeLabelBackendRevision: "Backend revision",
  infoRuntimeLabelBackendBuild: "Backend build time",
  infoRuntimeLabelBackendEnvironment: "Backend environment",
  infoRuntimeLabelBackendProvider: "Backend provider",
  infoRuntimeLabelBackendDatabaseServer: "Database server",
  infoRuntimeLabelBackendDatabaseName: "Database name",
  infoRuntimeLabelBackendWebServer: "Web server name",
  infoRuntimeLoading: "Loading backend metadata ...",
  infoRuntimeNotAvailable: "Not available",
  shellOnlyBadge: "EO-009-C",
  timelineAriaLabel: "Timeline foundation",
  timelineTitle: "Planning timeline",
  timelineThreeMonthView: "3-month view",
  timelinePeriodLabel: "Period",
  timelinePeriodNext30Days: "30 days",
  timelinePeriodNextThreeMonths: "Next 3 months",
  timelinePeriodNextSixMonths: "Next 6 months",
  timelinePeriodFullYear: "Full year",
  timelinePeriodWeek: "Week",
  timelinePeriodMonth: "Month",
  timelineGroupByLabel: "Group by",
  timelineGroupByTeams: "Teams",
  timelineGroupByPeople: "People",
  timelineViewLabel: "View",
  timelineViewGantt: "Bars (Gantt)",
  timelineViewList: "List",
  timelineViewCalendar: "Calendar (month)",
  timelineToday: "Today",
  timelineCalendarPrev: "Previous month",
  timelineCalendarNext: "Next month",
  timelineCalendarOverflow: "+{count} more",
  timelineFilter: "Filter",
  timelineFilterLabel: "Filter",
  timelineFilterPlaceholder: "Search team or person",
  timelineLegendSchoolHolidaySg: "School holidays St. Gallen",
  timelineLegendSchoolHolidayDubendorf: "School holidays Dübendorf",
  timelineLegendPublicHoliday: "Public holidays",
  timelineAvailablePeople: "Available people (total)",
  timelineMinimumStaffing: "Required minimum staffing",
  timelineCalendarWeekPrefix: "CW",
  timelineEmployeeColumn: "Employee",
  resourceCompetencies: "Roles and competencies",
  resourceVacationSummary: "Vacation summary: entitlement, booked, remaining",
  resourceVacationIcon: "🌴",
  resourceVacationEntitlement: "E",
  resourceVacationBooked: "B",
  resourceVacationRemaining: "R",
  resourceVacationEntitlementTooltip: "Vacation entitlement",
  resourceVacationBookedTooltip: "Booked",
  resourceVacationRemainingTooltip: "Remaining days",
  teamGroupingResourceCount: "resources",
  teamGroupingResourceCountCompact: "people",
  teamGroupingExpand: "Expand team group",
  teamGroupingCollapse: "Collapse team group",
  eventTypeVacation: "Vacation",
  eventTypeCompensation: "Compensation",
  eventTypeEducation: "Education",
  eventTypeHomeOffice: "Home Office",
  eventTypeTraining: "Training",
  eventTypeMilitary: "Military",
  eventTypeUnpaidLeave: "Unpaid leave",
  eventTypeOtherAbsence: "Other absence",
  eventTypeProject: "Project",
  eventTypeMaintenance: "Maintenance",
  eventTypeOnCall: "On Call",
  eventTypeStandby: "Standby",
  detailsClose: "Close",
  detailsResourceTitle: "Resource details",
  detailsPresenceTitle: "Event details",
  detailsResourceSection: "Resource",
  detailsPresenceSection: "Presence event",
  detailsOrganisation: "Organisation",
  detailsPrimaryTeam: "Primary team",
  detailsSecondaryTeams: "Secondary teams",
  detailsVacation: "Vacation",
  detailsEventType: "Event type",
  detailsEventTitle: "Title",
  detailsStartDate: "Start date",
  detailsEndDate: "End date",
  detailsDuration: "Duration",
  detailsDays: "days",
  absenceNew: "New absence",
  absencePersistError: "The absence could not be saved. Please try again.",
  approvalSubmitPending: "The request was submitted to Microsoft 365 for approval. The approver will find it in the Teams “Approvals” app.",
  approvalSubmitAutoApproved: "The absence was saved – no approval is required for this person.",
  approvalSubmitError: "The request could not be submitted. Please check the approver in the Team Admin Center and try again.",
  myApprovalsTitle: "My requests",
  myApprovalsDescription: "Your vacation requests and their Microsoft 365 status. The approver decides in the Teams “Approvals” app (Incoming for them; Sent for you).",
  myApprovalsRefresh: "Refresh status",
  myApprovalsOpenTeams: "Open Approvals in Teams",
  myApprovalsEmpty: "No requests yet. New requests are created from the Timeline (“Request approval”).",
  myApprovalsLoadError: "The requests could not be loaded. Please try again.",
  myApprovalsColPeriod: "Period",
  myApprovalsColModified: "Last modified",
  myApprovalsColM365: "M365 Approvals",
  myApprovalsM365Linked: "Linked",
  myApprovalsM365Missing: "No Graph item",
  myApprovalsGraphId: "Graph id",
  myApprovalsWhereToFind: "In the Teams Approvals app: as approver under “Received”, as requester under “Sent”. Check the environment/filter (tenant) at the top right. The item only appears for the selected approver’s account.",
  absenceApproverPolicyManaged: "Managed by the team policy",
  absenceApproverNone: "Select an approver",
  absenceApproverRequired: "Please select an approver or configure a default approver in the Team Admin Center.",
  orgConfigTitle: "Organisations & Locations",
  orgConfigDescription: "Configurable lists for partner organisations and office locations. Member values derive from the Microsoft 365 profile (company, office) and are mapped here.",
  orgConfigOrganisations: "Organisations",
  orgConfigLocations: "Locations",
  orgConfigOrganisationMappings: "Mapping profile value → organisation",
  orgConfigLocationMappings: "Mapping profile value → location",
  orgConfigUnassigned: "Unassigned",
  orgConfigAdd: "Add",
  orgConfigRemove: "Remove",
  orgConfigSave: "Save organisations & locations",
  orgConfigSaved: "Saved. Mappings take effect immediately.",
  orgConfigLoadError: "The configuration could not be loaded.",
  orgConfigSaveError: "The configuration could not be saved.",
  myApprovalsColOutlook: "Outlook",
  teamCapacityAbsentPersons: "Absent persons",
  teamCapacityAbsenceDays: "Absence (person-days)",
  teamCapacityAvailableDays: "Available (person-days)",
  absenceCreateTitle: "Request absence",
  absenceEditTitle: "Edit absence",
  absenceCreate: "Save",
  absenceRequestApproval: "Request approval",
  absenceUpdate: "Save changes",
  absenceDelete: "Delete",
  absenceDeleteConfirm: "Confirm delete",
  absenceFieldType: "Absence type",
  absenceFieldStartDate: "Start date",
  absenceFieldStartHalf: "Start day half",
  absenceFieldEndDate: "End date",
  absenceFieldEndHalf: "End day half",
  absenceFieldSubstitute: "Substitute",
  absenceFieldComment: "Comment",
  absenceSubstituteNone: "No substitute",
  absenceCalculatedWorkdays: "Working days",
  absenceSyncTitle: "Synchronization",
  absenceSyncOutlook: "Synchronize with Outlook",
  absenceApprovalStatus: "Request status",
  absenceApprovalStatusDraft: "Draft",
  absenceApprovalStatusPending: "Pending",
  absenceApprovalStatusApproved: "Approved",
  absenceApprovalStatusRejected: "Rejected",
  absenceVacationEntitlementTitle: "Vacation entitlement 2026",
  absenceVacationAvailable: "Available",
  absenceVacationBooked: "Already booked",
  absenceVacationAfterBooking: "After this booking",
  absenceCancel: "Cancel",
  vacationRequestStatus: "Request status",
  vacationRequestApprovalSection: "Approval",
  vacationRequestApprover: "Approver",
  vacationRequestCommentToApprover: "Comment to approver",
  vacationRequestSaveDraft: "Save draft",
  vacationRequestSubmitForApproval: "Submit for approval",
  approvalPrototypeTitle: "Clickable approval workflow",
  approvalPrototypeBadge: "EO-202-A mock workflow",
  approvalLiveModeBadge: "Microsoft 365 Approval Process",
  approvalPrototypeTimeline: "Approval progress",
  approvalPrototypeStepPrepare: "Prepare",
  approvalPrototypeStepReview: "Review",
  approvalPrototypeStepSubmitted: "Submitted",
  approvalPrototypeStepTeamLead: "Division Head",
  approvalPrototypeStepDecision: "Decision",
  approvalPrototypePrepareTitle: "Prepare vacation request",
  approvalPrototypePrepareDescription: "Enter the request details as they will appear in the future production surface. Everything stays local in the browser.",
  approvalPrototypeReviewTitle: "Review request",
  approvalPrototypeReviewDescription: "Check period, duration, and approver before the request is submitted in the simulation.",
  approvalPrototypeSubmittedTitle: "Request submitted",
  approvalPrototypeSubmittedDescription: "The request is now with the Division Head in the mock workflow. No real approval was started.",
  approvalPrototypeTeamLeadTitle: "Simulate Division Head decision",
  approvalPrototypeTeamLeadDescription: "Switch to the Division Head perspective and simulate approval or rejection.",
  approvalPrototypeDecisionTitle: "Workflow completed",
  approvalPrototypeDecisionDescription: "The mock workflow shows the final status. No production data was changed.",
  approvalPrototypeReviewRequest: "Review request",
  approvalPrototypeBackToEdit: "Back to editing",
  approvalPrototypeBackToPending: "Back to submitted",
  approvalPrototypeOpenTeamLead: "Open Division Head view",
  approvalPrototypeCancelRequest: "Cancel request",
  approvalPrototypeApprove: "Approve",
  approvalPrototypeReject: "Reject",
  approvalPrototypeStartNew: "Start new mock workflow",
  approvalPrototypeRoutingHint: "The approver comes from the simulated team policy and can later be replaced by the production API.",
  approvalPrototypeSubmittedMessage: "The request visibly waits for the Division Head decision. This state is temporary UI state only.",
  approvalPrototypeDecisionComment: "Decision comment",
  approvalPrototypeApprovedMessage: "The request was approved in the mock workflow.",
  approvalPrototypeRejectedMessage: "The request was rejected in the mock workflow.",
  approvalPrototypeCancelledMessage: "The request was cancelled in the mock workflow.",
  approvalPrototypeApprovedPersistedMessage: "The approved vacation was saved to the mock timeline.",
  approvalPrototypePersistError: "Could not save the approved vacation to mock state.",
  approvalPrototypeSummaryTitle: "Request summary",
  approvalPrototypeSummaryDescription: "Current mock state for demos and usability review.",
  approvalPrototypeRequester: "Requester",
  approvalPrototypeMockOnly: "Mock only, no production process",
  approvalStatusDraft: "Draft",
  approvalStatusSubmitted: "Submitted",
  approvalStatusPendingApproval: "Pending approval",
  approvalStatusApproved: "Approved",
  approvalStatusRejected: "Rejected",
  approvalStatusCancelled: "Cancelled",
  approvalStatusFailed: "Failed",
  absenceCalculatedRemainingVacation: "Remaining vacation after booking",
  absenceValidationRequired: "Please complete all required fields.",
  absenceValidationEndBeforeStart: "The end date must not be before the start date.",
  absenceValidationDuration: "The selected half-day combination does not create a valid duration.",
  absenceValidationOutsideTimeline: "The change is outside the visible timeline range.",
  absenceValidationMoveDuration: "Moving an absence must not change its duration.",
  absenceTypeVacation: "Vacation",
  absenceTypeCompensation: "Compensation",
  absenceTypeEducation: "Education",
  absenceTypeTraining: "Training",
  absenceTypeMilitary: "Military",
  absenceTypeUnpaidLeave: "Unpaid leave",
  absenceTypeOther: "Other",
  dayHalfMorning: "Morning",
  dayHalfAfternoon: "Afternoon",
  dayHalfFullDay: "Full day",
  capacityAvailable: "Available capacity",
  teamCapacityDashboardTitle: "Team capacity",
  teamCapacityDashboardDescription: "Aggregated weekly overview based on the central capacity engine.",
  teamCapacityTeamLabel: "Team",
  teamCapacityAvailable: "Available",
  teamCapacityAbsent: "Absent",
  teamCapacityUtilization: "Coverage",
  teamCapacityMembers: "Team members",
  teamCapacityNominal: "Nominal",
  teamCapacityCriticalWeeks: "Critical weeks",
  teamCapacityCriticalWeeksShort: "Critical weeks",
  teamCapacityWeeklyOverview: "Weekly overview",
  teamCapacityStatus: "Status",
  teamCapacityMetric: "Metric",
  teamCapacityAffectedResources: "Affected employees",
  teamCapacityNoAffectedResources: "No affected employees in this calendar week.",
  teamCapacityStatusOk: "OK",
  teamCapacityStatusWarning: "Warning",
  teamCapacityStatusCritical: "Critical",
  designSystemSectionTitle: "Design system foundation",
  designSystemSectionDescription: "Reusable visual patterns for upcoming Engineering Orders.",
  designCardLayoutTitle: "Layout",
  designCardLayoutDescription: "Shell, page header, content area, and responsive spacing follow one coherent grid.",
  designCardThemeTitle: "Theme",
  designCardThemeDescription: "Light and dark mode are based on Fluent UI tokens and remain extensible.",
  designCardTypographyTitle: "Typography",
  designCardTypographyDescription: "Titles, sections, and helper text use consistent sizes and weights.",
  statusReady: "Ready",
  statusFoundation: "Foundation",
  statusReserved: "Reserved",
  placeholderSurfaceTitle: "Application Shell",
  placeholderSurfaceText: "This page is intentionally a placeholder. Business functionality follows in later Engineering Orders.",
  errorBoundaryTitle: "Something went wrong.",
  errorBoundaryMessage: "The view could not be loaded. Please try again or share the reference with support.",
  errorReferenceLabel: "Reference",
  errorRetryAction: "Try again",
  runtimeConfigUnavailableTitle: "Application configuration unavailable",
  runtimeConfigUnavailableDescription: "The application cannot show reliable planning data without a valid deployment configuration.",
  planningBootstrapLoading: "Loading planning data ...",
  planningBootstrapEmptyTitle: "No plannable people found.",
  planningBootstrapEmptyMessage: "The planning view needs team members before capacity and absences can be shown.",
  planningBootstrapNoTeamContextTitle: "No team selected.",
  planningBootstrapNoTeamContextMessage: "The planning view does not know which team to show yet. Open RPP as a tab inside a team, or choose a team.",
  planningBootstrapUnauthenticatedTitle: "Sign-in required.",
  planningBootstrapUnauthenticatedMessage: "RPP could not sign in to Microsoft 365. Accept the Microsoft Teams consent dialog and try again.",
  planningBootstrapForbiddenTitle: "No access to this team.",
  planningBootstrapForbiddenMessage: "Your account is known but has no access to this team's data. Please contact your team lead.",
  teamContextPickerLoading: "Loading your teams …",
  teamContextPickerPrompt: "Which team would you like to plan?",
  teamContextPickerNoTeams: "You are not a member of any team yet. Ask your team lead to add you to one.",
  teamContextPickerFailed: "Your teams could not be loaded. Please try again.",
  mySettingsTitle: "My Settings",
  mySettingsLoading: "Loading settings ...",
  mySettingsProfileTitle: "Profile",
  mySettingsName: "Name",
  mySettingsEmail: "E-mail address",
  mySettingsTeam: "Team",
  mySettingsApprovalTitle: "Approval",
  mySettingsApprovalDescription: "Default approver and fallback for vacation requests.",
  mySettingsDefaultApprover: "Default approver",
  mySettingsFallbackApprover: "Fallback approver",
  mySettingsApproverSource: "Source",
  mySettingsApproverSourceUser: "Personal setting",
  mySettingsApproverSourceTeamPolicy: "Team policy",
  mySettingsApproverSourceTeamLead: "Division Head",
  mySettingsApproverSourceFallback: "Fallback",
  mySettingsNoApproverWarning: "No approver configured. Please contact your team admin.",
  mySettingsNotificationsTitle: "Notifications",
  mySettingsNotificationsDescription: "How you are informed about request status changes.",
  mySettingsNotificationInApp: "In-app notification",
  mySettingsNotificationEmail: "E-mail notification",
  mySettingsNotificationTeams: "Teams notification",
  mySettingsOutlookTitle: "Outlook calendar",
  mySettingsOutlookDescription: "Default behavior for approved absences.",
  mySettingsOutlookSync: "Synchronize approved vacations with Outlook",
  mySettingsOutlookEnabled: "Enabled",
  mySettingsOutlookDisabled: "Disabled",
  mySettingsOutlookManaged: "Managed by team policy",
  mySettingsRegionalTitle: "Regional",
  mySettingsRegionalDescription: "Language and time zone are inherited from Microsoft 365 or the browser.",
  mySettingsLanguage: "Language",
  mySettingsTimeZone: "Time zone",
  mySettingsManagedByTeamPolicy: "Managed by team policy",
  mySettingsNotConfigured: "Not configured",
  mySettingsSaveChanges: "Save changes",
  mySettingsResetToDefaults: "Reset to defaults",
  mySettingsSavedToast: "Settings saved",
  mySettingsResetToast: "Settings reset",
  mySettingsSaveError: "Settings could not be saved",
  outlookSyncStatusNotRequired: "No Outlook synchronization",
  outlookSyncStatusPending: "Syncing with Outlook",
  outlookSyncStatusSynced: "Outlook calendar updated",
  outlookSyncStatusFailed: "Outlook synchronization failed",
  outlookSyncRetry: "Retry synchronization",
  vacationBalanceTitle: "Vacation balance",
  vacationBalanceAnnualEntitlement: "Annual entitlement",
  vacationBalanceCarryForward: "Carry forward",
  vacationBalanceManualAdjustments: "Manual adjustments",
  vacationBalancePendingVacation: "Pending vacation",
  vacationBalanceApprovedVacation: "Approved vacation",
  vacationBalanceRemainingBalance: "Remaining balance",
  vacationBalancePreviewTitle: "Balance preview",
  vacationBalanceCurrentBalance: "Current balance",
  vacationBalanceRequestedVacation: "Requested vacation",
  vacationBalanceRemainingAfterSubmission: "Balance after submission",
  vacationBalanceExceedsWarning: "This request exceeds the available vacation balance. Sprint 3 shows a warning but does not hard-block submission.",
  vacationBalanceAdjustmentTitle: "Adjust balance",
  vacationBalanceAdjustmentValue: "Adjustment",
  vacationBalanceAdjustmentReason: "Reason",
  vacationBalanceSaveAdjustment: "Save adjustment",
  vacationBalanceHistoryTitle: "Adjustment history",
  vacationBalanceHistoryPrevious: "Previous",
  vacationBalanceHistoryNew: "New",
  vacationBalanceHistoryEmpty: "No manual adjustments yet.",
  vacationBalancePreviewControlsTitle: "Check vacation request",
  teamAdminTitle: "Team Admin Center",
  teamAdminLoading: "Loading Team Admin Center ...",
  teamAdminLoadError: "Team Admin Center could not be loaded.",
  teamAdminSaveError: "Team settings could not be saved.",
  teamAdminSavedToast: "Team settings saved",
  teamAdminAutoSaveEnabled: "Auto-save active",
  teamAdminAutoSaveSaving: "Saving changes ...",
  teamAdminNoManagedTeams: "No manageable teams found.",
  teamAdminTeamSelection: "Team selection",
  teamAdminTeamSelectionDescription: "Teams you are authorized to manage as Division Head or delegated administrator.",
  teamAdminActiveTeam: "Active team",
  teamAdminManagedTeam: "Managed team",
  teamAdminAllTeams: "All teams",
  teamAdminAllTeamsDescription: "Alphabetical overview of all team members for demo data maintenance.",
  teamAdminTeamInformation: "Team information",
  teamAdminTeamLead: "Division Head",
  teamAdminMemberCount: "Members",
  teamAdminDefaultApprover: "Default approver",
  teamAdminBackupApprover: "Backup approver",
  teamAdminNoBackupApprover: "No backup approver",
  teamAdminDisplaySettings: "Display",
  teamAdminDisplaySettingsDescription: "Display options for the planning timeline. Apply to the whole installation.",
  teamAdminShowVacationSummary: "Show vacation figures in the timeline",
  teamAdminEventColorMode: "Event colors",
  teamAdminEventColorByType: "By absence type",
  teamAdminEventColorByTeam: "By team",
  teamAdminTeamColor: "Color",
  teamAdminTeamColorAuto: "Automatic",
  teamColorBlue: "Blue",
  teamColorGreen: "Green",
  teamColorMarigold: "Yellow",
  teamColorBerry: "Berry",
  teamColorTeal: "Teal",
  teamColorPumpkin: "Orange",
  teamColorLavender: "Violet",
  teamColorSeafoam: "Mint",
  teamColorCranberry: "Red",
  teamColorPlatinum: "Gray",
  teamAdminApprovalPolicy: "Approval policy",
  teamAdminApprovalPolicyDescription: "This policy influences new vacation requests and personal settings for team members.",
  teamAdminAllowUserOverride: "Users may choose another approver",
  teamAdminOutlookSyncPolicy: "Outlook synchronization",
  teamAdminOutlookSyncOptional: "Optional",
  teamAdminOutlookSyncMandatory: "Mandatory",
  teamAdminOutlookSyncDisabled: "Disabled",
  teamAdminAbsenceEntryTypes: "Absence types",
  teamAdminAbsenceEntryTypesDescription: "Centrally manage absence types, approval requirements, and vacation balance behavior.",
  teamAdminEntryTypeName: "Type",
  teamAdminEntryTypeActive: "Active",
  teamAdminEntryTypeRequiresApproval: "Approval",
  teamAdminEntryTypeConsumesVacation: "Vacation balance",
  teamAdminEntryTypeActions: "Action",
  teamAdminEntryTypeNew: "New absence type",
  teamAdminEntryTypeNewPlaceholder: "e.g. Conference",
  teamAdminEntryTypeAdd: "Add",
  teamAdminEntryTypeDelete: "Delete absence type",
  teamAdminTeamMembers: "Team members",
  teamAdminTeamMembersDescription: "Assignment of default team, additional positions, employment, vacation balance, approval exemption, and effective approver.",
  teamAdminMemberAdd: "Add member",
  teamAdminMemberAddPlaceholder: "Choose person from Teams space",
  teamAdminMemberAddButton: "Add",
  teamAdminMemberName: "Name",
  teamAdminMemberEmail: "E-mail",
  teamAdminMemberPosition: "Position",
  teamAdminMemberActions: "Actions",
  teamAdminMemberRemove: "Remove",
  teamAdminMemberRemoveConfirm: "Remove “{name}” from RPP planning? The person may remain in the M365 team; absence history is kept.",
  teamAdminMemberRemoveHint: "Removes the person from all RPP teams on this host (after save).",
  teamAdminMemberRemoveError: "The person could not be removed from RPP planning. Try again or reload the page.",
  teamAdminMemberRemoveEmpty: "No RPP assignment was found for this person (already removed).",
  teamAdminPrimaryTeam: "Default team",
  teamAdminAdditionalPositions: "Additional positions",
  teamAdminEmploymentPercentage: "Employment",
  teamAdminVacationBalance: "Vacation balance",
  teamAdminActiveVacationRequests: "Active requests",
  teamAdminApprovalExempt: "No approval required",
  teamAdminNoApprovalRequired: "No approval required",
  teamAdminEffectiveApprover: "Effective approver",
  teamAdminNotAvailable: "Not available",
  teamAdminSaveChanges: "Save changes",
  teamAdminTeamManagement: "Team management",
  teamAdminTeamManagementDescription: "Create, rename, and delete teams and define a display order independent of alphabetical sorting.",
  teamAdminTeamManagementOrder: "Order",
  teamAdminTeamManagementName: "Team",
  teamAdminTeamManagementOrganization: "Organization",
  teamAdminTeamMoveUp: "Move up",
  teamAdminTeamMoveDown: "Move down",
  teamAdminTeamNew: "New team",
  teamAdminTeamNewPlaceholder: "e.g. Cloud Engineering",
  teamAdminTeamAdd: "Add team",
  teamAdminTeamDelete: "Delete team",
  teamAdminTeamManagementUpdatedToast: "Team management updated",
  teamAdminTeamNameRequired: "The team name must not be empty.",
  teamAdminTeamNameDuplicate: "A team with this name already exists.",
  teamAdminTeamHasMembers: "Teams with assigned members cannot be deleted.",
  teamAdminTeamLastTeam: "The last team cannot be deleted.",
  teamAdminTeamRequiredStaffing: "Required staffing",
  teamCapacityRequiredStaffing: "Required staffing",
  reportsSharedPlanningTitle: "Joint planning across organisations",
  reportsSharedPlanningSubtitle: "Clear separation/filtering by organization and location",
  reportsOrganizationLabel: "Organization",
  reportsOrgFilterAll: "All",
  reportsTableEmployee: "Employee",
  reportsTableLocation: "Location",
  reportsTableTeamsRoles: "Teams / roles",
  reportsTeamFilter: "Team",
  reportsFilterHint: "Filterable by organization, location, and team",
  reportsAnalysisTitle: "Analysis – Critical understaffing",
  reportsAnalysisSubtitle: "Visual analysis & trends (later with Power BI)",
  reportsCriticalWeeks: "Critical weeks",
  reportsCriticalWeeksHint: "Below required staffing",
  reportsWarnings: "Warnings",
  reportsWarningsHint: "Below warning threshold",
  reportsUtilization: "Utilization",
  reportsUtilizationHint: "Next 3 months",
  reportsChartTitle: "Utilization over time (all teams)",
  reportsLegendUtilization: "Utilization",
  reportsLegendMinStaffing: "Required staffing",
  reportsLegendWarnThreshold: "Warning threshold",
  reportsCriticalWeeksLabel: "Critical weeks:",
  reportsNoCriticalWeeks: "No critical weeks",
  reportsToPowerBi: "To Power BI",
  reportsCriticalTeams: "critical teams",
  reportsCriticalWeekUtilization: "Utilization",
  reportsMinimumAvailable: "Minimum available",
  reportsAvailableCapacity: "Available",
  reportsMyAbsencesTitle: "My absences & Outlook sync",
  reportsMyAbsencesSubtitle: "Personal overview and synchronization",
  reportsMyAbsencesHeading: "My absences 2026",
  reportsMyAbsencesEmpty: "No personal absences in the current period.",
  reportsDays: "days",
  reportsStatusRequested: "Requested",
  reportsStatusPlanned: "Planned",
  reportsOutlookSyncTitle: "Outlook synchronization",
  reportsOutlookSyncText: "Your absences are synchronized with Outlook.",
  reportsOutlookLastSync: "Last synchronization: Today, 08:45",
  reportsOutlookSyncPending: "Waiting for approval",
  personCardTabOverview: "Overview",
  personCardTabContact: "Contact",
  personCardTabOrganization: "Organization",
  personCardSendQuickMessage: "Send a quick message",
  personCardLastOnline: "Last online: 14 minutes ago • Available at 12:00",
  personCardWorkHours: "Work hours: 06:30 - 16:00",
  personCardInOffice: "Scheduled in office",
  personCardSameTimezone: "Same time zone as you",
  personCardContactInformation: "Contact information",
  personCardAssistant: "Assistant",
  personCardEmail: "E-mail",
  personCardChat: "Chat",
  personCardPhoneBusiness: "Phone (business)",
  personCardWorkLocation: "Work location",
  personCardCompany: "Company",
  personCardMoreContact: "Show more contact information",
  personCardDepartment: "Department",
  personCardBusinessAddress: "Address (business)",
  personCardClose: "Close",
  personCardTeams: "Teams",
  personCardManager: "Manager",
  demoDataSectionTitle: "Demo data",
  demoDataSectionDescription: "Changes to mock data (teams, required staffing, absences, settings, vacation balances, public holidays, and school holidays) are stored locally in the browser and survive a restart. Use export/import to maintain the publicHolidays JSON block.",
  demoDataChangesPresent: "Local changes are present.",
  demoDataResetButton: "Reset demo data",
  demoDataExportButton: "Export demo data",
  demoDataImportButton: "Import demo data",
  demoDataExportFailed: "Export failed. Please check your browser.",
  demoDataImportFailed: "Import failed. Please check the JSON file.",
  teamAdminSchoolHolidaySyncTitle: "Update school holiday calendars",
  teamAdminSchoolHolidaySyncDescription: "Loads school holidays for St. Gallen and Dübendorf/Zurich from the configured Open Data JSON sources and stores them in the local mock calendar.",
  teamAdminSchoolHolidaySyncYear: "Calendar year",
  teamAdminSchoolHolidaySyncButton: "Fetch school holidays",
  teamAdminSchoolHolidaySyncRunning: "Loading school holidays...",
  teamAdminSchoolHolidaySyncSuccess: "School holidays updated for",
  teamAdminSchoolHolidaySyncDays: "calendar days",
  teamAdminSchoolHolidaySyncError: "School holidays could not be loaded. Please check network/CORS or use JSON import.",
  teamAdminHolidayCalendarsTitle: "Holiday calendars",
  teamAdminHolidayCalendarsDescription: "Configure each holiday calendar separately, including its color and its own fetch action.",
  teamAdminCalendarRefreshButton: "Fetch",
  teamAdminCalendarRefreshError: "The holiday calendar could not be refreshed.",
  teamAdminCalendarSourceUrl: "Calendar URL",
  teamAdminCalendarSourceUrlPlaceholder: "https://.../calendar.json or https://.../calendar.ics",
  teamAdminCalendarSourceType: "Format",
  teamAdminSchoolHolidaySyncStGallenNoData: "Note: St. Gallen returned no records for this year.",
  teamAdminSchoolHolidaySyncZurichNoData: "Note: Zurich/Dübendorf returned no records for this year.",
  teamAdminFederalHolidaySyncButton: "Fetch default Zurich holidays",
  teamAdminFederalHolidaySyncRunning: "Updating default Zurich holidays...",
  teamAdminFederalHolidaySyncSuccess: "Default Zurich holidays updated for",
  teamAdminFederalHolidaySyncError: "Default Zurich holidays could not be updated.",
  teamAdminAbsenceEntryTypesSaveHint: "New or changed absence types are persisted automatically and then appear in the absence form.",
  navAppAdmin: "App Admin Center",
  pageAppAdminDescription: "Central application administration for backend providers, configuration, and diagnostics.",
  appAdminEffectiveConfigTitle: "Effective configuration",
  appAdminEffectiveConfigDescription: "Currently active application configuration including the origin of every value.",
  appAdminFieldDataSource: "Data provider",
  appAdminFieldMembershipSource: "Membership source",
  appAdminFieldSharePointSiteUrl: "SharePoint site URL",
  appAdminFieldApiBaseUrl: "API base URL",
  appAdminFieldEnvironment: "Environment",
  appAdminFieldRelease: "Release",
  appAdminFieldRevision: "Revision",
  appAdminOriginLocalOverride: "Local override",
  appAdminOriginDeployment: "Deployment",
  appAdminOriginBuild: "Build",
  appAdminOriginDefault: "Default",
  appAdminOriginStandaloneBrowser: "Standalone browser (mock demo)",
  appAdminFieldStandaloneBrowserUsesMock: "Mock in standalone browser",
  appAdminStandaloneBrowserUsesMockOn: "On (browser → mock, Teams → deployment)",
  appAdminStandaloneBrowserUsesMockOff: "Off",
  appAdminProviderMock: "Mock data (demo)",
  appAdminProviderSharePoint: "SharePoint lists",
  appAdminProviderApi: "RPP Web API",
  appAdminMembershipMock: "Mock",
  appAdminMembershipGraph: "Microsoft Graph",
  appAdminProviderConfigTitle: "Backend provider",
  appAdminProviderConfigDescription: "Provider selection as a local override for this browser. The deployment configuration remains unchanged.",
  appAdminAccessDeniedTitle: "Unauthorized",
  appAdminAccessDeniedDescription: "The App Admin Center requires the Microsoft Entra role “Teams Administrator” (or “Global Administrator”). Please contact your IT administration.",
  teamAdminAccessDeniedTitle: "Unauthorized",
  teamAdminAccessDeniedDescription: "The Team Admin Center requires the owner role in the active Microsoft Teams team.",
  activeTeamChipLabel: "Active team",
  appAdminHolidayResetTitle: "Reset holiday calendar",
  appAdminHolidayResetDescription: "Clears this tenant's central public/school holiday calendar so individual calendars can be loaded fresh (Team Admin Center → calendar actions).",
  appAdminHolidayResetButton: "Clear holiday calendar",
  appAdminHolidayResetConfirm: "Really clear",
  appAdminHolidayResetSuccess: "The calendar was cleared. Reload the calendars in the Team Admin Center.",
  appAdminHolidayResetError: "The calendar could not be cleared (check permission or connection).",
  appAdminSharePointSiteUrlHint: "https and *.sharepoint.com only.",
  appAdminApiBaseUrlHint: "https only (http only for localhost).",
  appAdminCspHint: "Note: the deployment's Content Security Policy must allow the API origin in connect-src.",
  appAdminSaveOverride: "Apply locally",
  appAdminResetOverride: "Reset override",
  appAdminOverrideActive: "A local override is active for this browser.",
  appAdminReloadPrompt: "The configuration was changed. Reload the application for it to take effect.",
  appAdminReloadNow: "Reload now",
  appAdminValidationSharePointUrl: "Please provide a valid SharePoint site URL (https, *.sharepoint.com).",
  appAdminValidationApiUrl: "Please provide a valid API base URL (https, http only for localhost).",
  appAdminConnectionTestTitle: "Connection test",
  appAdminConnectionTestDescription: "Check provider reachability. Results show status and latency.",
  appAdminTestConnection: "Test connection",
  appAdminTestRunning: "Testing…",
  appAdminTestHealthy: "Reachable",
  appAdminTestFailed: "Failed",
  appAdminExportTitle: "Deployment configuration",
  appAdminExportDescription: "Generates a deployable config/runtime-config.js from the effective configuration.",
  appAdminExportButton: "Download runtime-config.js",
  appAdminNotConfigured: "Not configured",
  footerText: "Microsoft Teams app shell • Sprint 1 • Observability EO-010",

  // EO-424: Mailbox Sync
  appAdminMailboxSyncTitle: "Outlook Mailbox Sync",
  appAdminMailboxSyncDescription: "Status and manual control of the inbound Outlook sync via the central mailbox. Emails with .ics calendar attachments are automatically imported as absences.",
  appAdminMailboxSyncBeta: "Beta",
  appAdminMailboxSyncBetaNote: "Beta feature: verified with Microsoft 365. Other senders and message formats are not fully tested yet — please check imported absences.",
  appAdminMailboxSyncEnabled: "Status",
  appAdminMailboxSyncEnabledYes: "Enabled",
  appAdminMailboxSyncEnabledNo: "Disabled",
  appAdminMailboxSyncRunning: "Running",
  appAdminMailboxSyncRunningYes: "Yes",
  appAdminMailboxSyncRunningNo: "No",
  appAdminMailboxSyncLastRun: "Last run",
  appAdminMailboxSyncNever: "Never",
  appAdminMailboxSyncProcessed: "Emails processed",
  appAdminMailboxSyncCreated: "Absences created",
  appAdminMailboxSyncUpdated: "Absences updated",
  appAdminMailboxSyncDeleted: "Absences deleted",
  appAdminMailboxSyncErrors: "Errors",
  appAdminMailboxSyncSkipped: "Skipped",
  appAdminMailboxSyncLastError: "Reason for the last failure",
  appAdminMailboxSyncEntries: "Latest entries",
  appAdminMailboxSyncNoData: "No sync data available. Click Refresh status.",
  appAdminMailboxSyncRefresh: "Refresh status",
  appAdminMailboxSyncRefreshing: "Loading…",
  appAdminMailboxSyncTrigger: "Sync now",
  appAdminMailboxSyncTriggering: "Syncing…",
  appAdminMailboxSyncStatusError: "Could not load sync status.",
  appAdminMailboxSyncTriggerError: "Could not start sync.",
  appAdminMailboxSyncAddress: "Mailbox email address",
  appAdminMailboxSyncAddressHint: "Email address of the shared mailbox that the sync service polls.",
  appAdminMailboxSyncAddressSave: "Save address",
  appAdminMailboxSyncAddressSaving: "Saving…",
  appAdminMailboxSyncAddressSaved: "Address saved.",
  appAdminMailboxSyncAddressError: "Could not save address.",
  appAdminMailboxSyncAddressValidation: "Please enter a valid email address.",

  // EO-450: Help Assistant
  navHelp: "Help ?",
  pageHelpDescription: "Ask about RPP in your own words – answered from the RPP help.",
  helpPageTitle: "Help",
  helpPageDescription: "Ask your question in your own words. Answers come exclusively from the RPP help.",
  helpIntroText: "What can we help with? Pick a question or write your own.",
  helpAboutThisPage: "Help with this page",
  helpInputLabel: "Your question",
  helpInputPlaceholder: "For example: how do I record a half-day absence?",
  helpSend: "Send",
  helpThinking: "Looking for an answer ...",
  helpAuthorYou: "You",
  helpAuthorAssistant: "RPP Help",
  helpSourceLabel: "Source",
  helpOpenPage: "Open",
  helpFeedbackQuestion: "Was this helpful?",
  helpFeedbackHelpful: "Helpful",
  helpFeedbackNotHelpful: "Not helpful",
  helpFeedbackThanks: "Thanks for the feedback.",
  helpErrorRequestFailed: "The question could not be answered. Please try again.",
  helpOpenLabel: "Open help",
  helpPanelClose: "Close help",
  helpDisclaimer: "The help answers questions about using RPP. It cannot create absences, approve requests or change settings.",
  helpStarterHalfDay: "How do I record a half-day absence?",
  helpStarterApproval: "Why does my vacation request need approval?",
  helpStarterSecondaryTeam: "What does “secondary team” mean?",
  helpStarterOutlook: "How do I synchronize an absence with Outlook?",
  helpStarterPersonMissing: "Why can't I see a person in the planning?",
  helpStarterPresence: "What is the difference between an absence and presence status?",
  helpMockSourceAbsences: "Creating and editing absences",
  helpMockSourceApprovals: "Approvals",
  helpMockSourceCapacity: "Team capacity",
  helpMockSourceOutlookSync: "Outlook synchronization",
  helpMockSourceTimeline: "Planning timeline (Overview)",
  helpMockSourceGlossary: "RPP glossary",
  helpMockSourceReports: "Reports and analyses",
  helpMockSourceTeamsAndRoles: "Teams, organisations and roles",
  helpMockSourceSettings: "Personal settings",
  helpMockSourceGettingStarted: "Getting started with RPP",
  helpMockSourceTeamAdmin: "Team Admin Center for team owners",
  helpMockAnswerHalfDay: "Set start and end to the same day and pick the same day half twice – Morning or Afternoon. That is 0.5 days. Multi-day starting afternoon or ending morning: set only that day half.",
  helpMockAnswerApprovalRequired: "Approval depends on three things: your team’s approval policy, the absence type, and a possible personal exemption. Decisions are made in the Teams Approvals app. Track status under Approvals.",
  helpMockAnswerSecondaryTeam: "A secondary team is any team other than the primary. The UI says Secondary teams or Additional positions; admin often says Default team for primary. Timeline row and capacity follow the primary team only – no double counting.",
  helpMockAnswerOutlookSync: "In Settings under Outlook calendar you can sync approved absences. The form often has Synchronize with Outlook. The team may set optional, mandatory, or disabled – the switch may then be locked.",
  helpMockAnswerPersonMissing: "Check filter, period, team assignment, collapsed groups, and M365 membership. Often the person has your team only as a secondary team – they appear under their primary (Default) team.",
  helpMockAnswerPresenceVsAbsence: "Absence = not here (e.g. vacation) – may need approval and reduces capacity. Presence = here but committed (e.g. home office, project) – usually without the same capacity impact.",
  helpMockAnswerWhyRed: "Red in Team capacity means Critical: below the critical threshold or – often – below required staffing on at least one day that week. Affected employees lists who is involved.",
  helpMockAnswerVacationBalance: "Annual entitlement, carry-forward and adjustments minus requested and approved vacation. On the timeline often E / B / R. Always calculated – correct the absence, do not “fix” a stored balance.",
  helpMockAnswerReports: "Reports gives the cross-team view: people, filters, critical weeks. Same capacity logic as Team capacity.",
  helpMockAnswerRoles: "Team Admin Center: Owner of the active Microsoft Teams team. App Admin Center: IT roles in Microsoft 365. Without the role the menu entry is hidden. Roles come from Microsoft 365, not RPP.",
  helpMockAnswerSettings: "In Settings: approver (if allowed), notifications, Outlook sync. Language and time zone come from Microsoft 365 – no language switcher in RPP.",
  helpMockAnswerGettingStarted: "RPP runs in Microsoft Teams. Use the top navigation for Overview, Team capacity, Approvals and more. Record absences on Overview; track requests under Approvals; check bottlenecks under Team capacity.",
  helpMockAnswerTeamAdmin: "As an owner, Team Admin Center lets you set approvers, absence types, required staffing, Outlook policy and members (Default team and additional positions). Switch the active team first. You still decide requests in the Teams Approvals app – not in Admin Center.",
  helpMockAnswerTeamAdminRestricted: "Team Admin Center and its how-to are only for team owners (Owner) in the Microsoft Teams team. Ask your team owner or IT if you need rules changed.",
  helpMockAnswerUnknown: "I can't find that in the RPP help. Please rephrase or ask your team administration.",
  helpStarterTeamAdmin: "What can I configure in Team Admin Center?",
  helpStarterMinimumStaffing: "What does required staffing do?",
} satisfies Record<keyof typeof de, string>;
