import type { de } from "./de";

export const es = {
  teamsRailLabel: "Navegación de Microsoft Teams",
  teamsRailActivity: "Actividad",
  teamsRailChat: "Chat",
  teamsRailTeams: "Equipos",
  teamsRailCalendar: "Calendario",
  teamsRailCalls: "Llamadas",
  teamsRailFiles: "Archivos",
  teamsRailResources: "Recursos",
  teamsRailApprovals: "Aprobaciones",
  teamsRailApps: "Aplicaciones",
  primaryNavigation: "Navegación principal",
  infoPageDescription: "RPP es la plataforma de planificación operativa de recursos IT, presencia y capacidad – nativa de Microsoft Teams.",
  infoPageBadge: "Release Candidate 5",
  infoPageTitle: "RPP – Planificación de Recursos y Presencia",
  infoPageGoToTimeline: "Ir a la cronología",
  infoPageGoToReports: "Ir a los informes",
  infoPageStatTeamsLabel: "Organizaciones y equipos",
  infoPageStatTeamsValue: "Configurable",
  infoPageStatModeLabel: "Modo de datos",
  infoPageStatModeMock: "Mock / demo",
  infoPageStatModeApi: "API / producción",
  infoPageStatDeploymentLabel: "Despliegue",
  infoPageStatDeploymentValue: "Pestaña Teams + Web API + SQL",
  infoCardPeopleTitle: "Personas y equipos",
  infoCardPeopleDescription: "Cada persona puede pertenecer a varios equipos y tener múltiples roles. La cronología, la capacidad del equipo y los informes comparten la misma base de miembros: consistente y transversal a las organizaciones.",
  infoCardPeopleStatus: "Multi-equipo, multi-rol",
  infoCardDataTitle: "Datos y persistencia",
  infoCardDataDescription: "Equipos, miembros, saldos de vacaciones, días festivos y políticas de aprobación se almacenan en el backend SQL. Microsoft Graph proporciona identidades y fotos de perfil; la aplicación sigue siendo la única fuente de verdad de planificación.",
  infoCardDataStatus: "SQL Server + Microsoft Graph",
  infoCardDeliveryTitle: "Entrega",
  infoCardDeliveryDescription: "Frontend, Web API y paquete de Teams se versionan y despliegan juntos. Lo que ves en el cliente de Teams coincide exactamente con la versión desplegada: sin sorpresas.",
  infoCardDeliveryStatus: "Versiones controladas",
  infoCardWhatIsRppTitle: "¿Qué es RPP?",
  infoCardWhatIsRppDescription: "RPP es la aplicación central de Teams para la planificación operativa de recursos, presencia y capacidad. Reúne cronología, vista de equipos, panel de capacidad, flujos de aprobación y administración en un solo espacio de trabajo coherente.",
  infoCardWhatIsRppStatus: "Plataforma de planificación operativa",
  infoCardValueTitle: "¿Para qué sirve RPP?",
  infoCardValueDescription: "RPP crea transparencia operativa entre organizaciones. Los jefes de equipo ven de un vistazo quién está disponible, dónde hay cuellos de botella y qué ausencias están aprobadas: sin correos, hojas de cálculo ni idas y venidas.",
  infoCardValueStatus: "Visibilidad y apoyo a la decisión",
  infoCardGetItTitle: "¿Cómo se obtiene?",
  infoCardGetItDescription: "RPP se aprovisiona como aplicación de Teams en tu tenant. Una vez instalada, aparece en la navegación de Teams. Los jefes de equipo configuran sus equipos en el Centro de Administración de Equipos: sin necesidad de tickets de TI.",
  infoCardGetItStatus: "Tienda de aplicaciones Teams (tenant)",
  infoFactsTitle: "De un vistazo",
  infoFactsDescription: "Arquitectura, módulos y funcionamiento de la plataforma.",
  infoFactArchitectureLabel: "Arquitectura",
  infoFactArchitectureValue: "React · Vite · Fluent UI · ASP.NET Core · SQL Server",
  infoFactArchitectureText: "El frontend se ejecuta como pestaña de Teams (Vite SPA, Fluent UI v9). La Web API (ASP.NET Core 8) gestiona toda la lógica de negocio, persistencia e integración con Graph. SQL Server almacena todos los datos de planificación.",
  infoFactRolesLabel: "Módulos",
  infoFactRolesValue: "Cronología · Calendario · Capacidad del equipo · Admin. de equipos · Admin. de la app · Informes · Aprobaciones · Configuración",
  infoFactRolesText: "Cada módulo tiene un propósito definido: planificación, administración, análisis, aprobaciones, configuración y ajustes personales.",
  infoFactLocalizationLabel: "Localización",
  infoFactLocalizationValue: "Alemán, inglés + 36 archivos de idioma adicionales",
  infoFactLocalizationText: "Todo el texto visible es localizable. Los idiomas principales son alemán e inglés; el sistema de traducción admite 38 configuraciones regionales.",
  infoFactTeamsLabel: "Multi-organización",
  infoFactTeamsValue: "Múltiples organizaciones · ampliable",
  infoFactTeamsText: "Organizaciones, ubicaciones y equipos son configurables sin cambios de código. La plataforma está diseñada para incorporar organizaciones adicionales.",
  shellOnlyBadge: "EO-009-C",
  timelineAriaLabel: "Base de la cronología",
  timelineTitle: "Cronología de planificación",
  timelineThreeMonthView: "Vista de 3 meses",
  timelinePeriodLabel: "Período",
  timelinePeriodNext30Days: "30 días",
  timelinePeriodNextThreeMonths: "Próximos 3 meses",
  timelinePeriodNextSixMonths: "Próximos 6 meses",
  timelinePeriodFullYear: "Año completo",
  timelineGroupByLabel: "Agrupar por",
  timelineGroupByTeams: "Equipos",
  timelineGroupByPeople: "Personas",
  timelineViewLabel: "Vista",
  timelineViewGantt: "Barras (Gantt)",
  timelineViewList: "Lista",
  timelineViewCalendar: "Calendario (mes)",
  timelineCalendarPrev: "Mes anterior",
  timelineCalendarNext: "Mes siguiente",
  timelineCalendarOverflow: "+{count} más",
  timelineLegendSchoolHolidaySg: "Vacaciones escolares St. Gallen",
  timelineLegendSchoolHolidayDubendorf: "Vacaciones escolares Dübendorf",
  timelineLegendPublicHoliday: "Días festivos",
  timelineAvailablePeople: "Personas disponibles (total)",
  timelineMinimumStaffing: "Dotación mínima requerida",
  timelineCalendarWeekPrefix: "SE",
  timelineEmployeeColumn: "Empleado",
  resourceCompetencies: "Roles y competencias",
  resourceVacationSummary: "Resumen de vacaciones: derecho, reservado, restante",
  resourceVacationIcon: "🌴",
  resourceVacationEntitlement: "D",
  resourceVacationBooked: "R",
  resourceVacationRemaining: "S",
  resourceVacationEntitlementTooltip: "Derecho de vacaciones",
  resourceVacationBookedTooltip: "Reservado",
  resourceVacationRemainingTooltip: "Días restantes",
  teamGroupingResourceCount: "recursos",
  teamGroupingResourceCountCompact: "pers.",
  teamGroupingExpand: "Expandir grupo de equipo",
  teamGroupingCollapse: "Contraer grupo de equipo",
  eventTypeVacation: "Vacaciones",
  eventTypeCompensation: "Compensación",
  eventTypeEducation: "Formación",
  eventTypeHomeOffice: "Teletrabajo",
  eventTypeTraining: "Capacitación",
  eventTypeMilitary: "Servicio militar",
  eventTypeUnpaidLeave: "Permiso no remunerado",
  eventTypeOtherAbsence: "Otra ausencia",
  eventTypeProject: "Proyecto",
  eventTypeMaintenance: "Mantenimiento",
  eventTypeOnCall: "Guardia",
  eventTypeStandby: "Disponibilidad",
  detailsResourceTitle: "Detalles del recurso",
  detailsPresenceTitle: "Detalles del evento",
  detailsResourceSection: "Recurso",
  detailsPresenceSection: "Evento de presencia",
  detailsOrganisation: "Organización",
  detailsPrimaryTeam: "Equipo principal",
  detailsSecondaryTeams: "Equipos adicionales",
  detailsVacation: "Vacaciones",
  detailsEventType: "Tipo de evento",
  detailsEventTitle: "Título",
  detailsStartDate: "Fecha de inicio",
  detailsEndDate: "Fecha de fin",
  detailsDuration: "Duración",
  detailsDays: "días",
  absenceNew: "Nueva ausencia",
  absencePersistError: "No se pudo guardar la ausencia. Inténtelo de nuevo.",
  approvalSubmitPending: "La solicitud se envió a Microsoft 365 para su aprobación. El aprobador la encontrará en la aplicación Teams «Approvals».",
  approvalSubmitAutoApproved: "La ausencia se guardó – no se requiere aprobación para esta persona.",
  approvalSubmitError: "No se pudo enviar la solicitud. Verifique el aprobador en el Centro de Administración de Equipos e inténtelo de nuevo.",
  myApprovalsTitle: "Mis solicitudes",
  myApprovalsDescription: "Solicitudes de vacaciones con estado de aprobación de Microsoft 365. Las decisiones se toman en la aplicación Teams «Approvals».",
  myApprovalsRefresh: "Actualizar estado",
  myApprovalsOpenTeams: "Abrir Approvals en Teams",
  myApprovalsEmpty: "Aún no hay solicitudes. Las nuevas solicitudes se crean desde la cronología («Solicitar aprobación»).",
  myApprovalsLoadError: "No se pudieron cargar las solicitudes. Inténtelo de nuevo.",
  myApprovalsColPeriod: "Período",
  myApprovalsColModified: "Última modificación",
  myApprovalsColM365: "M365 Approvals",
  myApprovalsM365Linked: "Linked",
  myApprovalsM365Missing: "No Graph item",
  myApprovalsGraphId: "Graph id",
  myApprovalsWhereToFind: "In the Teams Approvals app: as approver under Received, as requester under Sent. Check the environment filter (tenant). The item only appears for the selected approver account.",
  absenceApproverPolicyManaged: "Gestionado por la política del equipo",
  absenceApproverNone: "Select an approver",
  absenceApproverRequired: "Please select an approver or configure a default approver in the Team Admin Center.",
  orgConfigTitle: "Organizaciones y ubicaciones",
  orgConfigDescription: "Listas configurables para organizaciones asociadas y ubicaciones. Los valores de los miembros se derivan del perfil de Microsoft 365 (empresa, oficina) y se asignan aquí.",
  orgConfigOrganisations: "Organizaciones",
  orgConfigLocations: "Ubicaciones",
  orgConfigOrganisationMappings: "Asignación valor de perfil → organización",
  orgConfigLocationMappings: "Asignación valor de perfil → ubicación",
  orgConfigUnassigned: "Sin asignar",
  orgConfigAdd: "Añadir",
  orgConfigRemove: "Eliminar",
  orgConfigSave: "Guardar organizaciones y ubicaciones",
  orgConfigSaved: "Guardado. Las asignaciones surten efecto inmediato.",
  orgConfigLoadError: "No se pudo cargar la configuración.",
  orgConfigSaveError: "No se pudo guardar la configuración.",
  myApprovalsColOutlook: "Outlook",
  teamCapacityAbsentPersons: "Personas ausentes",
  teamCapacityAbsenceDays: "Ausencia (días-persona)",
  teamCapacityAvailableDays: "Disponible (días-persona)",
  absenceCreateTitle: "Solicitar ausencia",
  absenceEditTitle: "Editar ausencia",
  absenceRequestApproval: "Solicitar aprobación",
  absenceDeleteConfirm: "Confirmar eliminación",
  absenceFieldType: "Tipo de ausencia",
  absenceFieldStartDate: "Fecha de inicio",
  absenceFieldStartHalf: "Mitad del día de inicio",
  absenceFieldEndDate: "Fecha de fin",
  absenceFieldEndHalf: "Mitad del día de fin",
  absenceFieldSubstitute: "Suplente",
  absenceFieldComment: "Comentario",
  absenceSubstituteNone: "Sin suplente",
  absenceCalculatedWorkdays: "Días laborables",
  absenceSyncTitle: "Sincronización",
  absenceSyncOutlook: "Sincronizar con Outlook",
  absenceApprovalStatus: "Estado de la solicitud",
  absenceApprovalStatusDraft: "Borrador",
  absenceApprovalStatusPending: "Pendiente",
  absenceApprovalStatusApproved: "Aprobado",
  absenceApprovalStatusRejected: "Rechazado",
  absenceVacationEntitlementTitle: "Derecho de vacaciones 2026",
  absenceVacationAvailable: "Disponible",
  absenceVacationBooked: "Ya reservado",
  absenceVacationAfterBooking: "Después de esta reserva",
  vacationRequestStatus: "Estado de la solicitud",
  vacationRequestApprovalSection: "Aprobación",
  vacationRequestApprover: "Aprobador",
  vacationRequestCommentToApprover: "Comentario para el aprobador",
  vacationRequestSaveDraft: "Guardar borrador",
  vacationRequestSubmitForApproval: "Enviar para aprobación",
  approvalPrototypeTitle: "Flujo de aprobación interactivo",
  approvalPrototypeBadge: "EO-202-A Flujo simulado",
  approvalLiveModeBadge: "Proceso de aprobación Microsoft 365",
  approvalPrototypeTimeline: "Progreso de la aprobación",
  approvalPrototypeStepPrepare: "Preparar",
  approvalPrototypeStepReview: "Revisar",
  approvalPrototypeStepSubmitted: "Enviado",
  approvalPrototypeStepTeamLead: "Jefe de departamento",
  approvalPrototypeStepDecision: "Decisión",
  approvalPrototypePrepareTitle: "Preparar solicitud de vacaciones",
  approvalPrototypePrepareDescription: "Introduzca los datos de la solicitud como en la futura interfaz productiva. Todo permanece local en el navegador.",
  approvalPrototypeReviewTitle: "Revisar solicitud",
  approvalPrototypeReviewDescription: "Verifique el período, la duración y el aprobador antes de enviar la solicitud simulada.",
  approvalPrototypeSubmittedTitle: "Solicitud enviada",
  approvalPrototypeSubmittedDescription: "La solicitud está en el flujo simulado con el jefe de departamento. No se ha iniciado ninguna aprobación real.",
  approvalPrototypeTeamLeadTitle: "Simular decisión del jefe de departamento",
  approvalPrototypeTeamLeadDescription: "Cambie a la perspectiva del jefe de departamento y simule la aprobación o el rechazo.",
  approvalPrototypeDecisionTitle: "Flujo completado",
  approvalPrototypeDecisionDescription: "El flujo simulado muestra el estado final. No se modificaron datos productivos.",
  approvalPrototypeReviewRequest: "Revisar solicitud",
  approvalPrototypeBackToEdit: "Volver a editar",
  approvalPrototypeBackToPending: "Volver a enviado",
  approvalPrototypeOpenTeamLead: "Abrir vista del jefe de departamento",
  approvalPrototypeCancelRequest: "Cancelar solicitud",
  approvalPrototypeApprove: "Aprobar",
  approvalPrototypeReject: "Rechazar",
  approvalPrototypeStartNew: "Iniciar nuevo flujo simulado",
  approvalPrototypeRoutingHint: "El aprobador proviene de la política de equipo simulada y podrá ser reemplazado por la API productiva más adelante.",
  approvalPrototypeSubmittedMessage: "La solicitud espera visiblemente la decisión del jefe de departamento. Este estado es solo temporal en la UI.",
  approvalPrototypeDecisionComment: "Comentario de decisión",
  approvalPrototypeApprovedMessage: "La solicitud fue aprobada en el flujo simulado.",
  approvalPrototypeRejectedMessage: "La solicitud fue rechazada en el flujo simulado.",
  approvalPrototypeCancelledMessage: "La solicitud fue cancelada en el flujo simulado.",
  approvalPrototypeApprovedPersistedMessage: "Las vacaciones aprobadas se guardaron en la cronología simulada.",
  approvalPrototypePersistError: "No se pudieron guardar las vacaciones aprobadas en el estado simulado.",
  approvalPrototypeSummaryTitle: "Resumen de la solicitud",
  approvalPrototypeSummaryDescription: "Estado simulado actual para demostración y revisión de usabilidad.",
  approvalPrototypeRequester: "Solicitante",
  approvalPrototypeMockOnly: "Solo simulación, no es un proceso productivo",
  approvalStatusDraft: "Borrador",
  approvalStatusSubmitted: "Enviado",
  approvalStatusPendingApproval: "Esperando aprobación",
  approvalStatusApproved: "Aprobado",
  approvalStatusRejected: "Rechazado",
  approvalStatusCancelled: "Cancelado",
  approvalStatusFailed: "Fallido",
  absenceCalculatedRemainingVacation: "Vacaciones restantes después de la reserva",
  absenceValidationRequired: "Complete todos los campos obligatorios.",
  absenceValidationEndBeforeStart: "La fecha de fin no puede ser anterior a la fecha de inicio.",
  absenceValidationDuration: "La combinación de medias jornadas seleccionada no produce una duración válida.",
  absenceValidationOutsideTimeline: "El cambio está fuera del período visible.",
  absenceValidationMoveDuration: "El desplazamiento no debe cambiar la duración de la ausencia.",
  absenceTypeVacation: "Vacaciones",
  absenceTypeCompensation: "Compensación",
  absenceTypeEducation: "Formación",
  absenceTypeTraining: "Capacitación",
  absenceTypeMilitary: "Servicio militar",
  absenceTypeUnpaidLeave: "Permiso no remunerado",
  absenceTypeOther: "Otro",
  dayHalfMorning: "Mañana",
  dayHalfAfternoon: "Tarde",
  dayHalfFullDay: "Día completo",
  capacityAvailable: "Capacidad disponible",
  teamCapacityDashboardTitle: "Capacidad del equipo",
  teamCapacityDashboardDescription: "Resumen semanal agregado basado en el motor central de capacidad.",
  teamCapacityTeamLabel: "Equipo",
  teamCapacityAvailable: "Disponible",
  teamCapacityAbsent: "Ausente",
  teamCapacityUtilization: "Ocupación",
  teamCapacityMembers: "Miembros del equipo",
  teamCapacityNominal: "Nominal",
  teamCapacityCriticalWeeks: "Semanas críticas",
  teamCapacityCriticalWeeksShort: "Sem. críticas",
  teamCapacityWeeklyOverview: "Resumen semanal",
  teamCapacityStatus: "Estado",
  teamCapacityMetric: "Indicador",
  teamCapacityAffectedResources: "Empleados afectados",
  teamCapacityNoAffectedResources: "Sin empleados afectados en esta semana calendario.",
  teamCapacityStatusOk: "OK",
  teamCapacityStatusWarning: "Advertencia",
  teamCapacityStatusCritical: "Crítico",
  designSystemSectionTitle: "Fundamentos del sistema de diseño",
  designSystemSectionDescription: "Patrones visuales reutilizables para próximas órdenes de ingeniería.",
  designCardLayoutTitle: "Maquetación",
  designCardLayoutDescription: "Shell, encabezado, área de contenido y espaciado responsive siguen una cuadrícula uniforme.",
  designCardThemeTitle: "Tema",
  designCardThemeDescription: "Modos claro y oscuro basados en tokens de Fluent UI, extensibles.",
  designCardTypographyTitle: "Tipografía",
  designCardTypographyDescription: "Títulos, secciones y textos de ayuda utilizan tamaños y pesos consistentes.",
  statusReady: "Listo",
  statusFoundation: "Base",
  statusReserved: "Reservado",
  placeholderSurfaceTitle: "Shell de aplicación",
  placeholderSurfaceText: "Esta página es intencionalmente un marcador de posición. La funcionalidad especializada seguirá en futuras órdenes de ingeniería.",
  errorBoundaryTitle: "Algo salió mal.",
  errorBoundaryMessage: "No se pudo cargar la vista. Inténtelo de nuevo o informe la referencia al soporte.",
  errorReferenceLabel: "Referencia",
  planningBootstrapEmptyTitle: "No se encontraron personas planificables.",
  planningBootstrapEmptyMessage: "La vista de planificación necesita miembros del equipo antes de poder mostrar capacidad y ausencias.",
  mySettingsTitle: "Mi configuración",
  mySettingsLoading: "Cargando configuración...",
  mySettingsProfileTitle: "Perfil",
  mySettingsName: "Nombre",
  mySettingsEmail: "Correo electrónico",
  mySettingsTeam: "Equipo",
  mySettingsApprovalTitle: "Aprobación",
  mySettingsApprovalDescription: "Aprobador predeterminado y suplente para solicitudes de vacaciones.",
  mySettingsDefaultApprover: "Aprobador predeterminado",
  mySettingsFallbackApprover: "Aprobador suplente",
  mySettingsApproverSource: "Origen",
  mySettingsApproverSourceUser: "Configuración personal",
  mySettingsApproverSourceTeamPolicy: "Política del equipo",
  mySettingsApproverSourceTeamLead: "Jefe de departamento",
  mySettingsApproverSourceFallback: "Suplente",
  mySettingsNoApproverWarning: "No se ha configurado ningún aprobador. Contacte al administrador del equipo.",
  mySettingsNotificationsTitle: "Notificaciones",
  mySettingsNotificationsDescription: "Cómo se le informará sobre cambios de estado de sus solicitudes.",
  mySettingsNotificationInApp: "Notificación en la aplicación",
  mySettingsNotificationEmail: "Notificación por correo",
  mySettingsNotificationTeams: "Notificación de Teams",
  mySettingsOutlookTitle: "Calendario de Outlook",
  mySettingsOutlookDescription: "Comportamiento predeterminado para ausencias aprobadas.",
  mySettingsOutlookSync: "Sincronizar vacaciones aprobadas con Outlook",
  mySettingsOutlookEnabled: "Activado",
  mySettingsOutlookDisabled: "Desactivado",
  mySettingsOutlookManaged: "Gestionado por política del equipo",
  mySettingsRegionalTitle: "Regional",
  mySettingsRegionalDescription: "El idioma y la zona horaria se toman de Microsoft 365 o del navegador.",
  mySettingsLanguage: "Idioma",
  mySettingsTimeZone: "Zona horaria",
  mySettingsManagedByTeamPolicy: "Gestionado por política del equipo",
  mySettingsNotConfigured: "No configurado",
  mySettingsResetToDefaults: "Restablecer valores predeterminados",
  mySettingsSavedToast: "Configuración guardada",
  mySettingsResetToast: "Configuración restablecida",
  outlookSyncStatusNotRequired: "Sin sincronización con Outlook",
  outlookSyncStatusPending: "Sincronización en curso",
  outlookSyncStatusSynced: "Calendario de Outlook actualizado",
  outlookSyncStatusFailed: "Sincronización con Outlook fallida",
  outlookSyncRetry: "Reintentar sincronización",
  vacationBalanceTitle: "Saldo de vacaciones",
  vacationBalanceAnnualEntitlement: "Derecho anual",
  vacationBalanceCarryForward: "Traslado",
  vacationBalanceManualAdjustments: "Ajustes manuales",
  vacationBalancePendingVacation: "Vacaciones solicitadas",
  vacationBalanceApprovedVacation: "Vacaciones aprobadas",
  vacationBalanceRemainingBalance: "Saldo restante",
  vacationBalancePreviewTitle: "Vista previa del saldo",
  vacationBalanceCurrentBalance: "Saldo actual",
  vacationBalanceRequestedVacation: "Días de vacaciones solicitados",
  vacationBalanceRemainingAfterSubmission: "Saldo después del envío",
  vacationBalanceExceedsWarning: "La solicitud supera el saldo de vacaciones disponible. El envío no se bloqueará en el Sprint 3.",
  vacationBalanceAdjustmentTitle: "Ajustar saldo",
  vacationBalanceAdjustmentValue: "Ajuste",
  vacationBalanceAdjustmentReason: "Motivo",
  vacationBalanceSaveAdjustment: "Guardar ajuste",
  vacationBalanceHistoryTitle: "Historial de ajustes",
  vacationBalanceHistoryPrevious: "Anterior",
  vacationBalanceHistoryNew: "Nuevo",
  vacationBalanceHistoryEmpty: "Aún no hay ajustes manuales.",
  vacationBalancePreviewControlsTitle: "Revisar solicitud de vacaciones",
  teamAdminTitle: "Centro de Administración de Equipos",
  teamAdminLoading: "Cargando Centro de Administración de Equipos...",
  teamAdminLoadError: "No se pudo cargar el Centro de Administración de Equipos.",
  teamAdminSavedToast: "Ajustes del equipo guardados",
  teamAdminAutoSaveEnabled: "Guardado automático activado",
  teamAdminAutoSaveSaving: "Guardando cambios...",
  teamAdminNoManagedTeams: "No se encontraron equipos administrables.",
  teamAdminTeamSelection: "Selección de equipo",
  teamAdminTeamSelectionDescription: "Equipos para los que tiene autorización como jefe de departamento o administrador delegado.",
  teamAdminActiveTeam: "Equipo activo",
  teamAdminManagedTeam: "Equipo administrado",
  teamAdminAllTeams: "Todos los equipos",
  teamAdminAllTeamsDescription: "Resumen alfabético de todos los miembros del equipo para mantenimiento de datos de demostración.",
  teamAdminTeamInformation: "Información del equipo",
  teamAdminTeamLead: "Jefe de departamento",
  teamAdminMemberCount: "Miembros",
  teamAdminDefaultApprover: "Aprobador predeterminado",
  teamAdminBackupApprover: "Aprobador suplente",
  teamAdminNoBackupApprover: "Sin aprobador suplente",
  teamAdminDisplaySettings: "Visualización",
  teamAdminDisplaySettingsDescription: "Opciones de visualización para la cronología de planificación. Aplican a toda la instalación.",
  teamAdminShowVacationSummary: "Mostrar cifras de vacaciones en la cronología",
  teamAdminEventColorMode: "Colores de eventos",
  teamAdminEventColorByType: "Por tipo de ausencia",
  teamAdminEventColorByTeam: "Por equipo",
  teamAdminTeamColor: "Color",
  teamAdminTeamColorAuto: "Automático",
  teamColorBlue: "Azul",
  teamColorGreen: "Verde",
  teamColorMarigold: "Amarillo",
  teamColorBerry: "Baya",
  teamColorTeal: "Turquesa",
  teamColorPumpkin: "Naranja",
  teamColorLavender: "Violeta",
  teamColorSeafoam: "Menta",
  teamColorCranberry: "Rojo",
  teamColorPlatinum: "Gris",
  teamAdminApprovalPolicy: "Política de aprobación",
  teamAdminApprovalPolicyDescription: "Esta política afecta a las nuevas solicitudes de vacaciones y a la configuración personal de los miembros del equipo.",
  teamAdminAllowUserOverride: "Los usuarios pueden elegir otro aprobador",
  teamAdminOutlookSyncPolicy: "Sincronización con Outlook",
  teamAdminOutlookSyncOptional: "Opcional",
  teamAdminOutlookSyncMandatory: "Obligatorio",
  teamAdminOutlookSyncDisabled: "Desactivado",
  teamAdminAbsenceEntryTypes: "Tipos de ausencia",
  teamAdminAbsenceEntryTypesDescription: "Administrar centralmente los tipos de ausencia, la obligación de aprobación y el consumo de saldo de vacaciones.",
  teamAdminEntryTypeName: "Tipo",
  teamAdminEntryTypeActive: "Activo",
  teamAdminEntryTypeRequiresApproval: "Aprobación",
  teamAdminEntryTypeConsumesVacation: "Saldo de vacaciones",
  teamAdminEntryTypeActions: "Acción",
  teamAdminEntryTypeNew: "Nuevo tipo de ausencia",
  teamAdminEntryTypeNewPlaceholder: "p. ej. Conferencia",
  teamAdminEntryTypeAdd: "Añadir",
  teamAdminEntryTypeDelete: "Eliminar tipo de ausencia",
  teamAdminTeamMembers: "Miembros del equipo",
  teamAdminTeamMembersDescription: "Asignación de equipo predeterminado, posiciones adicionales, jornada, saldo de vacaciones, exención de aprobación y aprobador efectivo.",
  teamAdminMemberAdd: "Añadir miembro",
  teamAdminMemberAddPlaceholder: "Seleccionar persona del espacio de Teams",
  teamAdminMemberAddButton: "Añadir",
  teamAdminMemberName: "Nombre",
  teamAdminMemberEmail: "Correo electrónico",
  teamAdminMemberPosition: "Cargo",
  teamAdminMemberActions: "Actions",
  teamAdminMemberRemove: "Remove",
  teamAdminMemberRemoveConfirm: "Remove \"{name}\" from RPP planning? The person may remain in the M365 team; absence history is kept.",
  teamAdminMemberRemoveHint: "Removes the person from all RPP teams on this host (after save).",
  teamAdminMemberRemoveError: "The person could not be removed from RPP planning. Try again or reload the page.",
  teamAdminMemberRemoveEmpty: "No RPP assignment was found for this person (already removed).",
  teamAdminPrimaryTeam: "Equipo predeterminado",
  teamAdminAdditionalPositions: "Cargos adicionales",
  teamAdminEmploymentPercentage: "Jornada",
  teamAdminVacationBalance: "Saldo de vacaciones",
  teamAdminActiveVacationRequests: "Solicitudes activas",
  teamAdminApprovalExempt: "Sin aprobación requerida",
  teamAdminNoApprovalRequired: "Sin aprobación requerida",
  teamAdminEffectiveApprover: "Aprobador efectivo",
  teamAdminNotAvailable: "No disponible",
  teamAdminTeamManagement: "Gestión de equipos",
  teamAdminTeamManagementDescription: "Crear, renombrar y eliminar equipos, y definir el orden de visualización independientemente del orden alfabético.",
  teamAdminTeamManagementOrder: "Orden",
  teamAdminTeamManagementName: "Equipo",
  teamAdminTeamManagementOrganization: "Organización",
  teamAdminTeamMoveUp: "Mover arriba",
  teamAdminTeamMoveDown: "Mover abajo",
  teamAdminTeamNew: "Nuevo equipo",
  teamAdminTeamNewPlaceholder: "p. ej. Cloud Engineering",
  teamAdminTeamAdd: "Añadir equipo",
  teamAdminTeamDelete: "Eliminar equipo",
  teamAdminTeamManagementUpdatedToast: "Gestión de equipos actualizada",
  teamAdminTeamNameRequired: "El nombre del equipo no puede estar vacío.",
  teamAdminTeamNameDuplicate: "Ya existe un equipo con este nombre.",
  teamAdminTeamHasMembers: "No se pueden eliminar equipos con miembros asignados.",
  teamAdminTeamLastTeam: "No se puede eliminar el último equipo.",
  teamAdminTeamRequiredStaffing: "Dotación mínima",
  teamCapacityRequiredStaffing: "Dotación mínima",
  reportsSharedPlanningTitle: "Planificación conjunta entre organizaciones",
  reportsSharedPlanningSubtitle: "Separación/filtro claro por organización y ubicación",
  reportsOrganizationLabel: "Organización",
  reportsOrgFilterAll: "Todas",
  reportsTableEmployee: "Empleado",
  reportsTableLocation: "Ubicación",
  reportsTableTeamsRoles: "Equipos / Roles",
  reportsTeamFilter: "Equipo",
  reportsFilterHint: "Filtrable por organización, ubicación y equipo",
  reportsAnalysisTitle: "Análisis – Subdotaciones críticas",
  reportsAnalysisSubtitle: "Análisis visual y tendencias (más adelante con Power BI)",
  reportsCriticalWeeks: "Semanas críticas",
  reportsCriticalWeeksHint: "Por debajo de la dotación mínima",
  reportsWarnings: "Advertencias",
  reportsWarningsHint: "Por debajo del umbral de advertencia",
  reportsUtilization: "Ocupación",
  reportsUtilizationHint: "Próximos 3 meses",
  reportsChartTitle: "Ocupación a lo largo del tiempo (todos los equipos)",
  reportsLegendUtilization: "Ocupación",
  reportsLegendMinStaffing: "Dotación mínima",
  reportsLegendWarnThreshold: "Umbral de advertencia",
  reportsCriticalWeeksLabel: "Semanas críticas:",
  reportsNoCriticalWeeks: "Sin semanas críticas",
  reportsToPowerBi: "A Power BI",
  reportsCriticalTeams: "equipos críticos",
  reportsCriticalWeekUtilization: "Ocupación",
  reportsMinimumAvailable: "Mínimo disponible",
  reportsAvailableCapacity: "Disponible",
  reportsMyAbsencesTitle: "Mis ausencias y sincronización con Outlook",
  reportsMyAbsencesSubtitle: "Resumen personal y sincronización",
  reportsMyAbsencesHeading: "Mis ausencias 2026",
  reportsMyAbsencesEmpty: "Sin ausencias personales en el período actual.",
  reportsDays: "días",
  reportsStatusRequested: "Solicitado",
  reportsStatusPlanned: "Planificado",
  reportsOutlookSyncTitle: "Sincronización con Outlook",
  reportsOutlookSyncText: "Sus ausencias se sincronizan con Outlook.",
  reportsOutlookLastSync: "Última sincronización: Hoy, 08:45",
  reportsOutlookSyncPending: "Esperando aprobación",
  personCardTabOverview: "Resumen",
  personCardTabContact: "Contacto",
  personCardTabOrganization: "Organización",
  personCardSendQuickMessage: "Enviar un mensaje rápido",
  personCardLastOnline: "Última conexión: Hace 14 minutos · Disponible a las 12:00",
  personCardWorkHours: "Horario laboral: 06:30 - 16:00",
  personCardInOffice: "Presencial previsto",
  personCardSameTimezone: "Misma zona horaria que usted",
  personCardContactInformation: "Información de contacto",
  personCardAssistant: "Asistente",
  personCardEmail: "Correo electrónico",
  personCardChat: "Chat",
  personCardPhoneBusiness: "Teléfono (trabajo)",
  personCardWorkLocation: "Lugar de trabajo",
  personCardCompany: "Empresa",
  personCardMoreContact: "Mostrar más información de contacto",
  personCardDepartment: "Departamento",
  personCardBusinessAddress: "Dirección (trabajo)",
  personCardClose: "Cerrar",
  personCardTeams: "Equipos",
  personCardManager: "Superior jerárquico",
  demoDataSectionTitle: "Datos de demostración",
  demoDataSectionDescription: "Los cambios en los datos simulados (equipos, dotación mínima, ausencias, configuración, saldos de vacaciones, festivos y vacaciones escolares) se guardan localmente en el navegador y sobreviven a un reinicio. Mediante Exportar/Importar puede gestionar especialmente el bloque JSON publicHolidays.",
  demoDataChangesPresent: "Hay cambios locales presentes.",
  demoDataResetButton: "Restablecer datos de demostración",
  demoDataExportButton: "Exportar datos de demostración",
  demoDataImportButton: "Importar datos de demostración",
  demoDataExportFailed: "Error de exportación. Verifique su navegador.",
  demoDataImportFailed: "Error de importación. Verifique el archivo JSON.",
  teamAdminSchoolHolidaySyncTitle: "Actualizar calendario de vacaciones escolares",
  teamAdminSchoolHolidaySyncDescription: "Carga las vacaciones escolares de St. Gallen y Dübendorf/Zúrich desde las fuentes JSON de datos abiertos y las guarda en el calendario simulado local.",
  teamAdminSchoolHolidaySyncYear: "Año calendario",
  teamAdminSchoolHolidaySyncButton: "Obtener vacaciones escolares",
  teamAdminSchoolHolidaySyncRunning: "Cargando vacaciones escolares...",
  teamAdminSchoolHolidaySyncSuccess: "Vacaciones escolares actualizadas para",
  teamAdminSchoolHolidaySyncDays: "días calendario",
  teamAdminSchoolHolidaySyncError: "No se pudieron cargar las vacaciones escolares. Verifique la red/CORS o use la importación JSON.",
  teamAdminSchoolHolidaySyncStGallenNoData: "Nota: St. Gallen no proporcionó entradas para este año.",
  teamAdminSchoolHolidaySyncZurichNoData: "Nota: Zúrich/Dübendorf no proporcionó entradas para este año.",
  teamAdminFederalHolidaySyncButton: "Obtener festivos predeterminados de Zúrich",
  teamAdminFederalHolidaySyncRunning: "Actualizando festivos predeterminados de Zúrich...",
  teamAdminFederalHolidaySyncSuccess: "Festivos predeterminados de Zúrich actualizados para",
  teamAdminFederalHolidaySyncError: "No se pudieron actualizar los festivos predeterminados de Zúrich.",
  teamAdminAbsenceEntryTypesSaveHint: "Los tipos de ausencia nuevos o modificados se aplican automáticamente y aparecen después en el formulario de ausencia.",
  pageAppAdminDescription: "Administración central de la aplicación para proveedores de backend, configuración y diagnóstico.",
  appAdminEffectiveConfigTitle: "Configuración efectiva",
  appAdminEffectiveConfigDescription: "Configuración de la aplicación actualmente activa, incluyendo el origen de cada valor.",
  appAdminFieldDataSource: "Proveedor de datos",
  appAdminFieldMembershipSource: "Fuente de membresía",
  appAdminFieldSharePointSiteUrl: "URL del sitio de SharePoint",
  appAdminFieldApiBaseUrl: "URL base de la API",
  appAdminFieldEnvironment: "Entorno",
  appAdminFieldRelease: "Release",
  appAdminFieldRevision: "Revisión",
  appAdminOriginLocalOverride: "Anulación local",
  appAdminOriginDeployment: "Despliegue",
  appAdminOriginBuild: "Build",
  appAdminOriginDefault: "Predeterminado",
  appAdminOriginStandaloneBrowser: "Standalone browser (mock demo)",
  appAdminFieldStandaloneBrowserUsesMock: "Mock in standalone browser",
  appAdminStandaloneBrowserUsesMockOn: "On (browser ? mock, Teams ? deployment)",
  appAdminStandaloneBrowserUsesMockOff: "Off",
  appAdminProviderMock: "Datos simulados (Demo)",
  appAdminProviderSharePoint: "Listas de SharePoint",
  appAdminProviderApi: "RPP Web API",
  appAdminMembershipMock: "Simulado",
  appAdminMembershipGraph: "Microsoft Graph",
  appAdminProviderConfigTitle: "Proveedor de backend",
  appAdminProviderConfigDescription: "Selección del proveedor como anulación local para este navegador. La configuración de despliegue permanece sin cambios.",
  appAdminAccessDeniedTitle: "No autorizado",
  appAdminAccessDeniedDescription: "El Centro de Administración de la App requiere el rol de Microsoft Entra «Teams Administrator» (o «Global Administrator»). Contacte a su administración de TI.",
  teamAdminAccessDeniedTitle: "No autorizado",
  teamAdminAccessDeniedDescription: "El Centro de Administración de Equipos requiere el rol de propietario (Owner) en el equipo activo de Microsoft Teams.",
  activeTeamChipLabel: "Equipo activo",
  appAdminHolidayResetTitle: "Restablecer calendario de festivos",
  appAdminHolidayResetDescription: "Vacía el calendario central de festivos y vacaciones escolares de este tenant para que se puedan cargar calendarios individuales nuevos (Centro de Administración de Equipos → Acciones de calendario).",
  appAdminHolidayResetButton: "Vaciar calendario de festivos",
  appAdminHolidayResetConfirm: "Confirmar vaciado",
  appAdminHolidayResetSuccess: "El calendario se ha vaciado. Vuelva a cargar los calendarios en el Centro de Administración de Equipos.",
  appAdminHolidayResetError: "No se pudo vaciar el calendario (verifique permisos o conexión).",
  appAdminSharePointSiteUrlHint: "Solo https y *.sharepoint.com.",
  appAdminApiBaseUrlHint: "Solo https (http solo para localhost).",
  appAdminCspHint: "Nota: La Content-Security-Policy del despliegue debe permitir el origen de la API en connect-src.",
  appAdminSaveOverride: "Aplicar localmente",
  appAdminResetOverride: "Restablecer anulación",
  appAdminOverrideActive: "Hay una anulación local activa para este navegador.",
  appAdminReloadPrompt: "La configuración ha cambiado. La aplicación debe recargarse para que surta efecto.",
  appAdminReloadNow: "Recargar ahora",
  appAdminValidationSharePointUrl: "Introduzca una URL de sitio de SharePoint válida (https, *.sharepoint.com).",
  appAdminValidationApiUrl: "Introduzca una URL base de API válida (https, http solo para localhost).",
  appAdminConnectionTestTitle: "Prueba de conexión",
  appAdminConnectionTestDescription: "Verificar la accesibilidad de los proveedores. Los resultados muestran el estado y la latencia.",
  appAdminTestConnection: "Probar conexión",
  appAdminTestRunning: "Prueba en curso…",
  appAdminTestHealthy: "Accesible",
  appAdminTestFailed: "Fallido",
  appAdminExportTitle: "Configuración de despliegue",
  appAdminExportDescription: "Genera un archivo config/runtime-config.js desplegable a partir de la configuración efectiva.",
  appAdminExportButton: "Descargar runtime-config.js",
  appAdminNotConfigured: "No configurado",
  footerText: "Microsoft Teams App Shell • Sprint 1 • Observabilidad EO-010",
  appAdminMailboxSyncTitle: "Outlook Mailbox Sync",
  appAdminMailboxSyncDescription: "Status and manual control of the inbound Outlook sync via the central mailbox. Emails with .ics calendar attachments are automatically imported as absences.",
  appAdminMailboxSyncEnabled: "Status",
  appAdminMailboxSyncEnabledYes: "Enabled",
  appAdminMailboxSyncEnabledNo: "Disabled",
  appAdminMailboxSyncRunning: "Running",
  appAdminMailboxSyncRunningYes: "Yes",
  appAdminMailboxSyncRunningNo: "No",
  appAdminMailboxSyncLastRun: "Last run",
  appAdminMailboxSyncNever: "Never",
  appAdminMailboxSyncProcessed: "Emails processed",
  appAdminMailboxSyncCreated: "Absences created",
  appAdminMailboxSyncUpdated: "Absences updated",
  appAdminMailboxSyncDeleted: "Absences deleted",
  appAdminMailboxSyncErrors: "Errors",
  appAdminMailboxSyncSkipped: "Skipped",
  appAdminMailboxSyncEntries: "Latest entries",
  appAdminMailboxSyncNoData: "No sync data available. Click Refresh status.",
  appAdminMailboxSyncRefresh: "Refresh status",
  appAdminMailboxSyncRefreshing: "Loading…",
  appAdminMailboxSyncTrigger: "Sync now",
  appAdminMailboxSyncTriggering: "Syncing…",
  appAdminMailboxSyncStatusError: "Could not load sync status.",
  appAdminMailboxSyncTriggerError: "Could not start sync.",
  appTitle: "Resources & Presence Planning",
  appSubtitle: "Operations planning for IT resources, presence, and capacity",
  appLogoAlt: "M365 Resources & Presence Planning app logo",
  themeLight: "Light",
  themeDark: "Dark",
  themeToggle: "Toggle appearance",
  headerSearch: "Search",
  headerSearchPlaceholder: "Search (Ctrl+E)",
  moreActions: "More actions",
  help: "Help",
  navOverview: "Overview",
  navTeamCapacity: "Team capacity",
  navMyAbsences: "My absences",
  navApprovals: "Approvals",
  navTeamAdmin: "Team Admin Center",
  navReports: "Reports",
  navSettings: "Settings",
  navInfo: "Info",
  pageOverviewDescription: "Operational planning overview with timeline, resources, teams, and presence events.",
  pageTeamCapacityDescription: "Weekly team capacity with availability, absence share, and risk status.",
  pageMyAbsencesDescription: "Placeholder for personal absences and future request overview.",
  pageApprovalsDescription: "Placeholder for future approvals and decision workflows.",
  pageTeamAdminDescription: "Central administration for team approvers, backups, policies, and vacation visibility.",
  pageReportsDescription: "Placeholder for reporting, analytics, and export views.",
  pageSettingsDescription: "Personal settings for absence requests, approvers, notifications, and Outlook synchronization.",
  pageInfoDescription: "Information about the application, architecture, and design system foundation.",
  timelinePeriodWeek: "Week",
  timelinePeriodMonth: "Month",
  timelineToday: "Today",
  timelineFilter: "Filter",
  timelineFilterLabel: "Filter",
  timelineFilterPlaceholder: "Search team or person",
  detailsClose: "Close",
  absenceCreate: "Save",
  absenceUpdate: "Save changes",
  absenceDelete: "Delete",
  absenceCancel: "Cancel",
  errorRetryAction: "Try again",
  planningBootstrapLoading: "Loading planning data ...",
  mySettingsSaveChanges: "Save changes",
  mySettingsSaveError: "Settings could not be saved",
  teamAdminSaveError: "Team settings could not be saved.",
  teamAdminSaveChanges: "Save changes",
  navAppAdmin: "App Admin Center",
  infoRuntimeCardTitle: "Effective Configuration & Backend Diagnostics",
  infoRuntimeCardDescription: "Live frontend/backend metadata, provider status, and infrastructure targets for quick operational checks.",
  infoRuntimeFrontendTitle: "Frontend (Teams tab)",
  infoRuntimeBackendTitle: "Backend (RPP Web API)",
  infoRuntimeLabelEffectiveProvider: "Active provider mode",
  infoRuntimeLabelEnvironment: "Environment",
  infoRuntimeLabelApiBaseUrl: "API base URL",
  infoRuntimeLabelSharePointSiteUrl: "SharePoint site URL",
  infoRuntimeLabelHealthEndpoint: "Health endpoint",
  infoRuntimeLabelFrontendRelease: "Frontend release",
  infoRuntimeLabelFrontendRevision: "Frontend revision",
  infoRuntimeLabelFrontendBuild: "Frontend build time",
  infoRuntimeLabelBackendStatus: "Backend status",
  infoRuntimeLabelBackendVersion: "Backend version",
  infoRuntimeLabelBackendRevision: "Backend revision",
  infoRuntimeLabelBackendBuild: "Backend build time",
  infoRuntimeLabelBackendEnvironment: "Backend environment",
  infoRuntimeLabelBackendProvider: "Backend provider",
  infoRuntimeLabelBackendDatabaseServer: "Database server",
  infoRuntimeLabelBackendDatabaseName: "Database name",
  infoRuntimeLabelBackendWebServer: "Web server name",
  infoRuntimeLoading: "Loading backend metadata ...",
  infoRuntimeNotAvailable: "Not available",
  appAdminMailboxSyncAddress: "Mailbox email address",
  appAdminMailboxSyncAddressHint: "Email address of the shared mailbox that the sync service polls.",
  appAdminMailboxSyncAddressSave: "Save address",
  appAdminMailboxSyncAddressSaving: "Saving…",
  appAdminMailboxSyncAddressSaved: "Address saved.",
  appAdminMailboxSyncAddressError: "Could not save address.",
  appAdminMailboxSyncAddressValidation: "Please enter a valid email address.",
  navHelp: "Help ?",
  pageHelpDescription: "Ask about RPP in your own words – answered from the RPP help.",
  helpPageTitle: "Help",
  helpPageDescription: "Ask your question in your own words. Answers come exclusively from the RPP help.",
  helpIntroText: "What can we help with? Pick a question or write your own.",
  helpAboutThisPage: "Help with this page",
  helpInputLabel: "Your question",
  helpInputPlaceholder: "For example: how do I record a half-day absence?",
  helpSend: "Send",
  helpThinking: "Looking for an answer ...",
  helpAuthorYou: "You",
  helpAuthorAssistant: "RPP Help",
  helpSourceLabel: "Source",
  helpOpenPage: "Open",
  helpFeedbackQuestion: "Was this helpful?",
  helpFeedbackHelpful: "Helpful",
  helpFeedbackNotHelpful: "Not helpful",
  helpFeedbackThanks: "Thanks for the feedback.",
  helpErrorRequestFailed: "The question could not be answered. Please try again.",
  helpDisclaimer: "The help answers questions about using RPP. It cannot create absences, approve requests or change settings.",
  helpStarterHalfDay: "How do I record a half-day absence?",
  helpStarterApproval: "Why does my vacation request need approval?",
  helpStarterSecondaryTeam: "What does “secondary team” mean?",
  helpStarterOutlook: "How do I synchronize an absence with Outlook?",
  helpStarterPersonMissing: "Why can't I see a person in the planning?",
  helpStarterPresence: "What is the difference between an absence and presence status?",
  helpMockSourceAbsences: "Creating and editing absences",
  helpMockSourceApprovals: "Approvals",
  helpMockSourceCapacity: "Team capacity",
  helpMockSourceOutlookSync: "Outlook synchronization",
  helpMockSourceTimeline: "Planning timeline (Overview)",
  helpMockSourceGlossary: "RPP glossary",
  helpMockSourceReports: "Reports and analyses",
  helpMockSourceTeamsAndRoles: "Teams, organisations and roles",
  helpMockSourceSettings: "Personal settings",
  helpMockAnswerHalfDay: "Set the start and end date to the same day and pick the same day half for both – either “Morning” twice or “Afternoon” twice. That gives 0.5 days. If a multi-day absence should start in the afternoon, set only the start day half to “Afternoon”; if it should end in the morning, set the end day half to “Morning”.",
  helpMockAnswerApprovalRequired: "Whether approval is required follows from three rules set by your team: the team's approval policy, the setting per absence type, and a possible personal exemption. The decision is not made in RPP but in the Microsoft Teams “Approvals” app. You can track your requests under “Approvals”.",
  helpMockAnswerSecondaryTeam: "A secondary team is any team that is not a person's primary team. Depending on where you look, the interface calls it “Secondary teams” or “Additional positions”. Important: a person appears in the timeline only under their primary team, and their capacity counts only there – it is neither split nor counted twice.",
  helpMockAnswerOutlookSync: "For all absences, enable “Synchronize approved vacation with Outlook” in Settings under “Outlook calendar”. For an individual case, use the “Synchronize with Outlook” switch under “Synchronization” in the absence form. If your team dictates the setting, the switch is locked.",
  helpMockAnswerPersonMissing: "Check in order: whether a search term is still active under “Filter”, whether the selected period is too short, whether the person is assigned to your team, whether they are inside a collapsed team group, and whether they are a member of the Microsoft Teams team. A frequent special case: the person is assigned to your team only as a secondary team – they then appear under their primary team.",
  helpMockAnswerPresenceVsAbsence: "An absence means “not here” – Vacation, Compensation, Education, Training, Military, Unpaid leave, Other. It may require approval and reduces available capacity. A presence event means “here, but committed” – Home Office, Project, Maintenance, On Call, Standby. It is not approved and does not reduce capacity.",
  helpMockAnswerWhyRed: "Red means status “Critical” in Team capacity. There are two reasons: either utilization has fallen below the critical threshold, or – more often – the team's required staffing is missed on at least one day of the week. The second case occurs even at good utilization. “Affected employees” shows who is concerned.",
  helpMockAnswerVacationBalance: "Your vacation balance is made up of the annual entitlement, the carry forward from last year and manual adjustments, minus pending and approved vacation. The timeline shows the figures E (entitlement), B (booked) and R (remaining days). The values are always calculated and never stored separately – so correct the absence, not the balance.",
  helpMockAnswerReports: "The “Reports” page analyses the planning across all teams and organisations: a people overview with filters by organisation, location and team, plus critical weeks, warnings and the utilization trend. The calculation is the same as in Team capacity.",
  helpMockAnswerRoles: "The Team Admin Center requires the Owner role in the active Microsoft Teams team; the App Admin Center requires the Microsoft Entra role “Teams Administrator” or “Global Administrator”. Without the role the entry does not appear in the navigation. Roles are granted in Microsoft 365, not in RPP.",
  helpMockAnswerSettings: "In Settings you define who approves your requests, how you are notified, and whether your absences appear in Outlook. Language and time zone are taken from Microsoft 365 – there is deliberately no language switcher.",
  helpMockAnswerUnknown: "I can't find anything about that in the RPP help. Please rephrase the question or contact your team administration.",
  helpOpenLabel: "Open help",
  helpPanelClose: "Close help",
  appAdminMailboxSyncLastError: "Reason for the last failure",
  appAdminMailboxSyncBeta: "Beta",
  appAdminMailboxSyncBetaNote: "Beta feature: verified with Microsoft 365. Other senders and message formats are not fully tested yet — please check imported absences.",
  planningBootstrapNoTeamContextTitle: "No team selected.",
  planningBootstrapNoTeamContextMessage: "The planning view does not know which team to show yet. Open RPP as a tab inside a team, or choose a team.",
  teamContextPickerLoading: "Loading your teams …",
  teamContextPickerPrompt: "Which team would you like to plan?",
  teamContextPickerNoTeams: "You are not a member of any team yet. Ask your team lead to add you to one.",
  teamContextPickerFailed: "Your teams could not be loaded. Please try again.",
  planningBootstrapUnauthenticatedTitle: "Sign-in required.",
  planningBootstrapUnauthenticatedMessage: "RPP could not sign in to Microsoft 365. Accept the Microsoft Teams consent dialog and try again.",
  planningBootstrapForbiddenTitle: "No access to this team.",
  planningBootstrapForbiddenMessage: "Your account is known but has no access to this team's data. Please contact your team lead.",
  runtimeConfigUnavailableTitle: "Application configuration unavailable",
  runtimeConfigUnavailableDescription: "The application cannot show reliable planning data without a valid deployment configuration.",
  teamAdminCalendarSourceUrl: "Calendar URL",
  teamAdminCalendarSourceUrlPlaceholder: "https://.../calendar.json or https://.../calendar.ics",
  teamAdminCalendarSourceType: "Format",
  teamAdminHolidayCalendarsTitle: "Holiday calendars",
  teamAdminHolidayCalendarsDescription: "Configure each holiday calendar separately, including its color and its own fetch action.",
  teamAdminCalendarRefreshButton: "Fetch",
  teamAdminCalendarRefreshError: "The holiday calendar could not be refreshed.",
  helpMockSourceGettingStarted: "Getting started with RPP",
  helpMockSourceTeamAdmin: "Team Admin Center for team owners",
  helpMockAnswerGettingStarted: "RPP runs in Microsoft Teams. Use the top navigation for Overview, Team capacity, Approvals and more. Record absences on Overview; track requests under Approvals; check bottlenecks under Team capacity.",
  helpMockAnswerTeamAdmin: "As an owner, Team Admin Center lets you set approvers, absence types, required staffing, Outlook policy and members (Default team and additional positions). Switch the active team first. You still decide requests in the Teams Approvals app – not in Admin Center.",
  helpMockAnswerTeamAdminRestricted: "Team Admin Center and its how-to are only for team owners (Owner) in the Microsoft Teams team. Ask your team owner or IT if you need rules changed.",
  helpStarterTeamAdmin: "What can I configure in Team Admin Center?",
  helpStarterMinimumStaffing: "What does required staffing do?",
} satisfies Record<keyof typeof de, string>;