import type { de } from "./de";

export const fr = {
  teamsRailLabel: "Navigation Microsoft Teams",
  teamsRailActivity: "Activité",
  teamsRailChat: "Chat",
  teamsRailTeams: "Équipes",
  teamsRailCalendar: "Calendrier",
  teamsRailCalls: "Appels",
  teamsRailFiles: "Fichiers",
  teamsRailResources: "Ressources",
  teamsRailApprovals: "Approbations",
  teamsRailApps: "Applications",
  primaryNavigation: "Navigation principale",
  infoPageDescription: "RPP est la plateforme de planification opérationnelle des ressources IT, présences et capacités – native de Microsoft Teams.",
  infoPageBadge: "Release Candidate 5",
  infoPageTitle: "RPP – Planification des Ressources et Présences",
  infoPageGoToTimeline: "Aller à la chronologie",
  infoPageGoToReports: "Aller aux rapports",
  infoPageStatTeamsLabel: "Organisations et équipes",
  infoPageStatTeamsValue: "Configurable",
  infoPageStatModeLabel: "Mode de données",
  infoPageStatModeMock: "Mock / démo",
  infoPageStatModeApi: "API / production",
  infoPageStatDeploymentLabel: "Déploiement",
  infoPageStatDeploymentValue: "Onglet Teams + API Web + SQL",
  infoCardPeopleTitle: "Personnes et équipes",
  infoCardPeopleDescription: "Chaque personne peut appartenir à plusieurs équipes et occuper plusieurs rôles. La chronologie, la capacité d'équipe et les rapports partagent la même base de membres – cohérente et inter-organisationnelle.",
  infoCardPeopleStatus: "Multi-équipe, multi-rôle",
  infoCardDataTitle: "Données et persistance",
  infoCardDataDescription: "Les équipes, les membres, les soldes de vacances, les jours fériés et les politiques d'approbation sont stockés dans le backend SQL. Microsoft Graph fournit les identités et les photos de profil – l'application reste la source unique de vérité de planification.",
  infoCardDataStatus: "SQL Server + Microsoft Graph",
  infoCardDeliveryTitle: "Livraison",
  infoCardDeliveryDescription: "Le frontend, l'API Web et le package Teams sont versionnés et déployés ensemble. Ce que vous voyez dans le client Teams correspond exactement à la version déployée – sans surprises.",
  infoCardDeliveryStatus: "Versions contrôlées",
  infoCardWhatIsRppTitle: "Qu'est-ce que RPP ?",
  infoCardWhatIsRppDescription: "RPP est l'application Teams centrale pour la planification opérationnelle des ressources, des présences et des capacités. Elle réunit chronologie, vue d'équipe, tableau de capacité, flux d'approbation et administration dans un espace de travail unique et cohérent.",
  infoCardWhatIsRppStatus: "Plateforme de planification opérationnelle",
  infoCardValueTitle: "À quoi sert RPP ?",
  infoCardValueDescription: "RPP crée une transparence opérationnelle entre les organisations. Les responsables d'équipe voient en un coup d'œil qui est disponible, où se forment les goulets d'étranglement et quelles absences sont approuvées – sans e-mails, tableurs ni allers-retours.",
  infoCardValueStatus: "Visibilité et aide à la décision",
  infoCardGetItTitle: "Comment l'obtenir ?",
  infoCardGetItDescription: "RPP est provisionné comme application Teams dans votre tenant. Une fois installée, elle apparaît dans la navigation Teams. Les responsables d'équipe configurent leurs équipes dans le Centre d'Administration des Équipes – sans ticket informatique.",
  infoCardGetItStatus: "Teams App Store (tenant)",
  infoFactsTitle: "En un coup d'œil",
  infoFactsDescription: "Architecture, modules et fonctionnement de la plateforme.",
  infoFactArchitectureLabel: "Architecture",
  infoFactArchitectureValue: "React · Vite · Fluent UI · ASP.NET Core · SQL Server",
  infoFactArchitectureText: "Le frontend s'exécute comme onglet Teams (Vite SPA, Fluent UI v9). L'API Web (ASP.NET Core 8) gère toute la logique métier, la persistance et l'intégration Graph. SQL Server stocke toutes les données de planification.",
  infoFactRolesLabel: "Modules",
  infoFactRolesValue: "Chronologie · Calendrier · Capacité d'équipe · Admin. d'équipe · Admin. de l'app · Rapports · Approbations · Paramètres",
  infoFactRolesText: "Chaque module a un objectif défini : planification, administration, analyse, approbations, configuration et paramètres personnels.",
  infoFactLocalizationLabel: "Localisation",
  infoFactLocalizationValue: "Allemand, anglais + 36 fichiers linguistiques supplémentaires",
  infoFactLocalizationText: "Tout le texte visible est localisable. Les langues principales sont l'allemand et l'anglais ; le système de traduction prend en charge 38 paramètres régionaux.",
  infoFactTeamsLabel: "Multi-organisation",
  infoFactTeamsValue: "Plusieurs organisations · extensible",
  infoFactTeamsText: "Les organisations, les sites et les équipes sont configurables sans modification de code. La plateforme est conçue pour intégrer des organisations supplémentaires.",
  shellOnlyBadge: "EO-009-C",
  timelineAriaLabel: "Base de la chronologie",
  timelineTitle: "Chronologie de planification",
  timelineThreeMonthView: "Vue sur 3 mois",
  timelinePeriodLabel: "Période",
  timelinePeriodNext30Days: "30 jours",
  timelinePeriodNextThreeMonths: "3 prochains mois",
  timelinePeriodNextSixMonths: "6 prochains mois",
  timelinePeriodFullYear: "Année complète",
  timelineGroupByLabel: "Regrouper par",
  timelineGroupByTeams: "Équipes",
  timelineGroupByPeople: "Personnes",
  timelineViewLabel: "Vue",
  timelineViewGantt: "Barres (Gantt)",
  timelineViewList: "Liste",
  timelineViewCalendar: "Calendrier (mois)",
  timelineCalendarPrev: "Mois précédent",
  timelineCalendarNext: "Mois suivant",
  timelineCalendarOverflow: "+{count} de plus",
  timelineLegendSchoolHolidaySg: "Vacances scolaires St-Gall",
  timelineLegendSchoolHolidayDubendorf: "Vacances scolaires Dübendorf",
  timelineLegendPublicHoliday: "Jours fériés",
  timelineAvailablePeople: "Personnes disponibles (total)",
  timelineMinimumStaffing: "Effectif minimum requis",
  timelineCalendarWeekPrefix: "SEM",
  timelineEmployeeColumn: "Collaborateur",
  resourceCompetencies: "Rôles et compétences",
  resourceVacationSummary: "Récapitulatif des vacances : droit, réservé, restant",
  resourceVacationIcon: "🌴",
  resourceVacationEntitlement: "D",
  resourceVacationBooked: "R",
  resourceVacationRemaining: "S",
  resourceVacationEntitlementTooltip: "Droit aux vacances",
  resourceVacationBookedTooltip: "Réservé",
  resourceVacationRemainingTooltip: "Jours restants",
  teamGroupingResourceCount: "ressources",
  teamGroupingResourceCountCompact: "coll.",
  teamGroupingExpand: "Développer le groupe d'équipe",
  teamGroupingCollapse: "Réduire le groupe d'équipe",
  eventTypeVacation: "Vacances",
  eventTypeCompensation: "Compensation",
  eventTypeEducation: "Formation",
  eventTypeHomeOffice: "Télétravail",
  eventTypeTraining: "Perfectionnement",
  eventTypeMilitary: "Service militaire",
  eventTypeUnpaidLeave: "Congé sans solde",
  eventTypeOtherAbsence: "Autre absence",
  eventTypeProject: "Projet",
  eventTypeMaintenance: "Maintenance",
  eventTypeOnCall: "Astreinte",
  eventTypeStandby: "Standby",
  detailsResourceTitle: "Détails de la ressource",
  detailsPresenceTitle: "Détails de l'événement",
  detailsResourceSection: "Ressource",
  detailsPresenceSection: "Événement de présence",
  detailsOrganisation: "Organisation",
  detailsPrimaryTeam: "Équipe principale",
  detailsSecondaryTeams: "Autres équipes",
  detailsVacation: "Vacances",
  detailsEventType: "Type d'événement",
  detailsEventTitle: "Titre",
  detailsStartDate: "Date de début",
  detailsEndDate: "Date de fin",
  detailsDuration: "Durée",
  detailsDays: "jours",
  absenceNew: "Nouvelle absence",
  absencePersistError: "Impossible d'enregistrer l'absence. Veuillez réessayer.",
  approvalSubmitPending: "La demande a été transmise à Microsoft 365 pour approbation. L'approbateur la trouvera dans l'application Teams « Approbations ».",
  approvalSubmitAutoApproved: "L'absence a été enregistrée – aucune approbation n'est requise pour cette personne.",
  approvalSubmitError: "Impossible de soumettre la demande. Veuillez vérifier l'approbateur dans le Centre d'Administration des Équipes et réessayer.",
  myApprovalsTitle: "Mes demandes",
  myApprovalsDescription: "Demandes de vacances avec statut d'approbation Microsoft 365. Les décisions sont prises dans l'application Teams « Approbations ».",
  myApprovalsRefresh: "Actualiser le statut",
  myApprovalsOpenTeams: "Ouvrir Approbations dans Teams",
  myApprovalsEmpty: "Aucune demande pour le moment. Les nouvelles demandes sont créées depuis la chronologie (« Demander l'approbation »).",
  myApprovalsLoadError: "Impossible de charger les demandes. Veuillez réessayer.",
  myApprovalsColPeriod: "Période",
  myApprovalsColModified: "Dernière modification",
  myApprovalsColM365: "M365 Approvals",
  myApprovalsM365Linked: "Linked",
  myApprovalsM365Missing: "No Graph item",
  myApprovalsGraphId: "Graph id",
  myApprovalsWhereToFind: "In the Teams Approvals app: as approver under Received, as requester under Sent. Check the environment filter (tenant). The item only appears for the selected approver account.",
  absenceApproverPolicyManaged: "Géré par la politique d'équipe",
  absenceApproverNone: "Select an approver",
  absenceApproverRequired: "Please select an approver or configure a default approver in the Team Admin Center.",
  orgConfigTitle: "Organisations et sites",
  orgConfigDescription: "Listes configurables pour les organisations partenaires et les sites. Les valeurs des membres sont dérivées du profil Microsoft 365 (entreprise, bureau) et attribuées ici.",
  orgConfigOrganisations: "Organisations",
  orgConfigLocations: "Sites",
  orgConfigOrganisationMappings: "Attribution valeur de profil → organisation",
  orgConfigLocationMappings: "Attribution valeur de profil → site",
  orgConfigUnassigned: "Non attribué",
  orgConfigAdd: "Ajouter",
  orgConfigRemove: "Supprimer",
  orgConfigSave: "Enregistrer les organisations et sites",
  orgConfigSaved: "Enregistré. Les attributions prennent effet immédiatement.",
  orgConfigLoadError: "Impossible de charger la configuration.",
  orgConfigSaveError: "Impossible d'enregistrer la configuration.",
  myApprovalsColOutlook: "Outlook",
  teamCapacityAbsentPersons: "Personnes absentes",
  teamCapacityAbsenceDays: "Absence (jours-personne)",
  teamCapacityAvailableDays: "Disponible (jours-personne)",
  absenceCreateTitle: "Demander une absence",
  absenceEditTitle: "Modifier l'absence",
  absenceRequestApproval: "Demander l'approbation",
  absenceDeleteConfirm: "Confirmer la suppression",
  absenceFieldType: "Type d'absence",
  absenceFieldStartDate: "Date de début",
  absenceFieldStartHalf: "Demi-journée de début",
  absenceFieldEndDate: "Date de fin",
  absenceFieldEndHalf: "Demi-journée de fin",
  absenceFieldSubstitute: "Remplaçant",
  absenceFieldComment: "Commentaire",
  absenceSubstituteNone: "Aucun remplaçant",
  absenceCalculatedWorkdays: "Jours ouvrés",
  absenceSyncTitle: "Synchronisation",
  absenceSyncOutlook: "Synchroniser avec Outlook",
  absenceApprovalStatus: "Statut de la demande",
  absenceApprovalStatusDraft: "Brouillon",
  absenceApprovalStatusPending: "En attente",
  absenceApprovalStatusApproved: "Approuvé",
  absenceApprovalStatusRejected: "Refusé",
  absenceVacationEntitlementTitle: "Droit aux vacances 2026",
  absenceVacationAvailable: "Disponible",
  absenceVacationBooked: "Déjà réservé",
  absenceVacationAfterBooking: "Après cette réservation",
  vacationRequestStatus: "Statut de la demande",
  vacationRequestApprovalSection: "Approbation",
  vacationRequestApprover: "Approbateur",
  vacationRequestCommentToApprover: "Commentaire pour l'approbateur",
  vacationRequestSaveDraft: "Enregistrer le brouillon",
  vacationRequestSubmitForApproval: "Soumettre pour approbation",
  approvalPrototypeTitle: "Flux d'approbation interactif",
  approvalPrototypeBadge: "EO-202-A Flux simulé",
  approvalLiveModeBadge: "Processus d'approbation Microsoft 365",
  approvalPrototypeTimeline: "Progression de l'approbation",
  approvalPrototypeStepPrepare: "Préparer",
  approvalPrototypeStepReview: "Vérifier",
  approvalPrototypeStepSubmitted: "Soumis",
  approvalPrototypeStepTeamLead: "Chef de département",
  approvalPrototypeStepDecision: "Décision",
  approvalPrototypePrepareTitle: "Préparer la demande de vacances",
  approvalPrototypePrepareDescription: "Saisissez les données de la demande comme dans la future interface productive. Tout reste local dans le navigateur.",
  approvalPrototypeReviewTitle: "Vérifier la demande",
  approvalPrototypeReviewDescription: "Contrôlez la période, la durée et l'approbateur avant de soumettre la demande simulée.",
  approvalPrototypeSubmittedTitle: "Demande soumise",
  approvalPrototypeSubmittedDescription: "La demande est dans le flux simulé auprès du chef de département. Aucune approbation réelle n'a été lancée.",
  approvalPrototypeTeamLeadTitle: "Simuler la décision du chef de département",
  approvalPrototypeTeamLeadDescription: "Passez dans la perspective du chef de département et simulez l'approbation ou le refus.",
  approvalPrototypeDecisionTitle: "Flux terminé",
  approvalPrototypeDecisionDescription: "Le flux simulé montre l'état final. Aucune donnée productive n'a été modifiée.",
  approvalPrototypeReviewRequest: "Vérifier la demande",
  approvalPrototypeBackToEdit: "Retour à la modification",
  approvalPrototypeBackToPending: "Retour à soumis",
  approvalPrototypeOpenTeamLead: "Ouvrir la vue chef de département",
  approvalPrototypeCancelRequest: "Annuler la demande",
  approvalPrototypeApprove: "Approuver",
  approvalPrototypeReject: "Refuser",
  approvalPrototypeStartNew: "Démarrer un nouveau flux simulé",
  approvalPrototypeRoutingHint: "L'approbateur provient de la politique d'équipe simulée et pourra être remplacé par l'API productive ultérieurement.",
  approvalPrototypeSubmittedMessage: "La demande attend visiblement la décision du chef de département. Cet état est uniquement temporaire dans l'UI.",
  approvalPrototypeDecisionComment: "Commentaire de décision",
  approvalPrototypeApprovedMessage: "La demande a été approuvée dans le flux simulé.",
  approvalPrototypeRejectedMessage: "La demande a été refusée dans le flux simulé.",
  approvalPrototypeCancelledMessage: "La demande a été annulée dans le flux simulé.",
  approvalPrototypeApprovedPersistedMessage: "Les vacances approuvées ont été enregistrées dans la chronologie simulée.",
  approvalPrototypePersistError: "Impossible d'enregistrer les vacances approuvées dans l'état simulé.",
  approvalPrototypeSummaryTitle: "Récapitulatif de la demande",
  approvalPrototypeSummaryDescription: "État simulé actuel pour démonstration et vérification d'utilisabilité.",
  approvalPrototypeRequester: "Demandeur",
  approvalPrototypeMockOnly: "Simulation uniquement, pas un processus productif",
  approvalStatusDraft: "Brouillon",
  approvalStatusSubmitted: "Soumis",
  approvalStatusPendingApproval: "En attente d'approbation",
  approvalStatusApproved: "Approuvé",
  approvalStatusRejected: "Refusé",
  approvalStatusCancelled: "Annulé",
  approvalStatusFailed: "Échoué",
  absenceCalculatedRemainingVacation: "Vacances restantes après réservation",
  absenceValidationRequired: "Veuillez remplir tous les champs obligatoires.",
  absenceValidationEndBeforeStart: "La date de fin ne peut pas être antérieure à la date de début.",
  absenceValidationDuration: "La combinaison de demi-journées sélectionnée ne produit pas une durée valide.",
  absenceValidationOutsideTimeline: "La modification se situe en dehors de la période visible.",
  absenceValidationMoveDuration: "Le déplacement ne doit pas modifier la durée de l'absence.",
  absenceTypeVacation: "Vacances",
  absenceTypeCompensation: "Compensation",
  absenceTypeEducation: "Formation",
  absenceTypeTraining: "Perfectionnement",
  absenceTypeMilitary: "Service militaire",
  absenceTypeUnpaidLeave: "Congé sans solde",
  absenceTypeOther: "Autre",
  dayHalfMorning: "Matin",
  dayHalfAfternoon: "Après-midi",
  dayHalfFullDay: "Journée entière",
  capacityAvailable: "Capacité disponible",
  teamCapacityDashboardTitle: "Capacité d'équipe",
  teamCapacityDashboardDescription: "Aperçu hebdomadaire agrégé basé sur le moteur central de capacité.",
  teamCapacityTeamLabel: "Équipe",
  teamCapacityAvailable: "Disponible",
  teamCapacityAbsent: "Absent",
  teamCapacityUtilization: "Occupation",
  teamCapacityMembers: "Membres de l'équipe",
  teamCapacityNominal: "Nominal",
  teamCapacityCriticalWeeks: "Semaines critiques",
  teamCapacityCriticalWeeksShort: "Sem. critiques",
  teamCapacityWeeklyOverview: "Aperçu hebdomadaire",
  teamCapacityStatus: "Statut",
  teamCapacityMetric: "Indicateur",
  teamCapacityAffectedResources: "Collaborateurs concernés",
  teamCapacityNoAffectedResources: "Aucun collaborateur concerné cette semaine.",
  teamCapacityStatusOk: "OK",
  teamCapacityStatusWarning: "Avertissement",
  teamCapacityStatusCritical: "Critique",
  designSystemSectionTitle: "Fondamentaux du système de design",
  designSystemSectionDescription: "Motifs visuels réutilisables pour les prochains ordres d'ingénierie.",
  designCardLayoutTitle: "Mise en page",
  designCardLayoutDescription: "Shell, en-tête, zone de contenu et espacement responsive suivent une grille uniforme.",
  designCardThemeTitle: "Thème",
  designCardThemeDescription: "Modes clair et sombre basés sur les tokens Fluent UI, extensibles.",
  designCardTypographyTitle: "Typographie",
  designCardTypographyDescription: "Titres, sections et textes d'aide utilisent des tailles et graisses cohérentes.",
  statusReady: "Prêt",
  statusFoundation: "Fondation",
  statusReserved: "Réservé",
  placeholderSurfaceTitle: "Shell d'application",
  placeholderSurfaceText: "Cette page est intentionnellement un espace réservé. La fonctionnalité métier suivra dans les prochains ordres d'ingénierie.",
  errorBoundaryTitle: "Quelque chose s'est mal passé.",
  errorBoundaryMessage: "Impossible de charger la vue. Veuillez réessayer ou signaler la référence au support.",
  errorReferenceLabel: "Référence",
  planningBootstrapEmptyTitle: "Aucune personne planifiable trouvée.",
  planningBootstrapEmptyMessage: "La vue de planification nécessite des membres d'équipe avant de pouvoir afficher la capacité et les absences.",
  mySettingsTitle: "Mes paramètres",
  mySettingsLoading: "Chargement des paramètres...",
  mySettingsProfileTitle: "Profil",
  mySettingsName: "Nom",
  mySettingsEmail: "Adresse e-mail",
  mySettingsTeam: "Équipe",
  mySettingsApprovalTitle: "Approbation",
  mySettingsApprovalDescription: "Approbateur par défaut et suppléant pour les demandes de vacances.",
  mySettingsDefaultApprover: "Approbateur par défaut",
  mySettingsFallbackApprover: "Approbateur suppléant",
  mySettingsApproverSource: "Source",
  mySettingsApproverSourceUser: "Paramètre personnel",
  mySettingsApproverSourceTeamPolicy: "Politique d'équipe",
  mySettingsApproverSourceTeamLead: "Chef de département",
  mySettingsApproverSourceFallback: "Suppléant",
  mySettingsNoApproverWarning: "Aucun approbateur configuré. Veuillez contacter l'administrateur de l'équipe.",
  mySettingsNotificationsTitle: "Notifications",
  mySettingsNotificationsDescription: "Comment vous serez informé des changements d'état de vos demandes.",
  mySettingsNotificationInApp: "Notification dans l'application",
  mySettingsNotificationEmail: "Notification par e-mail",
  mySettingsNotificationTeams: "Notification Teams",
  mySettingsOutlookTitle: "Calendrier Outlook",
  mySettingsOutlookDescription: "Comportement par défaut pour les absences approuvées.",
  mySettingsOutlookSync: "Synchroniser les vacances approuvées avec Outlook",
  mySettingsOutlookEnabled: "Activé",
  mySettingsOutlookDisabled: "Désactivé",
  mySettingsOutlookManaged: "Géré par la politique d'équipe",
  mySettingsRegionalTitle: "Régional",
  mySettingsRegionalDescription: "La langue et le fuseau horaire sont repris de Microsoft 365 ou du navigateur.",
  mySettingsLanguage: "Langue",
  mySettingsTimeZone: "Fuseau horaire",
  mySettingsManagedByTeamPolicy: "Géré par la politique d'équipe",
  mySettingsNotConfigured: "Non configuré",
  mySettingsResetToDefaults: "Rétablir les valeurs par défaut",
  mySettingsSavedToast: "Paramètres enregistrés",
  mySettingsResetToast: "Paramètres rétablis",
  outlookSyncStatusNotRequired: "Aucune synchronisation Outlook",
  outlookSyncStatusPending: "Synchronisation en cours",
  outlookSyncStatusSynced: "Calendrier Outlook mis à jour",
  outlookSyncStatusFailed: "Synchronisation Outlook échouée",
  outlookSyncRetry: "Réessayer la synchronisation",
  vacationBalanceTitle: "Solde de vacances",
  vacationBalanceAnnualEntitlement: "Droit annuel",
  vacationBalanceCarryForward: "Report",
  vacationBalanceManualAdjustments: "Ajustements manuels",
  vacationBalancePendingVacation: "Vacances demandées",
  vacationBalanceApprovedVacation: "Vacances approuvées",
  vacationBalanceRemainingBalance: "Solde restant",
  vacationBalancePreviewTitle: "Aperçu du solde",
  vacationBalanceCurrentBalance: "Solde actuel",
  vacationBalanceRequestedVacation: "Jours de vacances demandés",
  vacationBalanceRemainingAfterSubmission: "Solde après soumission",
  vacationBalanceExceedsWarning: "La demande dépasse le solde de vacances disponible. La soumission ne sera pas bloquée dans le Sprint 3.",
  vacationBalanceAdjustmentTitle: "Ajuster le solde",
  vacationBalanceAdjustmentValue: "Ajustement",
  vacationBalanceAdjustmentReason: "Motif",
  vacationBalanceSaveAdjustment: "Enregistrer l'ajustement",
  vacationBalanceHistoryTitle: "Historique des ajustements",
  vacationBalanceHistoryPrevious: "Précédent",
  vacationBalanceHistoryNew: "Nouveau",
  vacationBalanceHistoryEmpty: "Aucun ajustement manuel pour le moment.",
  vacationBalancePreviewControlsTitle: "Vérifier la demande de vacances",
  teamAdminTitle: "Centre d'Administration des Équipes",
  teamAdminLoading: "Chargement du Centre d'Administration des Équipes...",
  teamAdminLoadError: "Impossible de charger le Centre d'Administration des Équipes.",
  teamAdminSavedToast: "Paramètres de l'équipe enregistrés",
  teamAdminAutoSaveEnabled: "Sauvegarde automatique activée",
  teamAdminAutoSaveSaving: "Enregistrement des modifications...",
  teamAdminNoManagedTeams: "Aucune équipe gérable trouvée.",
  teamAdminTeamSelection: "Sélection d'équipe",
  teamAdminTeamSelectionDescription: "Équipes pour lesquelles vous êtes autorisé en tant que chef de département ou administrateur délégué.",
  teamAdminActiveTeam: "Équipe active",
  teamAdminManagedTeam: "Équipe gérée",
  teamAdminAllTeams: "Toutes les équipes",
  teamAdminAllTeamsDescription: "Aperçu alphabétique de tous les membres pour la maintenance des données de démonstration.",
  teamAdminTeamInformation: "Informations sur l'équipe",
  teamAdminTeamLead: "Chef de département",
  teamAdminMemberCount: "Membres",
  teamAdminDefaultApprover: "Approbateur par défaut",
  teamAdminBackupApprover: "Approbateur suppléant",
  teamAdminNoBackupApprover: "Aucun approbateur suppléant",
  teamAdminDisplaySettings: "Affichage",
  teamAdminDisplaySettingsDescription: "Options d'affichage pour la chronologie de planification. S'appliquent à l'ensemble de l'installation.",
  teamAdminShowVacationSummary: "Afficher les chiffres des vacances dans la chronologie",
  teamAdminEventColorMode: "Couleurs des événements",
  teamAdminEventColorByType: "Par type d'absence",
  teamAdminEventColorByTeam: "Par équipe",
  teamAdminTeamColor: "Couleur",
  teamAdminTeamColorAuto: "Automatique",
  teamColorBlue: "Bleu",
  teamColorGreen: "Vert",
  teamColorMarigold: "Jaune",
  teamColorBerry: "Baie",
  teamColorTeal: "Turquoise",
  teamColorPumpkin: "Orange",
  teamColorLavender: "Violet",
  teamColorSeafoam: "Menthe",
  teamColorCranberry: "Rouge",
  teamColorPlatinum: "Gris",
  teamAdminApprovalPolicy: "Politique d'approbation",
  teamAdminApprovalPolicyDescription: "Cette politique influence les nouvelles demandes de vacances et les paramètres personnels des membres de l'équipe.",
  teamAdminAllowUserOverride: "Les utilisateurs peuvent choisir un autre approbateur",
  teamAdminOutlookSyncPolicy: "Synchronisation Outlook",
  teamAdminOutlookSyncOptional: "Optionnel",
  teamAdminOutlookSyncMandatory: "Obligatoire",
  teamAdminOutlookSyncDisabled: "Désactivé",
  teamAdminAbsenceEntryTypes: "Types d'absence",
  teamAdminAbsenceEntryTypesDescription: "Gérer centralement les types d'absence, l'obligation d'approbation et la consommation du solde de vacances.",
  teamAdminEntryTypeName: "Type",
  teamAdminEntryTypeActive: "Actif",
  teamAdminEntryTypeRequiresApproval: "Approbation",
  teamAdminEntryTypeConsumesVacation: "Solde de vacances",
  teamAdminEntryTypeActions: "Action",
  teamAdminEntryTypeNew: "Nouveau type d'absence",
  teamAdminEntryTypeNewPlaceholder: "ex. Conférence",
  teamAdminEntryTypeAdd: "Ajouter",
  teamAdminEntryTypeDelete: "Supprimer le type d'absence",
  teamAdminTeamMembers: "Membres de l'équipe",
  teamAdminTeamMembersDescription: "Attribution de l'équipe par défaut, postes supplémentaires, taux d'emploi, solde de vacances, exemption d'approbation et approbateur effectif.",
  teamAdminMemberAdd: "Ajouter un membre",
  teamAdminMemberAddPlaceholder: "Sélectionner une personne de l'espace Teams",
  teamAdminMemberAddButton: "Ajouter",
  teamAdminMemberName: "Nom",
  teamAdminMemberEmail: "E-mail",
  teamAdminMemberPosition: "Poste",
  teamAdminMemberActions: "Actions",
  teamAdminMemberRemove: "Remove",
  teamAdminMemberRemoveConfirm: "Remove \"{name}\" from RPP planning? The person may remain in the M365 team; absence history is kept.",
  teamAdminMemberRemoveHint: "Removes the person from all RPP teams on this host (after save).",
  teamAdminMemberRemoveError: "The person could not be removed from RPP planning. Try again or reload the page.",
  teamAdminMemberRemoveEmpty: "No RPP assignment was found for this person (already removed).",
  teamAdminPrimaryTeam: "Équipe par défaut",
  teamAdminAdditionalPositions: "Postes supplémentaires",
  teamAdminEmploymentPercentage: "Taux d'emploi",
  teamAdminVacationBalance: "Solde de vacances",
  teamAdminActiveVacationRequests: "Demandes actives",
  teamAdminApprovalExempt: "Aucune approbation requise",
  teamAdminNoApprovalRequired: "Aucune approbation requise",
  teamAdminEffectiveApprover: "Approbateur effectif",
  teamAdminNotAvailable: "Non disponible",
  teamAdminTeamManagement: "Gestion des équipes",
  teamAdminTeamManagementDescription: "Créer, renommer et supprimer des équipes, et définir l'ordre d'affichage indépendamment de l'ordre alphabétique.",
  teamAdminTeamManagementOrder: "Ordre",
  teamAdminTeamManagementName: "Équipe",
  teamAdminTeamManagementOrganization: "Organisation",
  teamAdminTeamMoveUp: "Déplacer vers le haut",
  teamAdminTeamMoveDown: "Déplacer vers le bas",
  teamAdminTeamNew: "Nouvelle équipe",
  teamAdminTeamNewPlaceholder: "ex. Cloud Engineering",
  teamAdminTeamAdd: "Ajouter une équipe",
  teamAdminTeamDelete: "Supprimer l'équipe",
  teamAdminTeamManagementUpdatedToast: "Gestion des équipes mise à jour",
  teamAdminTeamNameRequired: "Le nom de l'équipe ne peut pas être vide.",
  teamAdminTeamNameDuplicate: "Une équipe portant ce nom existe déjà.",
  teamAdminTeamHasMembers: "Les équipes avec des membres attribués ne peuvent pas être supprimées.",
  teamAdminTeamLastTeam: "La dernière équipe ne peut pas être supprimée.",
  teamAdminTeamRequiredStaffing: "Effectif minimum",
  teamCapacityRequiredStaffing: "Effectif minimum",
  reportsSharedPlanningTitle: "Planification partagée entre organisations",
  reportsSharedPlanningSubtitle: "Séparation/filtre clair par organisation et site",
  reportsOrganizationLabel: "Organisation",
  reportsOrgFilterAll: "Toutes",
  reportsTableEmployee: "Collaborateur",
  reportsTableLocation: "Site",
  reportsTableTeamsRoles: "Équipes / Rôles",
  reportsTeamFilter: "Équipe",
  reportsFilterHint: "Filtrable par organisation, site et équipe",
  reportsAnalysisTitle: "Analyse – Sous-effectifs critiques",
  reportsAnalysisSubtitle: "Analyse visuelle et tendances (ultérieurement avec Power BI)",
  reportsCriticalWeeks: "Semaines critiques",
  reportsCriticalWeeksHint: "En dessous de l'effectif minimum",
  reportsWarnings: "Avertissements",
  reportsWarningsHint: "En dessous du seuil d'avertissement",
  reportsUtilization: "Occupation",
  reportsUtilizationHint: "3 prochains mois",
  reportsChartTitle: "Occupation dans le temps (toutes les équipes)",
  reportsLegendUtilization: "Occupation",
  reportsLegendMinStaffing: "Effectif minimum",
  reportsLegendWarnThreshold: "Seuil d'avertissement",
  reportsCriticalWeeksLabel: "Semaines critiques :",
  reportsNoCriticalWeeks: "Aucune semaine critique",
  reportsToPowerBi: "Vers Power BI",
  reportsCriticalTeams: "équipes critiques",
  reportsCriticalWeekUtilization: "Occupation",
  reportsMinimumAvailable: "Minimum disponible",
  reportsAvailableCapacity: "Disponible",
  reportsMyAbsencesTitle: "Mes absences et synchronisation Outlook",
  reportsMyAbsencesSubtitle: "Aperçu personnel et synchronisation",
  reportsMyAbsencesHeading: "Mes absences 2026",
  reportsMyAbsencesEmpty: "Aucune absence personnelle dans la période actuelle.",
  reportsDays: "jours",
  reportsStatusRequested: "Demandé",
  reportsStatusPlanned: "Planifié",
  reportsOutlookSyncTitle: "Synchronisation Outlook",
  reportsOutlookSyncText: "Vos absences sont synchronisées avec Outlook.",
  reportsOutlookLastSync: "Dernière synchronisation : Aujourd'hui, 08:45",
  reportsOutlookSyncPending: "En attente d'approbation",
  personCardTabOverview: "Aperçu",
  personCardTabContact: "Contact",
  personCardTabOrganization: "Organisation",
  personCardSendQuickMessage: "Envoyer un message rapide",
  personCardLastOnline: "Dernière connexion : Il y a 14 minutes · Disponible à 12:00",
  personCardWorkHours: "Heures de travail : 06:30 - 16:00",
  personCardInOffice: "Présentiel prévu",
  personCardSameTimezone: "Même fuseau horaire que vous",
  personCardContactInformation: "Coordonnées",
  personCardAssistant: "Assistant",
  personCardEmail: "E-mail",
  personCardChat: "Chat",
  personCardPhoneBusiness: "Téléphone (professionnel)",
  personCardWorkLocation: "Lieu de travail",
  personCardCompany: "Entreprise",
  personCardMoreContact: "Afficher plus de coordonnées",
  personCardDepartment: "Département",
  personCardBusinessAddress: "Adresse (professionnelle)",
  personCardClose: "Fermer",
  personCardTeams: "Équipes",
  personCardManager: "Supérieur hiérarchique",
  demoDataSectionTitle: "Données de démonstration",
  demoDataSectionDescription: "Les modifications des données simulées (équipes, effectif minimum, absences, paramètres, soldes de vacances, jours fériés et vacances scolaires) sont enregistrées localement dans le navigateur et survivent à un redémarrage. Via Exporter/Importer, vous pouvez notamment gérer le bloc JSON publicHolidays.",
  demoDataChangesPresent: "Des modifications locales sont présentes.",
  demoDataResetButton: "Réinitialiser les données de démonstration",
  demoDataExportButton: "Exporter les données de démonstration",
  demoDataImportButton: "Importer les données de démonstration",
  demoDataExportFailed: "Échec de l'exportation. Veuillez vérifier votre navigateur.",
  demoDataImportFailed: "Échec de l'importation. Veuillez vérifier le fichier JSON.",
  teamAdminSchoolHolidaySyncTitle: "Mettre à jour le calendrier des vacances scolaires",
  teamAdminSchoolHolidaySyncDescription: "Charge les vacances scolaires de St-Gall et Dübendorf/Zurich depuis les sources JSON Open Data et les enregistre dans le calendrier simulé local.",
  teamAdminSchoolHolidaySyncYear: "Année civile",
  teamAdminSchoolHolidaySyncButton: "Récupérer les vacances scolaires",
  teamAdminSchoolHolidaySyncRunning: "Chargement des vacances scolaires...",
  teamAdminSchoolHolidaySyncSuccess: "Vacances scolaires mises à jour pour",
  teamAdminSchoolHolidaySyncDays: "jours calendaires",
  teamAdminSchoolHolidaySyncError: "Impossible de charger les vacances scolaires. Veuillez vérifier le réseau/CORS ou utiliser l'importation JSON.",
  teamAdminSchoolHolidaySyncStGallenNoData: "Note : St-Gall n'a pas fourni d'entrées pour cette année.",
  teamAdminSchoolHolidaySyncZurichNoData: "Note : Zurich/Dübendorf n'a pas fourni d'entrées pour cette année.",
  teamAdminFederalHolidaySyncButton: "Récupérer les jours fériés par défaut de Zurich",
  teamAdminFederalHolidaySyncRunning: "Mise à jour des jours fériés par défaut de Zurich...",
  teamAdminFederalHolidaySyncSuccess: "Jours fériés par défaut de Zurich mis à jour pour",
  teamAdminFederalHolidaySyncError: "Impossible de mettre à jour les jours fériés par défaut de Zurich.",
  teamAdminAbsenceEntryTypesSaveHint: "Les types d'absence nouveaux ou modifiés sont appliqués automatiquement et apparaissent ensuite dans le formulaire d'absence.",
  pageAppAdminDescription: "Administration centrale de l'application pour les fournisseurs backend, la configuration et le diagnostic.",
  appAdminEffectiveConfigTitle: "Configuration effective",
  appAdminEffectiveConfigDescription: "Configuration applicative actuellement active, y compris l'origine de chaque valeur.",
  appAdminFieldDataSource: "Fournisseur de données",
  appAdminFieldMembershipSource: "Source d'appartenance",
  appAdminFieldSharePointSiteUrl: "URL du site SharePoint",
  appAdminFieldApiBaseUrl: "URL de base de l'API",
  appAdminFieldEnvironment: "Environnement",
  appAdminFieldRelease: "Release",
  appAdminFieldRevision: "Révision",
  appAdminOriginLocalOverride: "Surcharge locale",
  appAdminOriginDeployment: "Déploiement",
  appAdminOriginBuild: "Build",
  appAdminOriginDefault: "Par défaut",
  appAdminOriginStandaloneBrowser: "Standalone browser (mock demo)",
  appAdminFieldStandaloneBrowserUsesMock: "Mock in standalone browser",
  appAdminStandaloneBrowserUsesMockOn: "On (browser ? mock, Teams ? deployment)",
  appAdminStandaloneBrowserUsesMockOff: "Off",
  appAdminProviderMock: "Données simulées (Démo)",
  appAdminProviderSharePoint: "Listes SharePoint",
  appAdminProviderApi: "RPP Web API",
  appAdminMembershipMock: "Simulé",
  appAdminMembershipGraph: "Microsoft Graph",
  appAdminProviderConfigTitle: "Fournisseur backend",
  appAdminProviderConfigDescription: "Sélection du fournisseur comme surcharge locale pour ce navigateur. La configuration de déploiement reste inchangée.",
  appAdminAccessDeniedTitle: "Non autorisé",
  appAdminAccessDeniedDescription: "Le Centre d'Administration de l'App nécessite le rôle Microsoft Entra « Teams Administrator » (ou « Global Administrator »). Veuillez contacter votre administration IT.",
  teamAdminAccessDeniedTitle: "Non autorisé",
  teamAdminAccessDeniedDescription: "Le Centre d'Administration des Équipes nécessite le rôle de propriétaire (Owner) dans l'équipe Microsoft Teams active.",
  activeTeamChipLabel: "Équipe active",
  appAdminHolidayResetTitle: "Réinitialiser le calendrier des jours fériés",
  appAdminHolidayResetDescription: "Vide le calendrier central des jours fériés et vacances scolaires de ce tenant pour permettre le chargement de calendriers individuels frais (Centre d'Administration des Équipes → Actions de calendrier).",
  appAdminHolidayResetButton: "Vider le calendrier des jours fériés",
  appAdminHolidayResetConfirm: "Confirmer le vidage",
  appAdminHolidayResetSuccess: "Le calendrier a été vidé. Rechargez les calendriers dans le Centre d'Administration des Équipes.",
  appAdminHolidayResetError: "Impossible de vider le calendrier (vérifiez les permissions ou la connexion).",
  appAdminSharePointSiteUrlHint: "Uniquement https et *.sharepoint.com.",
  appAdminApiBaseUrlHint: "Uniquement https (http uniquement pour localhost).",
  appAdminCspHint: "Note : La Content-Security-Policy du déploiement doit autoriser l'origine de l'API dans connect-src.",
  appAdminSaveOverride: "Appliquer localement",
  appAdminResetOverride: "Réinitialiser la surcharge",
  appAdminOverrideActive: "Une surcharge locale est active pour ce navigateur.",
  appAdminReloadPrompt: "La configuration a été modifiée. L'application doit être rechargée pour prendre effet.",
  appAdminReloadNow: "Recharger maintenant",
  appAdminValidationSharePointUrl: "Veuillez saisir une URL de site SharePoint valide (https, *.sharepoint.com).",
  appAdminValidationApiUrl: "Veuillez saisir une URL de base d'API valide (https, http uniquement pour localhost).",
  appAdminConnectionTestTitle: "Test de connexion",
  appAdminConnectionTestDescription: "Vérifier l'accessibilité des fournisseurs. Les résultats montrent l'état et la latence.",
  appAdminTestConnection: "Tester la connexion",
  appAdminTestRunning: "Test en cours…",
  appAdminTestHealthy: "Accessible",
  appAdminTestFailed: "Échoué",
  appAdminExportTitle: "Configuration de déploiement",
  appAdminExportDescription: "Génère un fichier config/runtime-config.js déployable à partir de la configuration effective.",
  appAdminExportButton: "Télécharger runtime-config.js",
  appAdminNotConfigured: "Non configuré",
  footerText: "Microsoft Teams App Shell • Sprint 1 • Observabilité EO-010",
  appAdminMailboxSyncTitle: "Outlook Mailbox Sync",
  appAdminMailboxSyncDescription: "Status and manual control of the inbound Outlook sync via the central mailbox. Emails with .ics calendar attachments are automatically imported as absences.",
  appAdminMailboxSyncEnabled: "Status",
  appAdminMailboxSyncEnabledYes: "Enabled",
  appAdminMailboxSyncEnabledNo: "Disabled",
  appAdminMailboxSyncRunning: "Running",
  appAdminMailboxSyncRunningYes: "Yes",
  appAdminMailboxSyncRunningNo: "No",
  appAdminMailboxSyncLastRun: "Last run",
  appAdminMailboxSyncNever: "Never",
  appAdminMailboxSyncProcessed: "Emails processed",
  appAdminMailboxSyncCreated: "Absences created",
  appAdminMailboxSyncUpdated: "Absences updated",
  appAdminMailboxSyncDeleted: "Absences deleted",
  appAdminMailboxSyncErrors: "Errors",
  appAdminMailboxSyncSkipped: "Skipped",
  appAdminMailboxSyncEntries: "Latest entries",
  appAdminMailboxSyncNoData: "No sync data available. Click Refresh status.",
  appAdminMailboxSyncRefresh: "Refresh status",
  appAdminMailboxSyncRefreshing: "Loading…",
  appAdminMailboxSyncTrigger: "Sync now",
  appAdminMailboxSyncTriggering: "Syncing…",
  appAdminMailboxSyncStatusError: "Could not load sync status.",
  appAdminMailboxSyncTriggerError: "Could not start sync.",
  appTitle: "Resources & Presence Planning",
  appSubtitle: "Operations planning for IT resources, presence, and capacity",
  appLogoAlt: "M365 Resources & Presence Planning app logo",
  themeLight: "Light",
  themeDark: "Dark",
  themeToggle: "Toggle appearance",
  headerSearch: "Search",
  headerSearchPlaceholder: "Search (Ctrl+E)",
  moreActions: "More actions",
  help: "Help",
  navOverview: "Overview",
  navTeamCapacity: "Team capacity",
  navMyAbsences: "My absences",
  navApprovals: "Approvals",
  navTeamAdmin: "Team Admin Center",
  navReports: "Reports",
  navSettings: "Settings",
  navInfo: "Info",
  pageOverviewDescription: "Operational planning overview with timeline, resources, teams, and presence events.",
  pageTeamCapacityDescription: "Weekly team capacity with availability, absence share, and risk status.",
  pageMyAbsencesDescription: "Placeholder for personal absences and future request overview.",
  pageApprovalsDescription: "Placeholder for future approvals and decision workflows.",
  pageTeamAdminDescription: "Central administration for team approvers, backups, policies, and vacation visibility.",
  pageReportsDescription: "Placeholder for reporting, analytics, and export views.",
  pageSettingsDescription: "Personal settings for absence requests, approvers, notifications, and Outlook synchronization.",
  pageInfoDescription: "Information about the application, architecture, and design system foundation.",
  timelinePeriodWeek: "Week",
  timelinePeriodMonth: "Month",
  timelineToday: "Today",
  timelineFilter: "Filter",
  timelineFilterLabel: "Filter",
  timelineFilterPlaceholder: "Search team or person",
  detailsClose: "Close",
  absenceCreate: "Save",
  absenceUpdate: "Save changes",
  absenceDelete: "Delete",
  absenceCancel: "Cancel",
  errorRetryAction: "Try again",
  planningBootstrapLoading: "Loading planning data ...",
  mySettingsSaveChanges: "Save changes",
  mySettingsSaveError: "Settings could not be saved",
  teamAdminSaveError: "Team settings could not be saved.",
  teamAdminSaveChanges: "Save changes",
  navAppAdmin: "App Admin Center",
  infoRuntimeCardTitle: "Effective Configuration & Backend Diagnostics",
  infoRuntimeCardDescription: "Live frontend/backend metadata, provider status, and infrastructure targets for quick operational checks.",
  infoRuntimeFrontendTitle: "Frontend (Teams tab)",
  infoRuntimeBackendTitle: "Backend (RPP Web API)",
  infoRuntimeLabelEffectiveProvider: "Active provider mode",
  infoRuntimeLabelEnvironment: "Environment",
  infoRuntimeLabelApiBaseUrl: "API base URL",
  infoRuntimeLabelSharePointSiteUrl: "SharePoint site URL",
  infoRuntimeLabelHealthEndpoint: "Health endpoint",
  infoRuntimeLabelFrontendRelease: "Frontend release",
  infoRuntimeLabelFrontendRevision: "Frontend revision",
  infoRuntimeLabelFrontendBuild: "Frontend build time",
  infoRuntimeLabelBackendStatus: "Backend status",
  infoRuntimeLabelBackendVersion: "Backend version",
  infoRuntimeLabelBackendRevision: "Backend revision",
  infoRuntimeLabelBackendBuild: "Backend build time",
  infoRuntimeLabelBackendEnvironment: "Backend environment",
  infoRuntimeLabelBackendProvider: "Backend provider",
  infoRuntimeLabelBackendDatabaseServer: "Database server",
  infoRuntimeLabelBackendDatabaseName: "Database name",
  infoRuntimeLabelBackendWebServer: "Web server name",
  infoRuntimeLoading: "Loading backend metadata ...",
  infoRuntimeNotAvailable: "Not available",
  appAdminMailboxSyncAddress: "Mailbox email address",
  appAdminMailboxSyncAddressHint: "Email address of the shared mailbox that the sync service polls.",
  appAdminMailboxSyncAddressSave: "Save address",
  appAdminMailboxSyncAddressSaving: "Saving…",
  appAdminMailboxSyncAddressSaved: "Address saved.",
  appAdminMailboxSyncAddressError: "Could not save address.",
  appAdminMailboxSyncAddressValidation: "Please enter a valid email address.",
  navHelp: "Help ?",
  pageHelpDescription: "Ask about RPP in your own words – answered from the RPP help.",
  helpPageTitle: "Help",
  helpPageDescription: "Ask your question in your own words. Answers come exclusively from the RPP help.",
  helpIntroText: "What can we help with? Pick a question or write your own.",
  helpAboutThisPage: "Help with this page",
  helpInputLabel: "Your question",
  helpInputPlaceholder: "For example: how do I record a half-day absence?",
  helpSend: "Send",
  helpThinking: "Looking for an answer ...",
  helpAuthorYou: "You",
  helpAuthorAssistant: "RPP Help",
  helpSourceLabel: "Source",
  helpOpenPage: "Open",
  helpFeedbackQuestion: "Was this helpful?",
  helpFeedbackHelpful: "Helpful",
  helpFeedbackNotHelpful: "Not helpful",
  helpFeedbackThanks: "Thanks for the feedback.",
  helpErrorRequestFailed: "The question could not be answered. Please try again.",
  helpDisclaimer: "The help answers questions about using RPP. It cannot create absences, approve requests or change settings.",
  helpStarterHalfDay: "How do I record a half-day absence?",
  helpStarterApproval: "Why does my vacation request need approval?",
  helpStarterSecondaryTeam: "What does “secondary team” mean?",
  helpStarterOutlook: "How do I synchronize an absence with Outlook?",
  helpStarterPersonMissing: "Why can't I see a person in the planning?",
  helpStarterPresence: "What is the difference between an absence and presence status?",
  helpMockSourceAbsences: "Creating and editing absences",
  helpMockSourceApprovals: "Approvals",
  helpMockSourceCapacity: "Team capacity",
  helpMockSourceOutlookSync: "Outlook synchronization",
  helpMockSourceTimeline: "Planning timeline (Overview)",
  helpMockSourceGlossary: "RPP glossary",
  helpMockSourceReports: "Reports and analyses",
  helpMockSourceTeamsAndRoles: "Teams, organisations and roles",
  helpMockSourceSettings: "Personal settings",
  helpMockAnswerHalfDay: "Set the start and end date to the same day and pick the same day half for both – either “Morning” twice or “Afternoon” twice. That gives 0.5 days. If a multi-day absence should start in the afternoon, set only the start day half to “Afternoon”; if it should end in the morning, set the end day half to “Morning”.",
  helpMockAnswerApprovalRequired: "Whether approval is required follows from three rules set by your team: the team's approval policy, the setting per absence type, and a possible personal exemption. The decision is not made in RPP but in the Microsoft Teams “Approvals” app. You can track your requests under “Approvals”.",
  helpMockAnswerSecondaryTeam: "A secondary team is any team that is not a person's primary team. Depending on where you look, the interface calls it “Secondary teams” or “Additional positions”. Important: a person appears in the timeline only under their primary team, and their capacity counts only there – it is neither split nor counted twice.",
  helpMockAnswerOutlookSync: "For all absences, enable “Synchronize approved vacation with Outlook” in Settings under “Outlook calendar”. For an individual case, use the “Synchronize with Outlook” switch under “Synchronization” in the absence form. If your team dictates the setting, the switch is locked.",
  helpMockAnswerPersonMissing: "Check in order: whether a search term is still active under “Filter”, whether the selected period is too short, whether the person is assigned to your team, whether they are inside a collapsed team group, and whether they are a member of the Microsoft Teams team. A frequent special case: the person is assigned to your team only as a secondary team – they then appear under their primary team.",
  helpMockAnswerPresenceVsAbsence: "An absence means “not here” – Vacation, Compensation, Education, Training, Military, Unpaid leave, Other. It may require approval and reduces available capacity. A presence event means “here, but committed” – Home Office, Project, Maintenance, On Call, Standby. It is not approved and does not reduce capacity.",
  helpMockAnswerWhyRed: "Red means status “Critical” in Team capacity. There are two reasons: either utilization has fallen below the critical threshold, or – more often – the team's required staffing is missed on at least one day of the week. The second case occurs even at good utilization. “Affected employees” shows who is concerned.",
  helpMockAnswerVacationBalance: "Your vacation balance is made up of the annual entitlement, the carry forward from last year and manual adjustments, minus pending and approved vacation. The timeline shows the figures E (entitlement), B (booked) and R (remaining days). The values are always calculated and never stored separately – so correct the absence, not the balance.",
  helpMockAnswerReports: "The “Reports” page analyses the planning across all teams and organisations: a people overview with filters by organisation, location and team, plus critical weeks, warnings and the utilization trend. The calculation is the same as in Team capacity.",
  helpMockAnswerRoles: "The Team Admin Center requires the Owner role in the active Microsoft Teams team; the App Admin Center requires the Microsoft Entra role “Teams Administrator” or “Global Administrator”. Without the role the entry does not appear in the navigation. Roles are granted in Microsoft 365, not in RPP.",
  helpMockAnswerSettings: "In Settings you define who approves your requests, how you are notified, and whether your absences appear in Outlook. Language and time zone are taken from Microsoft 365 – there is deliberately no language switcher.",
  helpMockAnswerUnknown: "I can't find anything about that in the RPP help. Please rephrase the question or contact your team administration.",
  helpOpenLabel: "Open help",
  helpPanelClose: "Close help",
  appAdminMailboxSyncLastError: "Reason for the last failure",
  appAdminMailboxSyncBeta: "Beta",
  appAdminMailboxSyncBetaNote: "Beta feature: verified with Microsoft 365. Other senders and message formats are not fully tested yet — please check imported absences.",
  planningBootstrapNoTeamContextTitle: "No team selected.",
  planningBootstrapNoTeamContextMessage: "The planning view does not know which team to show yet. Open RPP as a tab inside a team, or choose a team.",
  teamContextPickerLoading: "Loading your teams …",
  teamContextPickerPrompt: "Which team would you like to plan?",
  teamContextPickerNoTeams: "You are not a member of any team yet. Ask your team lead to add you to one.",
  teamContextPickerFailed: "Your teams could not be loaded. Please try again.",
  planningBootstrapUnauthenticatedTitle: "Sign-in required.",
  planningBootstrapUnauthenticatedMessage: "RPP could not sign in to Microsoft 365. Accept the Microsoft Teams consent dialog and try again.",
  planningBootstrapForbiddenTitle: "No access to this team.",
  planningBootstrapForbiddenMessage: "Your account is known but has no access to this team's data. Please contact your team lead.",
  runtimeConfigUnavailableTitle: "Application configuration unavailable",
  runtimeConfigUnavailableDescription: "The application cannot show reliable planning data without a valid deployment configuration.",
  teamAdminCalendarSourceUrl: "Calendar URL",
  teamAdminCalendarSourceUrlPlaceholder: "https://.../calendar.json or https://.../calendar.ics",
  teamAdminCalendarSourceType: "Format",
  teamAdminHolidayCalendarsTitle: "Holiday calendars",
  teamAdminHolidayCalendarsDescription: "Configure each holiday calendar separately, including its color and its own fetch action.",
  teamAdminCalendarRefreshButton: "Fetch",
  teamAdminCalendarRefreshError: "The holiday calendar could not be refreshed.",
  helpMockSourceGettingStarted: "Getting started with RPP",
  helpMockSourceTeamAdmin: "Team Admin Center for team owners",
  helpMockAnswerGettingStarted: "RPP runs in Microsoft Teams. Use the top navigation for Overview, Team capacity, Approvals and more. Record absences on Overview; track requests under Approvals; check bottlenecks under Team capacity.",
  helpMockAnswerTeamAdmin: "As an owner, Team Admin Center lets you set approvers, absence types, required staffing, Outlook policy and members (Default team and additional positions). Switch the active team first. You still decide requests in the Teams Approvals app – not in Admin Center.",
  helpMockAnswerTeamAdminRestricted: "Team Admin Center and its how-to are only for team owners (Owner) in the Microsoft Teams team. Ask your team owner or IT if you need rules changed.",
  helpStarterTeamAdmin: "What can I configure in Team Admin Center?",
  helpStarterMinimumStaffing: "What does required staffing do?",
} satisfies Record<keyof typeof de, string>;