import type { de } from "./de";

export const it = {
  teamsRailLabel: "Navigazione Microsoft Teams",
  teamsRailActivity: "Attività",
  teamsRailChat: "Chat",
  teamsRailTeams: "Team",
  teamsRailCalendar: "Calendario",
  teamsRailCalls: "Chiamate",
  teamsRailFiles: "File",
  teamsRailResources: "Risorse",
  teamsRailApprovals: "Approvazioni",
  teamsRailApps: "App",
  primaryNavigation: "Navigazione principale",
  infoPageDescription: "RPP è la piattaforma di pianificazione operativa per risorse IT, presenze e capacità – nativa in Microsoft Teams.",
  infoPageBadge: "Release Candidate 5",
  infoPageTitle: "RPP – Pianificazione Risorse e Presenze",
  infoPageGoToTimeline: "Vai alla timeline",
  infoPageGoToReports: "Vai ai report",
  infoPageStatTeamsLabel: "Organizzazioni e team",
  infoPageStatTeamsValue: "Configurabile",
  infoPageStatModeLabel: "Modalità dati",
  infoPageStatModeMock: "Mock / demo",
  infoPageStatModeApi: "API / produzione",
  infoPageStatDeploymentLabel: "Distribuzione",
  infoPageStatDeploymentValue: "Scheda Teams + API Web + SQL",
  infoCardPeopleTitle: "Persone e team",
  infoCardPeopleDescription: "Ogni persona può appartenere a più team e ricoprire più ruoli. Timeline, capacità del team e report condividono la stessa base di appartenenza – coerente e trasversale alle organizzazioni.",
  infoCardPeopleStatus: "Multi-team, multi-ruolo",
  infoCardDataTitle: "Dati e persistenza",
  infoCardDataDescription: "Team, membri, saldi ferie, festività e politiche di approvazione sono archiviati nel backend SQL. Microsoft Graph fornisce identità e foto profilo – l'applicazione rimane l'unica fonte di verità di pianificazione.",
  infoCardDataStatus: "SQL Server + Microsoft Graph",
  infoCardDeliveryTitle: "Consegna",
  infoCardDeliveryDescription: "Frontend, API Web e pacchetto Teams sono versionati e distribuiti insieme. Ciò che vedi nel client Teams corrisponde esattamente alla versione distribuita – nessuna sorpresa.",
  infoCardDeliveryStatus: "Versioni controllate",
  infoCardWhatIsRppTitle: "Cos'è RPP?",
  infoCardWhatIsRppDescription: "RPP è l'applicazione Teams centrale per la pianificazione operativa di risorse, presenze e capacità. Riunisce timeline, vista team, dashboard capacità, flussi di approvazione e amministrazione in un unico spazio di lavoro coerente.",
  infoCardWhatIsRppStatus: "Piattaforma di pianificazione operativa",
  infoCardValueTitle: "A cosa serve RPP?",
  infoCardValueDescription: "RPP crea trasparenza operativa tra le organizzazioni. I responsabili di team vedono a colpo d'occhio chi è disponibile, dove si formano colli di bottiglia e quali assenze sono approvate – senza email, fogli di calcolo o scambi di messaggi.",
  infoCardValueStatus: "Visibilità e supporto decisionale",
  infoCardGetItTitle: "Come si ottiene?",
  infoCardGetItDescription: "RPP viene fornito come app Teams nel tuo tenant. Una volta installata, appare nella navigazione di Teams. I responsabili di team configurano i propri team nel Centro Amministrazione Team – senza bisogno di ticket IT.",
  infoCardGetItStatus: "Teams App Store (tenant)",
  infoFactsTitle: "A colpo d'occhio",
  infoFactsDescription: "Architettura, moduli e funzionamento della piattaforma.",
  infoFactArchitectureLabel: "Architettura",
  infoFactArchitectureValue: "React · Vite · Fluent UI · ASP.NET Core · SQL Server",
  infoFactArchitectureText: "Il frontend viene eseguito come scheda Teams (Vite SPA, Fluent UI v9). L'API Web (ASP.NET Core 8) gestisce tutta la logica di business, la persistenza e l'integrazione Graph. SQL Server archivia tutti i dati di pianificazione.",
  infoFactRolesLabel: "Moduli",
  infoFactRolesValue: "Timeline · Calendario · Capacità team · Ammin. team · Ammin. app · Report · Approvazioni · Impostazioni",
  infoFactRolesText: "Ogni modulo ha uno scopo definito: pianificazione, amministrazione, analisi, approvazioni, configurazione e impostazioni personali.",
  infoFactLocalizationLabel: "Localizzazione",
  infoFactLocalizationValue: "Tedesco, inglese + 36 file di lingua aggiuntivi",
  infoFactLocalizationText: "Tutto il testo visibile è localizzabile. Le lingue principali sono tedesco e inglese; il sistema di traduzione supporta 38 impostazioni locali.",
  infoFactTeamsLabel: "Multi-organizzazione",
  infoFactTeamsValue: "Più organizzazioni · estensibile",
  infoFactTeamsText: "Organizzazioni, sedi e team sono configurabili senza modifiche al codice. La piattaforma è progettata per integrare altre organizzazioni.",
  shellOnlyBadge: "EO-009-C",
  timelineAriaLabel: "Base timeline",
  timelineTitle: "Timeline di pianificazione",
  timelineThreeMonthView: "Vista 3 mesi",
  timelinePeriodLabel: "Periodo",
  timelinePeriodNext30Days: "30 giorni",
  timelinePeriodNextThreeMonths: "Prossimi 3 mesi",
  timelinePeriodNextSixMonths: "Prossimi 6 mesi",
  timelinePeriodFullYear: "Anno intero",
  timelineGroupByLabel: "Raggruppa per",
  timelineGroupByTeams: "Team",
  timelineGroupByPeople: "Persone",
  timelineViewLabel: "Vista",
  timelineViewGantt: "Barre (Gantt)",
  timelineViewList: "Lista",
  timelineViewCalendar: "Calendario (mese)",
  timelineCalendarPrev: "Mese precedente",
  timelineCalendarNext: "Mese successivo",
  timelineCalendarOverflow: "+{count} altri",
  timelineLegendSchoolHolidaySg: "Vacanze scolastiche St. Gallen",
  timelineLegendSchoolHolidayDubendorf: "Vacanze scolastiche Dübendorf",
  timelineLegendPublicHoliday: "Festività",
  timelineAvailablePeople: "Persone disponibili (totale)",
  timelineMinimumStaffing: "Organico minimo richiesto",
  timelineCalendarWeekPrefix: "SET",
  timelineEmployeeColumn: "Collaboratore",
  resourceCompetencies: "Ruoli e competenze",
  resourceVacationSummary: "Riepilogo ferie: diritto, prenotate, residue",
  resourceVacationIcon: "🌴",
  resourceVacationEntitlement: "D",
  resourceVacationBooked: "P",
  resourceVacationRemaining: "R",
  resourceVacationEntitlementTooltip: "Diritto ferie",
  resourceVacationBookedTooltip: "Prenotate",
  resourceVacationRemainingTooltip: "Giorni residui",
  teamGroupingResourceCount: "risorse",
  teamGroupingResourceCountCompact: "coll.",
  teamGroupingExpand: "Espandi gruppo team",
  teamGroupingCollapse: "Riduci gruppo team",
  eventTypeVacation: "Ferie",
  eventTypeCompensation: "Compensazione",
  eventTypeEducation: "Formazione",
  eventTypeHomeOffice: "Home Office",
  eventTypeTraining: "Addestramento",
  eventTypeMilitary: "Servizio militare",
  eventTypeUnpaidLeave: "Congedo non retribuito",
  eventTypeOtherAbsence: "Altra assenza",
  eventTypeProject: "Progetto",
  eventTypeMaintenance: "Manutenzione",
  eventTypeOnCall: "Reperibilità",
  eventTypeStandby: "Standby",
  detailsResourceTitle: "Dettagli risorsa",
  detailsPresenceTitle: "Dettagli evento",
  detailsResourceSection: "Risorsa",
  detailsPresenceSection: "Evento di presenza",
  detailsOrganisation: "Organizzazione",
  detailsPrimaryTeam: "Team principale",
  detailsSecondaryTeams: "Altri team",
  detailsVacation: "Ferie",
  detailsEventType: "Tipo evento",
  detailsEventTitle: "Titolo",
  detailsStartDate: "Data inizio",
  detailsEndDate: "Data fine",
  detailsDuration: "Durata",
  detailsDays: "giorni",
  absenceNew: "Nuova assenza",
  absencePersistError: "Impossibile salvare l'assenza. Riprova.",
  approvalSubmitPending: "La richiesta è stata inviata a Microsoft 365 per l'approvazione. L'approvatore la troverà nell'app Teams «Approvazioni».",
  approvalSubmitAutoApproved: "L'assenza è stata salvata – per questa persona non è richiesta alcuna approvazione.",
  approvalSubmitError: "Impossibile inviare la richiesta. Verifica l'approvatore nel Centro Amministrazione Team e riprova.",
  myApprovalsTitle: "Le mie richieste",
  myApprovalsDescription: "Richieste di ferie con stato di approvazione Microsoft 365. Le decisioni vengono prese nell'app Teams «Approvazioni».",
  myApprovalsRefresh: "Aggiorna stato",
  myApprovalsOpenTeams: "Apri Approvazioni in Teams",
  myApprovalsEmpty: "Nessuna richiesta presente. Le nuove richieste vengono create dalla timeline («Richiedi approvazione»).",
  myApprovalsLoadError: "Impossibile caricare le richieste. Riprova.",
  myApprovalsColPeriod: "Periodo",
  myApprovalsColModified: "Ultima modifica",
  myApprovalsColM365: "M365 Approvals",
  myApprovalsM365Linked: "Linked",
  myApprovalsM365Missing: "No Graph item",
  myApprovalsGraphId: "Graph id",
  myApprovalsWhereToFind: "In the Teams Approvals app: as approver under Received, as requester under Sent. Check the environment filter (tenant). The item only appears for the selected approver account.",
  absenceApproverPolicyManaged: "Gestito dalla politica del team",
  absenceApproverNone: "Select an approver",
  absenceApproverRequired: "Please select an approver or configure a default approver in the Team Admin Center.",
  orgConfigTitle: "Organizzazioni e sedi",
  orgConfigDescription: "Elenchi configurabili per organizzazioni partner e sedi. I valori dei membri derivano dal profilo Microsoft 365 (azienda, ufficio) e vengono assegnati qui.",
  orgConfigOrganisations: "Organizzazioni",
  orgConfigLocations: "Sedi",
  orgConfigOrganisationMappings: "Assegnazione valore profilo → organizzazione",
  orgConfigLocationMappings: "Assegnazione valore profilo → sede",
  orgConfigUnassigned: "Non assegnato",
  orgConfigAdd: "Aggiungi",
  orgConfigRemove: "Rimuovi",
  orgConfigSave: "Salva organizzazioni e sedi",
  orgConfigSaved: "Salvato. Le assegnazioni hanno effetto immediato.",
  orgConfigLoadError: "Impossibile caricare la configurazione.",
  orgConfigSaveError: "Impossibile salvare la configurazione.",
  myApprovalsColOutlook: "Outlook",
  teamCapacityAbsentPersons: "Persone assenti",
  teamCapacityAbsenceDays: "Assenza (giorni-persona)",
  teamCapacityAvailableDays: "Disponibile (giorni-persona)",
  absenceCreateTitle: "Richiedi assenza",
  absenceEditTitle: "Modifica assenza",
  absenceRequestApproval: "Richiedi approvazione",
  absenceDeleteConfirm: "Conferma eliminazione",
  absenceFieldType: "Tipo assenza",
  absenceFieldStartDate: "Data inizio",
  absenceFieldStartHalf: "Mezza giornata inizio",
  absenceFieldEndDate: "Data fine",
  absenceFieldEndHalf: "Mezza giornata fine",
  absenceFieldSubstitute: "Sostituto",
  absenceFieldComment: "Commento",
  absenceSubstituteNone: "Nessun sostituto",
  absenceCalculatedWorkdays: "Giorni lavorativi",
  absenceSyncTitle: "Sincronizzazione",
  absenceSyncOutlook: "Sincronizza con Outlook",
  absenceApprovalStatus: "Stato richiesta",
  absenceApprovalStatusDraft: "Bozza",
  absenceApprovalStatusPending: "In attesa",
  absenceApprovalStatusApproved: "Approvato",
  absenceApprovalStatusRejected: "Rifiutato",
  absenceVacationEntitlementTitle: "Diritto ferie 2026",
  absenceVacationAvailable: "Disponibile",
  absenceVacationBooked: "Già prenotate",
  absenceVacationAfterBooking: "Dopo questa prenotazione",
  vacationRequestStatus: "Stato richiesta",
  vacationRequestApprovalSection: "Approvazione",
  vacationRequestApprover: "Approvatore",
  vacationRequestCommentToApprover: "Commento per l'approvatore",
  vacationRequestSaveDraft: "Salva bozza",
  vacationRequestSubmitForApproval: "Invia per approvazione",
  approvalPrototypeTitle: "Flusso di approvazione interattivo",
  approvalPrototypeBadge: "EO-202-A Flusso simulato",
  approvalLiveModeBadge: "Processo di approvazione Microsoft 365",
  approvalPrototypeTimeline: "Avanzamento approvazione",
  approvalPrototypeStepPrepare: "Prepara",
  approvalPrototypeStepReview: "Verifica",
  approvalPrototypeStepSubmitted: "Inviato",
  approvalPrototypeStepTeamLead: "Capo dipartimento",
  approvalPrototypeStepDecision: "Decisione",
  approvalPrototypePrepareTitle: "Prepara richiesta ferie",
  approvalPrototypePrepareDescription: "Inserisci i dati della richiesta come nella futura interfaccia produttiva. Tutto rimane locale nel browser.",
  approvalPrototypeReviewTitle: "Verifica richiesta",
  approvalPrototypeReviewDescription: "Controlla periodo, durata e approvatore prima di inviare la richiesta simulata.",
  approvalPrototypeSubmittedTitle: "Richiesta inviata",
  approvalPrototypeSubmittedDescription: "La richiesta è nel flusso simulato presso il capo dipartimento. Non è stata avviata alcuna approvazione reale.",
  approvalPrototypeTeamLeadTitle: "Simula decisione del capo dipartimento",
  approvalPrototypeTeamLeadDescription: "Passa alla prospettiva del capo dipartimento e simula approvazione o rifiuto.",
  approvalPrototypeDecisionTitle: "Flusso completato",
  approvalPrototypeDecisionDescription: "Il flusso simulato mostra lo stato finale. Nessun dato produttivo è stato modificato.",
  approvalPrototypeReviewRequest: "Verifica richiesta",
  approvalPrototypeBackToEdit: "Torna alla modifica",
  approvalPrototypeBackToPending: "Torna a inviato",
  approvalPrototypeOpenTeamLead: "Apri vista capo dipartimento",
  approvalPrototypeCancelRequest: "Annulla richiesta",
  approvalPrototypeApprove: "Approva",
  approvalPrototypeReject: "Rifiuta",
  approvalPrototypeStartNew: "Avvia nuovo flusso simulato",
  approvalPrototypeRoutingHint: "L'approvatore proviene dalla politica team simulata e potrà essere sostituito dall'API produttiva in seguito.",
  approvalPrototypeSubmittedMessage: "La richiesta attende visibilmente la decisione del capo dipartimento. Questo stato è solo temporaneo nell'UI.",
  approvalPrototypeDecisionComment: "Commento decisione",
  approvalPrototypeApprovedMessage: "La richiesta è stata approvata nel flusso simulato.",
  approvalPrototypeRejectedMessage: "La richiesta è stata rifiutata nel flusso simulato.",
  approvalPrototypeCancelledMessage: "La richiesta è stata annullata nel flusso simulato.",
  approvalPrototypeApprovedPersistedMessage: "Le ferie approvate sono state salvate nella timeline simulata.",
  approvalPrototypePersistError: "Impossibile salvare le ferie approvate nello stato simulato.",
  approvalPrototypeSummaryTitle: "Riepilogo richiesta",
  approvalPrototypeSummaryDescription: "Stato simulato attuale per dimostrazione e verifica usabilità.",
  approvalPrototypeRequester: "Richiedente",
  approvalPrototypeMockOnly: "Solo simulazione, non è un processo produttivo",
  approvalStatusDraft: "Bozza",
  approvalStatusSubmitted: "Inviato",
  approvalStatusPendingApproval: "In attesa di approvazione",
  approvalStatusApproved: "Approvato",
  approvalStatusRejected: "Rifiutato",
  approvalStatusCancelled: "Annullato",
  approvalStatusFailed: "Fallito",
  absenceCalculatedRemainingVacation: "Ferie residue dopo la prenotazione",
  absenceValidationRequired: "Compila tutti i campi obbligatori.",
  absenceValidationEndBeforeStart: "La data di fine non può essere precedente alla data di inizio.",
  absenceValidationDuration: "La combinazione di mezze giornate selezionata non produce una durata valida.",
  absenceValidationOutsideTimeline: "La modifica è al di fuori del periodo visibile.",
  absenceValidationMoveDuration: "Lo spostamento non deve modificare la durata dell'assenza.",
  absenceTypeVacation: "Ferie",
  absenceTypeCompensation: "Compensazione",
  absenceTypeEducation: "Formazione",
  absenceTypeTraining: "Addestramento",
  absenceTypeMilitary: "Servizio militare",
  absenceTypeUnpaidLeave: "Congedo non retribuito",
  absenceTypeOther: "Altro",
  dayHalfMorning: "Mattina",
  dayHalfAfternoon: "Pomeriggio",
  dayHalfFullDay: "Giorno intero",
  capacityAvailable: "Capacità disponibile",
  teamCapacityDashboardTitle: "Capacità team",
  teamCapacityDashboardDescription: "Riepilogo settimanale aggregato basato sul motore centrale di capacità.",
  teamCapacityTeamLabel: "Team",
  teamCapacityAvailable: "Disponibile",
  teamCapacityAbsent: "Assente",
  teamCapacityUtilization: "Occupazione",
  teamCapacityMembers: "Membri del team",
  teamCapacityNominal: "Nominale",
  teamCapacityCriticalWeeks: "Settimane critiche",
  teamCapacityCriticalWeeksShort: "Sett. critiche",
  teamCapacityWeeklyOverview: "Riepilogo settimanale",
  teamCapacityStatus: "Stato",
  teamCapacityMetric: "Indicatore",
  teamCapacityAffectedResources: "Collaboratori interessati",
  teamCapacityNoAffectedResources: "Nessun collaboratore interessato in questa settimana.",
  teamCapacityStatusOk: "OK",
  teamCapacityStatusWarning: "Avviso",
  teamCapacityStatusCritical: "Critico",
  designSystemSectionTitle: "Fondamenti del sistema di design",
  designSystemSectionDescription: "Pattern visivi riutilizzabili per i prossimi ordini di ingegneria.",
  designCardLayoutTitle: "Layout",
  designCardLayoutDescription: "Shell, intestazione, area contenuti e spaziatura responsive seguono una griglia uniforme.",
  designCardThemeTitle: "Tema",
  designCardThemeDescription: "Modalità chiara e scura basate su token Fluent UI, estensibili.",
  designCardTypographyTitle: "Tipografia",
  designCardTypographyDescription: "Titoli, sezioni e testi di aiuto utilizzano dimensioni e pesi coerenti.",
  statusReady: "Pronto",
  statusFoundation: "Base",
  statusReserved: "Riservato",
  placeholderSurfaceTitle: "Shell applicazione",
  placeholderSurfaceText: "Questa pagina è intenzionalmente un segnaposto. La funzionalità specialistica seguirà nei prossimi ordini di ingegneria.",
  errorBoundaryTitle: "Qualcosa è andato storto.",
  errorBoundaryMessage: "Impossibile caricare la vista. Riprova o segnala il riferimento al supporto.",
  errorReferenceLabel: "Riferimento",
  planningBootstrapEmptyTitle: "Nessuna persona pianificabile trovata.",
  planningBootstrapEmptyMessage: "La vista di pianificazione richiede membri del team prima di poter mostrare capacità e assenze.",
  mySettingsTitle: "Le mie impostazioni",
  mySettingsLoading: "Caricamento impostazioni...",
  mySettingsProfileTitle: "Profilo",
  mySettingsName: "Nome",
  mySettingsEmail: "Email",
  mySettingsTeam: "Team",
  mySettingsApprovalTitle: "Approvazione",
  mySettingsApprovalDescription: "Approvatore predefinito e sostituto per le richieste di ferie.",
  mySettingsDefaultApprover: "Approvatore predefinito",
  mySettingsFallbackApprover: "Approvatore sostituto",
  mySettingsApproverSource: "Origine",
  mySettingsApproverSourceUser: "Impostazione personale",
  mySettingsApproverSourceTeamPolicy: "Politica team",
  mySettingsApproverSourceTeamLead: "Capo dipartimento",
  mySettingsApproverSourceFallback: "Sostituto",
  mySettingsNoApproverWarning: "Nessun approvatore configurato. Contatta l'amministratore del team.",
  mySettingsNotificationsTitle: "Notifiche",
  mySettingsNotificationsDescription: "Come sarai informato sui cambiamenti di stato delle tue richieste.",
  mySettingsNotificationInApp: "Notifica in-app",
  mySettingsNotificationEmail: "Notifica email",
  mySettingsNotificationTeams: "Notifica Teams",
  mySettingsOutlookTitle: "Calendario Outlook",
  mySettingsOutlookDescription: "Comportamento predefinito per le assenze approvate.",
  mySettingsOutlookSync: "Sincronizza ferie approvate con Outlook",
  mySettingsOutlookEnabled: "Attivato",
  mySettingsOutlookDisabled: "Disattivato",
  mySettingsOutlookManaged: "Gestito dalla politica team",
  mySettingsRegionalTitle: "Regionale",
  mySettingsRegionalDescription: "Lingua e fuso orario sono presi da Microsoft 365 o dal browser.",
  mySettingsLanguage: "Lingua",
  mySettingsTimeZone: "Fuso orario",
  mySettingsManagedByTeamPolicy: "Gestito dalla politica team",
  mySettingsNotConfigured: "Non configurato",
  mySettingsResetToDefaults: "Ripristina valori predefiniti",
  mySettingsSavedToast: "Impostazioni salvate",
  mySettingsResetToast: "Impostazioni ripristinate",
  outlookSyncStatusNotRequired: "Nessuna sincronizzazione Outlook",
  outlookSyncStatusPending: "Sincronizzazione in corso",
  outlookSyncStatusSynced: "Calendario Outlook aggiornato",
  outlookSyncStatusFailed: "Sincronizzazione Outlook fallita",
  outlookSyncRetry: "Riprova sincronizzazione",
  vacationBalanceTitle: "Saldo ferie",
  vacationBalanceAnnualEntitlement: "Diritto annuale",
  vacationBalanceCarryForward: "Riporto",
  vacationBalanceManualAdjustments: "Rettifiche manuali",
  vacationBalancePendingVacation: "Ferie richieste",
  vacationBalanceApprovedVacation: "Ferie approvate",
  vacationBalanceRemainingBalance: "Saldo residuo",
  vacationBalancePreviewTitle: "Anteprima saldo",
  vacationBalanceCurrentBalance: "Saldo attuale",
  vacationBalanceRequestedVacation: "Giorni di ferie richiesti",
  vacationBalanceRemainingAfterSubmission: "Saldo dopo l'invio",
  vacationBalanceExceedsWarning: "La richiesta supera il saldo ferie disponibile. L'invio non sarà bloccato nello Sprint 3.",
  vacationBalanceAdjustmentTitle: "Rettifica saldo",
  vacationBalanceAdjustmentValue: "Rettifica",
  vacationBalanceAdjustmentReason: "Motivo",
  vacationBalanceSaveAdjustment: "Salva rettifica",
  vacationBalanceHistoryTitle: "Cronologia rettifiche",
  vacationBalanceHistoryPrevious: "Precedente",
  vacationBalanceHistoryNew: "Nuovo",
  vacationBalanceHistoryEmpty: "Nessuna rettifica manuale presente.",
  vacationBalancePreviewControlsTitle: "Verifica richiesta ferie",
  teamAdminTitle: "Centro Amministrazione Team",
  teamAdminLoading: "Caricamento Centro Amministrazione Team...",
  teamAdminLoadError: "Impossibile caricare il Centro Amministrazione Team.",
  teamAdminSavedToast: "Impostazioni team salvate",
  teamAdminAutoSaveEnabled: "Salvataggio automatico attivo",
  teamAdminAutoSaveSaving: "Salvataggio modifiche...",
  teamAdminNoManagedTeams: "Nessun team gestibile trovato.",
  teamAdminTeamSelection: "Selezione team",
  teamAdminTeamSelectionDescription: "Team per i quali sei autorizzato come capo dipartimento o amministratore delegato.",
  teamAdminActiveTeam: "Team attivo",
  teamAdminManagedTeam: "Team gestito",
  teamAdminAllTeams: "Tutti i team",
  teamAdminAllTeamsDescription: "Riepilogo alfabetico di tutti i membri per la manutenzione dei dati demo.",
  teamAdminTeamInformation: "Informazioni team",
  teamAdminTeamLead: "Capo dipartimento",
  teamAdminMemberCount: "Membri",
  teamAdminDefaultApprover: "Approvatore predefinito",
  teamAdminBackupApprover: "Approvatore sostituto",
  teamAdminNoBackupApprover: "Nessun approvatore sostituto",
  teamAdminDisplaySettings: "Visualizzazione",
  teamAdminDisplaySettingsDescription: "Opzioni di visualizzazione per la timeline di pianificazione. Valgono per l'intera installazione.",
  teamAdminShowVacationSummary: "Mostra indicatori ferie nella timeline",
  teamAdminEventColorMode: "Colori eventi",
  teamAdminEventColorByType: "Per tipo assenza",
  teamAdminEventColorByTeam: "Per team",
  teamAdminTeamColor: "Colore",
  teamAdminTeamColorAuto: "Automatico",
  teamColorBlue: "Blu",
  teamColorGreen: "Verde",
  teamColorMarigold: "Giallo",
  teamColorBerry: "Bacca",
  teamColorTeal: "Turchese",
  teamColorPumpkin: "Arancione",
  teamColorLavender: "Viola",
  teamColorSeafoam: "Menta",
  teamColorCranberry: "Rosso",
  teamColorPlatinum: "Grigio",
  teamAdminApprovalPolicy: "Politica di approvazione",
  teamAdminApprovalPolicyDescription: "Questa politica influisce sulle nuove richieste di ferie e sulle impostazioni personali dei membri del team.",
  teamAdminAllowUserOverride: "Gli utenti possono scegliere un altro approvatore",
  teamAdminOutlookSyncPolicy: "Sincronizzazione Outlook",
  teamAdminOutlookSyncOptional: "Opzionale",
  teamAdminOutlookSyncMandatory: "Obbligatorio",
  teamAdminOutlookSyncDisabled: "Disattivato",
  teamAdminAbsenceEntryTypes: "Tipi di assenza",
  teamAdminAbsenceEntryTypesDescription: "Gestisci centralmente i tipi di assenza, l'obbligo di approvazione e il consumo del saldo ferie.",
  teamAdminEntryTypeName: "Tipo",
  teamAdminEntryTypeActive: "Attivo",
  teamAdminEntryTypeRequiresApproval: "Approvazione",
  teamAdminEntryTypeConsumesVacation: "Saldo ferie",
  teamAdminEntryTypeActions: "Azione",
  teamAdminEntryTypeNew: "Nuovo tipo assenza",
  teamAdminEntryTypeNewPlaceholder: "es. Conferenza",
  teamAdminEntryTypeAdd: "Aggiungi",
  teamAdminEntryTypeDelete: "Elimina tipo assenza",
  teamAdminTeamMembers: "Membri del team",
  teamAdminTeamMembersDescription: "Assegnazione team predefinito, posizioni aggiuntive, percentuale impiego, saldo ferie, esenzione approvazione e approvatore effettivo.",
  teamAdminMemberAdd: "Aggiungi membro",
  teamAdminMemberAddPlaceholder: "Seleziona persona dallo spazio Teams",
  teamAdminMemberAddButton: "Aggiungi",
  teamAdminMemberName: "Nome",
  teamAdminMemberEmail: "Email",
  teamAdminMemberPosition: "Posizione",
  teamAdminMemberActions: "Actions",
  teamAdminMemberRemove: "Remove",
  teamAdminMemberRemoveConfirm: "Remove \"{name}\" from RPP planning? The person may remain in the M365 team; absence history is kept.",
  teamAdminMemberRemoveHint: "Removes the person from all RPP teams on this host (after save).",
  teamAdminMemberRemoveError: "The person could not be removed from RPP planning. Try again or reload the page.",
  teamAdminMemberRemoveEmpty: "No RPP assignment was found for this person (already removed).",
  teamAdminPrimaryTeam: "Team predefinito",
  teamAdminAdditionalPositions: "Posizioni aggiuntive",
  teamAdminEmploymentPercentage: "Percentuale impiego",
  teamAdminVacationBalance: "Saldo ferie",
  teamAdminActiveVacationRequests: "Richieste attive",
  teamAdminApprovalExempt: "Nessuna approvazione richiesta",
  teamAdminNoApprovalRequired: "Nessuna approvazione richiesta",
  teamAdminEffectiveApprover: "Approvatore effettivo",
  teamAdminNotAvailable: "Non disponibile",
  teamAdminTeamManagement: "Gestione team",
  teamAdminTeamManagementDescription: "Crea, rinomina ed elimina team, e definisci l'ordine di visualizzazione indipendentemente dall'ordine alfabetico.",
  teamAdminTeamManagementOrder: "Ordine",
  teamAdminTeamManagementName: "Team",
  teamAdminTeamManagementOrganization: "Organizzazione",
  teamAdminTeamMoveUp: "Sposta in alto",
  teamAdminTeamMoveDown: "Sposta in basso",
  teamAdminTeamNew: "Nuovo team",
  teamAdminTeamNewPlaceholder: "es. Cloud Engineering",
  teamAdminTeamAdd: "Aggiungi team",
  teamAdminTeamDelete: "Elimina team",
  teamAdminTeamManagementUpdatedToast: "Gestione team aggiornata",
  teamAdminTeamNameRequired: "Il nome del team non può essere vuoto.",
  teamAdminTeamNameDuplicate: "Esiste già un team con questo nome.",
  teamAdminTeamHasMembers: "I team con membri assegnati non possono essere eliminati.",
  teamAdminTeamLastTeam: "L'ultimo team non può essere eliminato.",
  teamAdminTeamRequiredStaffing: "Organico minimo",
  teamCapacityRequiredStaffing: "Organico minimo",
  reportsSharedPlanningTitle: "Pianificazione condivisa tra organizzazioni",
  reportsSharedPlanningSubtitle: "Chiara separazione/filtro per organizzazione e sede",
  reportsOrganizationLabel: "Organizzazione",
  reportsOrgFilterAll: "Tutte",
  reportsTableEmployee: "Collaboratore",
  reportsTableLocation: "Sede",
  reportsTableTeamsRoles: "Team / Ruoli",
  reportsTeamFilter: "Team",
  reportsFilterHint: "Filtrabile per organizzazione, sede e team",
  reportsAnalysisTitle: "Analisi – Sotto-organici critici",
  reportsAnalysisSubtitle: "Analisi visiva e tendenze (in seguito con Power BI)",
  reportsCriticalWeeks: "Settimane critiche",
  reportsCriticalWeeksHint: "Sotto l'organico minimo",
  reportsWarnings: "Avvisi",
  reportsWarningsHint: "Sotto la soglia di avviso",
  reportsUtilization: "Occupazione",
  reportsUtilizationHint: "Prossimi 3 mesi",
  reportsChartTitle: "Occupazione nel tempo (tutti i team)",
  reportsLegendUtilization: "Occupazione",
  reportsLegendMinStaffing: "Organico minimo",
  reportsLegendWarnThreshold: "Soglia di avviso",
  reportsCriticalWeeksLabel: "Settimane critiche:",
  reportsNoCriticalWeeks: "Nessuna settimana critica",
  reportsToPowerBi: "A Power BI",
  reportsCriticalTeams: "team critici",
  reportsCriticalWeekUtilization: "Occupazione",
  reportsMinimumAvailable: "Minimo disponibile",
  reportsAvailableCapacity: "Disponibile",
  reportsMyAbsencesTitle: "Le mie assenze e sincronizzazione Outlook",
  reportsMyAbsencesSubtitle: "Riepilogo personale e sincronizzazione",
  reportsMyAbsencesHeading: "Le mie assenze 2026",
  reportsMyAbsencesEmpty: "Nessuna assenza personale nel periodo attuale.",
  reportsDays: "giorni",
  reportsStatusRequested: "Richiesto",
  reportsStatusPlanned: "Pianificato",
  reportsOutlookSyncTitle: "Sincronizzazione Outlook",
  reportsOutlookSyncText: "Le tue assenze vengono sincronizzate con Outlook.",
  reportsOutlookLastSync: "Ultima sincronizzazione: Oggi, 08:45",
  reportsOutlookSyncPending: "In attesa di approvazione",
  personCardTabOverview: "Panoramica",
  personCardTabContact: "Contatto",
  personCardTabOrganization: "Organizzazione",
  personCardSendQuickMessage: "Invia un messaggio rapido",
  personCardLastOnline: "Ultimo accesso: 14 minuti fa · Disponibile alle 12:00",
  personCardWorkHours: "Orario di lavoro: 06:30 - 16:00",
  personCardInOffice: "In ufficio previsto",
  personCardSameTimezone: "Stesso fuso orario",
  personCardContactInformation: "Informazioni di contatto",
  personCardAssistant: "Assistente",
  personCardEmail: "Email",
  personCardChat: "Chat",
  personCardPhoneBusiness: "Telefono (lavoro)",
  personCardWorkLocation: "Luogo di lavoro",
  personCardCompany: "Azienda",
  personCardMoreContact: "Mostra più contatti",
  personCardDepartment: "Dipartimento",
  personCardBusinessAddress: "Indirizzo (lavoro)",
  personCardClose: "Chiudi",
  personCardTeams: "Team",
  personCardManager: "Superiore",
  demoDataSectionTitle: "Dati demo",
  demoDataSectionDescription: "Le modifiche ai dati simulati (team, organico minimo, assenze, impostazioni, saldi ferie, festività e vacanze scolastiche) vengono salvate localmente nel browser e sopravvivono al riavvio. Con Esporta/Importa puoi gestire in particolare il blocco JSON publicHolidays.",
  demoDataChangesPresent: "Sono presenti modifiche locali.",
  demoDataResetButton: "Ripristina dati demo",
  demoDataExportButton: "Esporta dati demo",
  demoDataImportButton: "Importa dati demo",
  demoDataExportFailed: "Esportazione fallita. Verifica il browser.",
  demoDataImportFailed: "Importazione fallita. Verifica il file JSON.",
  teamAdminSchoolHolidaySyncTitle: "Aggiorna calendario vacanze scolastiche",
  teamAdminSchoolHolidaySyncDescription: "Carica le vacanze scolastiche di St. Gallen e Dübendorf/Zurigo dalle fonti JSON Open Data e le salva nel calendario simulato locale.",
  teamAdminSchoolHolidaySyncYear: "Anno solare",
  teamAdminSchoolHolidaySyncButton: "Recupera vacanze scolastiche",
  teamAdminSchoolHolidaySyncRunning: "Caricamento vacanze scolastiche...",
  teamAdminSchoolHolidaySyncSuccess: "Vacanze scolastiche aggiornate per",
  teamAdminSchoolHolidaySyncDays: "giorni solari",
  teamAdminSchoolHolidaySyncError: "Impossibile caricare le vacanze scolastiche. Verifica rete/CORS o usa l'importazione JSON.",
  teamAdminSchoolHolidaySyncStGallenNoData: "Nota: St. Gallen non ha fornito voci per quest'anno.",
  teamAdminSchoolHolidaySyncZurichNoData: "Nota: Zurigo/Dübendorf non ha fornito voci per quest'anno.",
  teamAdminFederalHolidaySyncButton: "Recupera festività predefinite Zurigo",
  teamAdminFederalHolidaySyncRunning: "Aggiornamento festività predefinite Zurigo...",
  teamAdminFederalHolidaySyncSuccess: "Festività predefinite Zurigo aggiornate per",
  teamAdminFederalHolidaySyncError: "Impossibile aggiornare le festività predefinite Zurigo.",
  teamAdminAbsenceEntryTypesSaveHint: "I tipi di assenza nuovi o modificati vengono applicati automaticamente e appaiono poi nel modulo assenza.",
  pageAppAdminDescription: "Amministrazione centrale dell'applicazione per provider backend, configurazione e diagnostica.",
  appAdminEffectiveConfigTitle: "Configurazione effettiva",
  appAdminEffectiveConfigDescription: "Configurazione applicativa attualmente attiva, inclusa l'origine di ogni valore.",
  appAdminFieldDataSource: "Provider dati",
  appAdminFieldMembershipSource: "Fonte appartenenza",
  appAdminFieldSharePointSiteUrl: "URL sito SharePoint",
  appAdminFieldApiBaseUrl: "URL base API",
  appAdminFieldEnvironment: "Ambiente",
  appAdminFieldRelease: "Release",
  appAdminFieldRevision: "Revisione",
  appAdminOriginLocalOverride: "Sovrascrittura locale",
  appAdminOriginDeployment: "Distribuzione",
  appAdminOriginBuild: "Build",
  appAdminOriginDefault: "Predefinito",
  appAdminOriginStandaloneBrowser: "Standalone browser (mock demo)",
  appAdminFieldStandaloneBrowserUsesMock: "Mock in standalone browser",
  appAdminStandaloneBrowserUsesMockOn: "On (browser ? mock, Teams ? deployment)",
  appAdminStandaloneBrowserUsesMockOff: "Off",
  appAdminProviderMock: "Dati simulati (Demo)",
  appAdminProviderSharePoint: "Elenchi SharePoint",
  appAdminProviderApi: "RPP Web API",
  appAdminMembershipMock: "Simulato",
  appAdminMembershipGraph: "Microsoft Graph",
  appAdminProviderConfigTitle: "Provider backend",
  appAdminProviderConfigDescription: "Selezione del provider come sovrascrittura locale per questo browser. La configurazione di distribuzione rimane invariata.",
  appAdminAccessDeniedTitle: "Non autorizzato",
  appAdminAccessDeniedDescription: "Il Centro Amministrazione App richiede il ruolo Microsoft Entra «Teams Administrator» (o «Global Administrator»). Contatta l'amministrazione IT.",
  teamAdminAccessDeniedTitle: "Non autorizzato",
  teamAdminAccessDeniedDescription: "Il Centro Amministrazione Team richiede il ruolo di proprietario (Owner) nel team Microsoft Teams attivo.",
  activeTeamChipLabel: "Team attivo",
  appAdminHolidayResetTitle: "Ripristina calendario festività",
  appAdminHolidayResetDescription: "Svuota il calendario centrale delle festività e vacanze scolastiche di questo tenant per poter caricare calendari individuali freschi (Centro Amministrazione Team → Azioni calendario).",
  appAdminHolidayResetButton: "Svuota calendario festività",
  appAdminHolidayResetConfirm: "Conferma svuotamento",
  appAdminHolidayResetSuccess: "Il calendario è stato svuotato. Ricarica i calendari nel Centro Amministrazione Team.",
  appAdminHolidayResetError: "Impossibile svuotare il calendario (verifica permessi o connessione).",
  appAdminSharePointSiteUrlHint: "Solo https e *.sharepoint.com.",
  appAdminApiBaseUrlHint: "Solo https (http solo per localhost).",
  appAdminCspHint: "Nota: La Content-Security-Policy della distribuzione deve consentire l'origine API in connect-src.",
  appAdminSaveOverride: "Applica localmente",
  appAdminResetOverride: "Ripristina sovrascrittura",
  appAdminOverrideActive: "È attiva una sovrascrittura locale per questo browser.",
  appAdminReloadPrompt: "La configurazione è stata modificata. L'applicazione deve essere ricaricata per avere effetto.",
  appAdminReloadNow: "Ricarica ora",
  appAdminValidationSharePointUrl: "Inserisci un URL sito SharePoint valido (https, *.sharepoint.com).",
  appAdminValidationApiUrl: "Inserisci un URL base API valido (https, http solo per localhost).",
  appAdminConnectionTestTitle: "Test di connessione",
  appAdminConnectionTestDescription: "Verifica la raggiungibilità dei provider. I risultati mostrano stato e latenza.",
  appAdminTestConnection: "Testa connessione",
  appAdminTestRunning: "Test in corso…",
  appAdminTestHealthy: "Raggiungibile",
  appAdminTestFailed: "Fallito",
  appAdminExportTitle: "Configurazione di distribuzione",
  appAdminExportDescription: "Genera un file config/runtime-config.js distribuibile dalla configurazione effettiva.",
  appAdminExportButton: "Scarica runtime-config.js",
  appAdminNotConfigured: "Non configurato",
  footerText: "Microsoft Teams App Shell • Sprint 1 • Osservabilità EO-010",
  appAdminMailboxSyncTitle: "Outlook Mailbox Sync",
  appAdminMailboxSyncDescription: "Status and manual control of the inbound Outlook sync via the central mailbox. Emails with .ics calendar attachments are automatically imported as absences.",
  appAdminMailboxSyncEnabled: "Status",
  appAdminMailboxSyncEnabledYes: "Enabled",
  appAdminMailboxSyncEnabledNo: "Disabled",
  appAdminMailboxSyncRunning: "Running",
  appAdminMailboxSyncRunningYes: "Yes",
  appAdminMailboxSyncRunningNo: "No",
  appAdminMailboxSyncLastRun: "Last run",
  appAdminMailboxSyncNever: "Never",
  appAdminMailboxSyncProcessed: "Emails processed",
  appAdminMailboxSyncCreated: "Absences created",
  appAdminMailboxSyncUpdated: "Absences updated",
  appAdminMailboxSyncDeleted: "Absences deleted",
  appAdminMailboxSyncErrors: "Errors",
  appAdminMailboxSyncSkipped: "Skipped",
  appAdminMailboxSyncEntries: "Latest entries",
  appAdminMailboxSyncNoData: "No sync data available. Click Refresh status.",
  appAdminMailboxSyncRefresh: "Refresh status",
  appAdminMailboxSyncRefreshing: "Loading…",
  appAdminMailboxSyncTrigger: "Sync now",
  appAdminMailboxSyncTriggering: "Syncing…",
  appAdminMailboxSyncStatusError: "Could not load sync status.",
  appAdminMailboxSyncTriggerError: "Could not start sync.",
  appTitle: "Resources & Presence Planning",
  appSubtitle: "Operations planning for IT resources, presence, and capacity",
  appLogoAlt: "M365 Resources & Presence Planning app logo",
  themeLight: "Light",
  themeDark: "Dark",
  themeToggle: "Toggle appearance",
  headerSearch: "Search",
  headerSearchPlaceholder: "Search (Ctrl+E)",
  moreActions: "More actions",
  help: "Help",
  navOverview: "Overview",
  navTeamCapacity: "Team capacity",
  navMyAbsences: "My absences",
  navApprovals: "Approvals",
  navTeamAdmin: "Team Admin Center",
  navReports: "Reports",
  navSettings: "Settings",
  navInfo: "Info",
  pageOverviewDescription: "Operational planning overview with timeline, resources, teams, and presence events.",
  pageTeamCapacityDescription: "Weekly team capacity with availability, absence share, and risk status.",
  pageMyAbsencesDescription: "Placeholder for personal absences and future request overview.",
  pageApprovalsDescription: "Placeholder for future approvals and decision workflows.",
  pageTeamAdminDescription: "Central administration for team approvers, backups, policies, and vacation visibility.",
  pageReportsDescription: "Placeholder for reporting, analytics, and export views.",
  pageSettingsDescription: "Personal settings for absence requests, approvers, notifications, and Outlook synchronization.",
  pageInfoDescription: "Information about the application, architecture, and design system foundation.",
  timelinePeriodWeek: "Week",
  timelinePeriodMonth: "Month",
  timelineToday: "Today",
  timelineFilter: "Filter",
  timelineFilterLabel: "Filter",
  timelineFilterPlaceholder: "Search team or person",
  detailsClose: "Close",
  absenceCreate: "Save",
  absenceUpdate: "Save changes",
  absenceDelete: "Delete",
  absenceCancel: "Cancel",
  errorRetryAction: "Try again",
  planningBootstrapLoading: "Loading planning data ...",
  mySettingsSaveChanges: "Save changes",
  mySettingsSaveError: "Settings could not be saved",
  teamAdminSaveError: "Team settings could not be saved.",
  teamAdminSaveChanges: "Save changes",
  navAppAdmin: "App Admin Center",
  infoRuntimeCardTitle: "Effective Configuration & Backend Diagnostics",
  infoRuntimeCardDescription: "Live frontend/backend metadata, provider status, and infrastructure targets for quick operational checks.",
  infoRuntimeFrontendTitle: "Frontend (Teams tab)",
  infoRuntimeBackendTitle: "Backend (RPP Web API)",
  infoRuntimeLabelEffectiveProvider: "Active provider mode",
  infoRuntimeLabelEnvironment: "Environment",
  infoRuntimeLabelApiBaseUrl: "API base URL",
  infoRuntimeLabelSharePointSiteUrl: "SharePoint site URL",
  infoRuntimeLabelHealthEndpoint: "Health endpoint",
  infoRuntimeLabelFrontendRelease: "Frontend release",
  infoRuntimeLabelFrontendRevision: "Frontend revision",
  infoRuntimeLabelFrontendBuild: "Frontend build time",
  infoRuntimeLabelBackendStatus: "Backend status",
  infoRuntimeLabelBackendVersion: "Backend version",
  infoRuntimeLabelBackendRevision: "Backend revision",
  infoRuntimeLabelBackendBuild: "Backend build time",
  infoRuntimeLabelBackendEnvironment: "Backend environment",
  infoRuntimeLabelBackendProvider: "Backend provider",
  infoRuntimeLabelBackendDatabaseServer: "Database server",
  infoRuntimeLabelBackendDatabaseName: "Database name",
  infoRuntimeLabelBackendWebServer: "Web server name",
  infoRuntimeLoading: "Loading backend metadata ...",
  infoRuntimeNotAvailable: "Not available",
  appAdminMailboxSyncAddress: "Mailbox email address",
  appAdminMailboxSyncAddressHint: "Email address of the shared mailbox that the sync service polls.",
  appAdminMailboxSyncAddressSave: "Save address",
  appAdminMailboxSyncAddressSaving: "Saving…",
  appAdminMailboxSyncAddressSaved: "Address saved.",
  appAdminMailboxSyncAddressError: "Could not save address.",
  appAdminMailboxSyncAddressValidation: "Please enter a valid email address.",
  navHelp: "Help ?",
  pageHelpDescription: "Ask about RPP in your own words – answered from the RPP help.",
  helpPageTitle: "Help",
  helpPageDescription: "Ask your question in your own words. Answers come exclusively from the RPP help.",
  helpIntroText: "What can we help with? Pick a question or write your own.",
  helpAboutThisPage: "Help with this page",
  helpInputLabel: "Your question",
  helpInputPlaceholder: "For example: how do I record a half-day absence?",
  helpSend: "Send",
  helpThinking: "Looking for an answer ...",
  helpAuthorYou: "You",
  helpAuthorAssistant: "RPP Help",
  helpSourceLabel: "Source",
  helpOpenPage: "Open",
  helpFeedbackQuestion: "Was this helpful?",
  helpFeedbackHelpful: "Helpful",
  helpFeedbackNotHelpful: "Not helpful",
  helpFeedbackThanks: "Thanks for the feedback.",
  helpErrorRequestFailed: "The question could not be answered. Please try again.",
  helpDisclaimer: "The help answers questions about using RPP. It cannot create absences, approve requests or change settings.",
  helpStarterHalfDay: "How do I record a half-day absence?",
  helpStarterApproval: "Why does my vacation request need approval?",
  helpStarterSecondaryTeam: "What does “secondary team” mean?",
  helpStarterOutlook: "How do I synchronize an absence with Outlook?",
  helpStarterPersonMissing: "Why can't I see a person in the planning?",
  helpStarterPresence: "What is the difference between an absence and presence status?",
  helpMockSourceAbsences: "Creating and editing absences",
  helpMockSourceApprovals: "Approvals",
  helpMockSourceCapacity: "Team capacity",
  helpMockSourceOutlookSync: "Outlook synchronization",
  helpMockSourceTimeline: "Planning timeline (Overview)",
  helpMockSourceGlossary: "RPP glossary",
  helpMockSourceReports: "Reports and analyses",
  helpMockSourceTeamsAndRoles: "Teams, organisations and roles",
  helpMockSourceSettings: "Personal settings",
  helpMockAnswerHalfDay: "Set the start and end date to the same day and pick the same day half for both – either “Morning” twice or “Afternoon” twice. That gives 0.5 days. If a multi-day absence should start in the afternoon, set only the start day half to “Afternoon”; if it should end in the morning, set the end day half to “Morning”.",
  helpMockAnswerApprovalRequired: "Whether approval is required follows from three rules set by your team: the team's approval policy, the setting per absence type, and a possible personal exemption. The decision is not made in RPP but in the Microsoft Teams “Approvals” app. You can track your requests under “Approvals”.",
  helpMockAnswerSecondaryTeam: "A secondary team is any team that is not a person's primary team. Depending on where you look, the interface calls it “Secondary teams” or “Additional positions”. Important: a person appears in the timeline only under their primary team, and their capacity counts only there – it is neither split nor counted twice.",
  helpMockAnswerOutlookSync: "For all absences, enable “Synchronize approved vacation with Outlook” in Settings under “Outlook calendar”. For an individual case, use the “Synchronize with Outlook” switch under “Synchronization” in the absence form. If your team dictates the setting, the switch is locked.",
  helpMockAnswerPersonMissing: "Check in order: whether a search term is still active under “Filter”, whether the selected period is too short, whether the person is assigned to your team, whether they are inside a collapsed team group, and whether they are a member of the Microsoft Teams team. A frequent special case: the person is assigned to your team only as a secondary team – they then appear under their primary team.",
  helpMockAnswerPresenceVsAbsence: "An absence means “not here” – Vacation, Compensation, Education, Training, Military, Unpaid leave, Other. It may require approval and reduces available capacity. A presence event means “here, but committed” – Home Office, Project, Maintenance, On Call, Standby. It is not approved and does not reduce capacity.",
  helpMockAnswerWhyRed: "Red means status “Critical” in Team capacity. There are two reasons: either utilization has fallen below the critical threshold, or – more often – the team's required staffing is missed on at least one day of the week. The second case occurs even at good utilization. “Affected employees” shows who is concerned.",
  helpMockAnswerVacationBalance: "Your vacation balance is made up of the annual entitlement, the carry forward from last year and manual adjustments, minus pending and approved vacation. The timeline shows the figures E (entitlement), B (booked) and R (remaining days). The values are always calculated and never stored separately – so correct the absence, not the balance.",
  helpMockAnswerReports: "The “Reports” page analyses the planning across all teams and organisations: a people overview with filters by organisation, location and team, plus critical weeks, warnings and the utilization trend. The calculation is the same as in Team capacity.",
  helpMockAnswerRoles: "The Team Admin Center requires the Owner role in the active Microsoft Teams team; the App Admin Center requires the Microsoft Entra role “Teams Administrator” or “Global Administrator”. Without the role the entry does not appear in the navigation. Roles are granted in Microsoft 365, not in RPP.",
  helpMockAnswerSettings: "In Settings you define who approves your requests, how you are notified, and whether your absences appear in Outlook. Language and time zone are taken from Microsoft 365 – there is deliberately no language switcher.",
  helpMockAnswerUnknown: "I can't find anything about that in the RPP help. Please rephrase the question or contact your team administration.",
  helpOpenLabel: "Open help",
  helpPanelClose: "Close help",
  appAdminMailboxSyncLastError: "Reason for the last failure",
  appAdminMailboxSyncBeta: "Beta",
  appAdminMailboxSyncBetaNote: "Beta feature: verified with Microsoft 365. Other senders and message formats are not fully tested yet — please check imported absences.",
  planningBootstrapNoTeamContextTitle: "No team selected.",
  planningBootstrapNoTeamContextMessage: "The planning view does not know which team to show yet. Open RPP as a tab inside a team, or choose a team.",
  teamContextPickerLoading: "Loading your teams …",
  teamContextPickerPrompt: "Which team would you like to plan?",
  teamContextPickerNoTeams: "You are not a member of any team yet. Ask your team lead to add you to one.",
  teamContextPickerFailed: "Your teams could not be loaded. Please try again.",
  planningBootstrapUnauthenticatedTitle: "Sign-in required.",
  planningBootstrapUnauthenticatedMessage: "RPP could not sign in to Microsoft 365. Accept the Microsoft Teams consent dialog and try again.",
  planningBootstrapForbiddenTitle: "No access to this team.",
  planningBootstrapForbiddenMessage: "Your account is known but has no access to this team's data. Please contact your team lead.",
  runtimeConfigUnavailableTitle: "Application configuration unavailable",
  runtimeConfigUnavailableDescription: "The application cannot show reliable planning data without a valid deployment configuration.",
  teamAdminCalendarSourceUrl: "Calendar URL",
  teamAdminCalendarSourceUrlPlaceholder: "https://.../calendar.json or https://.../calendar.ics",
  teamAdminCalendarSourceType: "Format",
  teamAdminHolidayCalendarsTitle: "Holiday calendars",
  teamAdminHolidayCalendarsDescription: "Configure each holiday calendar separately, including its color and its own fetch action.",
  teamAdminCalendarRefreshButton: "Fetch",
  teamAdminCalendarRefreshError: "The holiday calendar could not be refreshed.",
  helpMockSourceGettingStarted: "Getting started with RPP",
  helpMockSourceTeamAdmin: "Team Admin Center for team owners",
  helpMockAnswerGettingStarted: "RPP runs in Microsoft Teams. Use the top navigation for Overview, Team capacity, Approvals and more. Record absences on Overview; track requests under Approvals; check bottlenecks under Team capacity.",
  helpMockAnswerTeamAdmin: "As an owner, Team Admin Center lets you set approvers, absence types, required staffing, Outlook policy and members (Default team and additional positions). Switch the active team first. You still decide requests in the Teams Approvals app – not in Admin Center.",
  helpMockAnswerTeamAdminRestricted: "Team Admin Center and its how-to are only for team owners (Owner) in the Microsoft Teams team. Ask your team owner or IT if you need rules changed.",
  helpStarterTeamAdmin: "What can I configure in Team Admin Center?",
  helpStarterMinimumStaffing: "What does required staffing do?",
} satisfies Record<keyof typeof de, string>;