import type { de } from "./de";
import { en } from "./en";

export const te = {
  ...en,
  themeLight: "తెలుపు",
  themeDark: "చీకటి",
  themeToggle: "రూపాన్ని మార్చండి",
  headerSearch: "శోధన",
  headerSearchPlaceholder: "శోధన (Ctrl+E)",
  moreActions: "మరిన్ని చర్యలు",
  help: "సహాయం",
  teamsRailLabel: "Microsoft Teams నావిగేషన్",
  teamsRailActivity: "క్రియాశీలత",
  teamsRailChat: "చాట్",
  teamsRailTeams: "జట్లు",
  teamsRailCalendar: "క్యాలెండర్",
  teamsRailCalls: "కాల్స్",
  teamsRailFiles: "ఫైళ్లు",
  teamsRailResources: "వనరులు",
  teamsRailApprovals: "ఆమోదాలు",
  teamsRailApps: "యాప్స్",
  primaryNavigation: "ప్రధాన నావిగేషన్",
  navOverview: "సారాంశం",
  navTeamCapacity: "జట్టు సామర్థ్యం",
  navMyAbsences: "నా గైర్హాజరీలు",
  navApprovals: "ఆమోదాలు",
  navTeamAdmin: "జట్టు అడ్మిన్ సెంటర్",
  navReports: "రిపోర్టులు",
  navSettings: "సెట్టింగ్స్",
  navInfo: "సమాచారం",
  navAppAdmin: "యాప్ అడ్మిన్ సెంటర్",
  activeTeamChipLabel: "సక్రియ జట్టు",
  footerText: "Microsoft Teams యాప్ షెల్ • Sprint 1 • పరిశీలన సామర్థ్యం EO-010",
  timelinePeriodWeek: "Week",
  timelinePeriodMonth: "Month",
  appTitle: "Resources & Presence Planning",
  appSubtitle: "Operations planning for IT resources, presence, and capacity",
  appLogoAlt: "M365 Resources & Presence Planning app logo",
  pageOverviewDescription: "Operational planning overview with timeline, resources, teams, and presence events.",
  pageTeamCapacityDescription: "Weekly team capacity with availability, absence share, and risk status.",
  pageMyAbsencesDescription: "Placeholder for personal absences and future request overview.",
  pageApprovalsDescription: "Placeholder for future approvals and decision workflows.",
  pageTeamAdminDescription: "Central administration for team approvers, backups, policies, and vacation visibility.",
  pageReportsDescription: "Placeholder for reporting, analytics, and export views.",
  pageSettingsDescription: "Personal settings for absence requests, approvers, notifications, and Outlook synchronization.",
  pageInfoDescription: "Information about the application, architecture, and design system foundation.",
  infoPageDescription: "A compact, readable overview of the product purpose, architecture, data flow, and delivery setup.",
  infoPageBadge: "Product info",
  infoPageTitle: "RPP in Microsoft Teams",
  infoPageGoToTimeline: "Go to timeline",
  infoPageGoToReports: "Go to reports",
  infoPageStatTeamsLabel: "Active team structure",
  infoPageStatTeamsValue: "Multiple organisations",
  infoPageStatModeLabel: "Data mode",
  infoPageStatModeMock: "Mock / demo",
  infoPageStatModeApi: "API / production",
  infoPageStatDeploymentLabel: "Deployment",
  infoPageStatDeploymentValue: "Teams tab + web API",
  infoCardPeopleTitle: "People and teams",
  infoCardPeopleDescription: "Timeline, team capacity, and reports use the same team and membership data. That keeps multiple organisations visible and assignments consistent.",
  infoCardPeopleStatus: "Planning view",
  infoCardDataTitle: "Data and persistence",
  infoCardDataDescription: "Team Admin Center, member assignments, vacation balances, and holidays are persisted in the backend and returned to the UI consistently.",
  infoCardDataStatus: "SQL + Graph",
  infoCardDeliveryTitle: "Delivery",
  infoCardDeliveryDescription: "Frontend, backend, and Teams package are shipped together so the visible version matches the deployed version.",
  infoCardDeliveryStatus: "Release ready",
  infoCardWhatIsRppTitle: "What is RPP Resources and Presence Planning?",
  infoCardWhatIsRppDescription: "RPP brings resource, attendance, and capacity planning together in a single application. All essential functions, from planning and approvals to administration, are available in one central place.",
  infoCardWhatIsRppStatus: "Teams-native planning",
  infoCardValueTitle: "What is the value of RPP?",
  infoCardValueDescription: "The solution creates operational visibility across multiple organisations, reduces coordination overhead, and keeps teams, roles, and absences aligned in one reliable view.",
  infoCardValueStatus: "More transparency",
  infoCardGetItTitle: "How can I get it?",
  infoCardGetItDescription: "RPP is delivered as a Microsoft Teams app. Distribution happens through the Teams package and the web API so the app is available in the M365 environment.",
  infoCardGetItStatus: "Delivered via Teams",
  infoFactsTitle: "What this application is about",
  infoFactsDescription: "A short overview of the architecture, operation, and collaboration between the key modules.",
  infoFactArchitectureLabel: "Architecture",
  infoFactArchitectureValue: "Teams UI, React, Vite, ASP.NET Core API",
  infoFactArchitectureText: "The experience runs as a Microsoft Teams tab and uses Fluent UI for product interactions, while the API handles delivery and persistence.",
  infoFactRolesLabel: "Roles and views",
  infoFactRolesValue: "Timeline, Team Admin, Reports, Approvals",
  infoFactRolesText: "Each tab has a clear purpose: operational planning, administration, analysis, approvals, and personal settings.",
  infoFactLocalizationLabel: "Localization",
  infoFactLocalizationValue: "German, Swiss German, English, Spanish, French, Italian, and Chinese",
  infoFactLocalizationText: "Every visible string is localizable. Spanish, French, Italian, and Chinese are also added as additional locales.",
  infoFactTeamsLabel: "Teams",
  infoFactTeamsValue: "Multiple organisations visible",
  infoFactTeamsText: "The info page reflects the product goal: platform, service, and domain teams should remain visible and understandable in one product.",
  shellOnlyBadge: "EO-009-C",
  timelineAriaLabel: "Timeline foundation",
  timelineTitle: "Planning timeline",
  timelineThreeMonthView: "3-month view",
  timelinePeriodLabel: "Period",
  timelinePeriodNext30Days: "30 days",
  timelinePeriodNextThreeMonths: "Next 3 months",
  timelinePeriodNextSixMonths: "Next 6 months",
  timelinePeriodFullYear: "Full year",
  timelineGroupByLabel: "Group by",
  timelineGroupByTeams: "Teams",
  timelineGroupByPeople: "People",
  timelineViewLabel: "View",
  timelineViewGantt: "Bars (Gantt)",
  timelineViewList: "List",
  timelineViewCalendar: "",
  timelineToday: "Today",
  timelineCalendarPrev: "",
  timelineCalendarNext: "",
  timelineCalendarOverflow: "",
  timelineFilter: "Filter",
  timelineFilterLabel: "Filter",
  timelineFilterPlaceholder: "Search team or person",
  timelineLegendSchoolHolidaySg: "School holidays St. Gallen",
  timelineLegendSchoolHolidayDubendorf: "School holidays Dübendorf",
  timelineLegendPublicHoliday: "Public holidays",
  timelineAvailablePeople: "Available people (total)",
  timelineMinimumStaffing: "Required minimum staffing",
  timelineCalendarWeekPrefix: "CW",
  timelineEmployeeColumn: "Employee",
  resourceCompetencies: "Roles and competencies",
  resourceVacationSummary: "Vacation summary: entitlement, booked, remaining",
  resourceVacationIcon: "🌴",
  resourceVacationEntitlement: "E",
  resourceVacationBooked: "B",
  resourceVacationRemaining: "R",
  resourceVacationEntitlementTooltip: "",
  resourceVacationBookedTooltip: "",
  resourceVacationRemainingTooltip: "",
  teamGroupingResourceCount: "resources",
  teamGroupingResourceCountCompact: "people",
  teamGroupingExpand: "Expand team group",
  teamGroupingCollapse: "Collapse team group",
  eventTypeVacation: "Vacation",
  eventTypeCompensation: "Compensation",
  eventTypeEducation: "Education",
  eventTypeHomeOffice: "Home Office",
  eventTypeTraining: "Training",
  eventTypeMilitary: "Military",
  eventTypeUnpaidLeave: "Unpaid leave",
  eventTypeOtherAbsence: "Other absence",
  eventTypeProject: "Project",
  eventTypeMaintenance: "Maintenance",
  eventTypeOnCall: "On Call",
  eventTypeStandby: "Standby",
  detailsClose: "Close",
  detailsResourceTitle: "Resource details",
  detailsPresenceTitle: "Event details",
  detailsResourceSection: "Resource",
  detailsPresenceSection: "Presence event",
  detailsOrganisation: "Organisation",
  detailsPrimaryTeam: "Primary team",
  detailsSecondaryTeams: "Secondary teams",
  detailsVacation: "Vacation",
  detailsEventType: "Event type",
  detailsEventTitle: "Title",
  detailsStartDate: "Start date",
  detailsEndDate: "End date",
  detailsDuration: "Duration",
  detailsDays: "days",
  absenceNew: "New absence",
  absencePersistError: "The absence could not be saved. Please try again.",
  approvalSubmitPending: "The request was submitted to Microsoft 365 for approval. The approver will find it in the Teams “Approvals” app.",
  approvalSubmitAutoApproved: "The absence was saved – no approval is required for this person.",
  approvalSubmitError: "The request could not be submitted. Please check the approver in the Team Admin Center and try again.",
  myApprovalsTitle: "My requests",
  myApprovalsDescription: "Vacation requests with Microsoft 365 approval status. Decisions are made in the Teams “Approvals” app.",
  myApprovalsRefresh: "Refresh status",
  myApprovalsOpenTeams: "Open Approvals in Teams",
  myApprovalsEmpty: "No requests yet. New requests are created from the Timeline (“Request approval”).",
  myApprovalsLoadError: "The requests could not be loaded. Please try again.",
  myApprovalsColPeriod: "Period",
  myApprovalsColModified: "Last modified",
  myApprovalsColM365: "M365 Approvals",
  myApprovalsM365Linked: "Linked",
  myApprovalsM365Missing: "No Graph item",
  myApprovalsGraphId: "Graph id",
  myApprovalsWhereToFind: "In the Teams Approvals app: as approver under Received, as requester under Sent. Check the environment filter (tenant). The item only appears for the selected approver account.",
  absenceApproverPolicyManaged: "Managed by the team policy",
  absenceApproverNone: "Select an approver",
  absenceApproverRequired: "Please select an approver or configure a default approver in the Team Admin Center.",
  orgConfigTitle: "Organisations & Locations",
  orgConfigDescription: "Configurable lists for partner organisations and office locations. Member values derive from the Microsoft 365 profile (company, office) and are mapped here.",
  orgConfigOrganisations: "Organisations",
  orgConfigLocations: "Locations",
  orgConfigOrganisationMappings: "Mapping profile value → organisation",
  orgConfigLocationMappings: "Mapping profile value → location",
  orgConfigUnassigned: "Unassigned",
  orgConfigAdd: "Add",
  orgConfigRemove: "Remove",
  orgConfigSave: "Save organisations & locations",
  orgConfigSaved: "Saved. Mappings take effect immediately.",
  orgConfigLoadError: "The configuration could not be loaded.",
  orgConfigSaveError: "The configuration could not be saved.",
  myApprovalsColOutlook: "Outlook",
  teamCapacityAbsentPersons: "Absent persons",
  teamCapacityAbsenceDays: "Absence (person-days)",
  teamCapacityAvailableDays: "Available (person-days)",
  absenceCreateTitle: "Request absence",
  absenceEditTitle: "Edit absence",
  absenceCreate: "Save",
  absenceRequestApproval: "Request approval",
  absenceUpdate: "Save changes",
  absenceDelete: "Delete",
  absenceDeleteConfirm: "Confirm delete",
  absenceFieldType: "Absence type",
  absenceFieldStartDate: "Start date",
  absenceFieldStartHalf: "Start day half",
  absenceFieldEndDate: "End date",
  absenceFieldEndHalf: "End day half",
  absenceFieldSubstitute: "Substitute",
  absenceFieldComment: "Comment",
  absenceSubstituteNone: "No substitute",
  absenceCalculatedWorkdays: "Working days",
  absenceSyncTitle: "Synchronization",
  absenceSyncOutlook: "Synchronize with Outlook",
  absenceApprovalStatus: "Request status",
  absenceApprovalStatusDraft: "Draft",
  absenceApprovalStatusPending: "Pending",
  absenceApprovalStatusApproved: "Approved",
  absenceApprovalStatusRejected: "Rejected",
  absenceVacationEntitlementTitle: "Vacation entitlement 2026",
  absenceVacationAvailable: "Available",
  absenceVacationBooked: "Already booked",
  absenceVacationAfterBooking: "After this booking",
  absenceCancel: "Cancel",
  vacationRequestStatus: "Request status",
  vacationRequestApprovalSection: "Approval",
  vacationRequestApprover: "Approver",
  vacationRequestCommentToApprover: "Comment to approver",
  vacationRequestSaveDraft: "Save draft",
  vacationRequestSubmitForApproval: "Submit for approval",
  approvalPrototypeTitle: "Clickable approval workflow",
  approvalPrototypeBadge: "EO-202-A mock workflow",
  approvalLiveModeBadge: "Microsoft 365 Approval Process",
  approvalPrototypeTimeline: "Approval progress",
  approvalPrototypeStepPrepare: "Prepare",
  approvalPrototypeStepReview: "Review",
  approvalPrototypeStepSubmitted: "Submitted",
  approvalPrototypeStepTeamLead: "Division Head",
  approvalPrototypeStepDecision: "Decision",
  approvalPrototypePrepareTitle: "Prepare vacation request",
  approvalPrototypePrepareDescription: "Enter the request details as they will appear in the future production surface. Everything stays local in the browser.",
  approvalPrototypeReviewTitle: "Review request",
  approvalPrototypeReviewDescription: "Check period, duration, and approver before the request is submitted in the simulation.",
  approvalPrototypeSubmittedTitle: "Request submitted",
  approvalPrototypeSubmittedDescription: "The request is now with the Division Head in the mock workflow. No real approval was started.",
  approvalPrototypeTeamLeadTitle: "Simulate Division Head decision",
  approvalPrototypeTeamLeadDescription: "Switch to the Division Head perspective and simulate approval or rejection.",
  approvalPrototypeDecisionTitle: "Workflow completed",
  approvalPrototypeDecisionDescription: "The mock workflow shows the final status. No production data was changed.",
  approvalPrototypeReviewRequest: "Review request",
  approvalPrototypeBackToEdit: "Back to editing",
  approvalPrototypeBackToPending: "Back to submitted",
  approvalPrototypeOpenTeamLead: "Open Division Head view",
  approvalPrototypeCancelRequest: "Cancel request",
  approvalPrototypeApprove: "Approve",
  approvalPrototypeReject: "Reject",
  approvalPrototypeStartNew: "Start new mock workflow",
  approvalPrototypeRoutingHint: "The approver comes from the simulated team policy and can later be replaced by the production API.",
  approvalPrototypeSubmittedMessage: "The request visibly waits for the Division Head decision. This state is temporary UI state only.",
  approvalPrototypeDecisionComment: "Decision comment",
  approvalPrototypeApprovedMessage: "The request was approved in the mock workflow.",
  approvalPrototypeRejectedMessage: "The request was rejected in the mock workflow.",
  approvalPrototypeCancelledMessage: "The request was cancelled in the mock workflow.",
  approvalPrototypeApprovedPersistedMessage: "The approved vacation was saved to the mock timeline.",
  approvalPrototypePersistError: "Could not save the approved vacation to mock state.",
  approvalPrototypeSummaryTitle: "Request summary",
  approvalPrototypeSummaryDescription: "Current mock state for demos and usability review.",
  approvalPrototypeRequester: "Requester",
  approvalPrototypeMockOnly: "Mock only, no production process",
  approvalStatusDraft: "Draft",
  approvalStatusSubmitted: "Submitted",
  approvalStatusPendingApproval: "Pending approval",
  approvalStatusApproved: "Approved",
  approvalStatusRejected: "Rejected",
  approvalStatusCancelled: "Cancelled",
  approvalStatusFailed: "Failed",
  absenceCalculatedRemainingVacation: "Remaining vacation after booking",
  absenceValidationRequired: "Please complete all required fields.",
  absenceValidationEndBeforeStart: "The end date must not be before the start date.",
  absenceValidationDuration: "The selected half-day combination does not create a valid duration.",
  absenceValidationOutsideTimeline: "The change is outside the visible timeline range.",
  absenceValidationMoveDuration: "Moving an absence must not change its duration.",
  absenceTypeVacation: "Vacation",
  absenceTypeCompensation: "Compensation",
  absenceTypeEducation: "Education",
  absenceTypeTraining: "Training",
  absenceTypeMilitary: "Military",
  absenceTypeUnpaidLeave: "Unpaid leave",
  absenceTypeOther: "Other",
  dayHalfMorning: "Morning",
  dayHalfAfternoon: "Afternoon",
  dayHalfFullDay: "Full day",
  capacityAvailable: "Available capacity",
  teamCapacityDashboardTitle: "Team capacity",
  teamCapacityDashboardDescription: "Aggregated weekly overview based on the central capacity engine.",
  teamCapacityTeamLabel: "Team",
  teamCapacityAvailable: "Available",
  teamCapacityAbsent: "Absent",
  teamCapacityUtilization: "Utilization",
  teamCapacityMembers: "Team members",
  teamCapacityNominal: "Nominal",
  teamCapacityCriticalWeeks: "Critical weeks",
  teamCapacityCriticalWeeksShort: "Critical weeks",
  teamCapacityWeeklyOverview: "Weekly overview",
  teamCapacityStatus: "Status",
  teamCapacityMetric: "Metric",
  teamCapacityAffectedResources: "Affected employees",
  teamCapacityNoAffectedResources: "No affected employees in this calendar week.",
  teamCapacityStatusOk: "OK",
  teamCapacityStatusWarning: "Warning",
  teamCapacityStatusCritical: "Critical",
  designSystemSectionTitle: "Design system foundation",
  designSystemSectionDescription: "Reusable visual patterns for upcoming Engineering Orders.",
  designCardLayoutTitle: "Layout",
  designCardLayoutDescription: "Shell, page header, content area, and responsive spacing follow one coherent grid.",
  designCardThemeTitle: "Theme",
  designCardThemeDescription: "Light and dark mode are based on Fluent UI tokens and remain extensible.",
  designCardTypographyTitle: "Typography",
  designCardTypographyDescription: "Titles, sections, and helper text use consistent sizes and weights.",
  statusReady: "Ready",
  statusFoundation: "Foundation",
  statusReserved: "Reserved",
  placeholderSurfaceTitle: "Application Shell",
  placeholderSurfaceText: "This page is intentionally a placeholder. Business functionality follows in later Engineering Orders.",
  errorBoundaryTitle: "Something went wrong.",
  errorBoundaryMessage: "The view could not be loaded. Please try again or share the reference with support.",
  errorReferenceLabel: "Reference",
  errorRetryAction: "Try again",
  planningBootstrapLoading: "Loading planning data ...",
  planningBootstrapEmptyTitle: "No plannable people found.",
  planningBootstrapEmptyMessage: "The planning view needs team members before capacity and absences can be shown.",
  mySettingsTitle: "My Settings",
  mySettingsLoading: "Loading settings ...",
  mySettingsProfileTitle: "Profile",
  mySettingsName: "Name",
  mySettingsEmail: "E-mail address",
  mySettingsTeam: "Team",
  mySettingsApprovalTitle: "Approval",
  mySettingsApprovalDescription: "Default approver and fallback for vacation requests.",
  mySettingsDefaultApprover: "Default approver",
  mySettingsFallbackApprover: "Fallback approver",
  mySettingsApproverSource: "Source",
  mySettingsApproverSourceUser: "Personal setting",
  mySettingsApproverSourceTeamPolicy: "Team policy",
  mySettingsApproverSourceTeamLead: "Division Head",
  mySettingsApproverSourceFallback: "Fallback",
  mySettingsNoApproverWarning: "No approver configured. Please contact your team admin.",
  mySettingsNotificationsTitle: "Notifications",
  mySettingsNotificationsDescription: "How you are informed about request status changes.",
  mySettingsNotificationInApp: "In-app notification",
  mySettingsNotificationEmail: "E-mail notification",
  mySettingsNotificationTeams: "Teams notification",
  mySettingsOutlookTitle: "Outlook calendar",
  mySettingsOutlookDescription: "Default behavior for approved absences.",
  mySettingsOutlookSync: "Synchronize approved vacations with Outlook",
  mySettingsOutlookEnabled: "Enabled",
  mySettingsOutlookDisabled: "Disabled",
  mySettingsOutlookManaged: "Managed by team policy",
  mySettingsRegionalTitle: "Regional",
  mySettingsRegionalDescription: "Language and time zone are inherited from Microsoft 365 or the browser.",
  mySettingsLanguage: "Language",
  mySettingsTimeZone: "Time zone",
  mySettingsManagedByTeamPolicy: "Managed by team policy",
  mySettingsNotConfigured: "Not configured",
  mySettingsSaveChanges: "Save changes",
  mySettingsResetToDefaults: "Reset to defaults",
  mySettingsSavedToast: "Settings saved",
  mySettingsResetToast: "Settings reset",
  mySettingsSaveError: "Settings could not be saved",
  outlookSyncStatusNotRequired: "No Outlook synchronization",
  outlookSyncStatusPending: "Syncing with Outlook",
  outlookSyncStatusSynced: "Outlook calendar updated",
  outlookSyncStatusFailed: "Outlook synchronization failed",
  outlookSyncRetry: "Retry synchronization",
  vacationBalanceTitle: "Vacation balance",
  vacationBalanceAnnualEntitlement: "Annual entitlement",
  vacationBalanceCarryForward: "Carry forward",
  vacationBalanceManualAdjustments: "Manual adjustments",
  vacationBalancePendingVacation: "Pending vacation",
  vacationBalanceApprovedVacation: "Approved vacation",
  vacationBalanceRemainingBalance: "Remaining balance",
  vacationBalancePreviewTitle: "Balance preview",
  vacationBalanceCurrentBalance: "Current balance",
  vacationBalanceRequestedVacation: "Requested vacation",
  vacationBalanceRemainingAfterSubmission: "Balance after submission",
  vacationBalanceExceedsWarning: "This request exceeds the available vacation balance. Sprint 3 shows a warning but does not hard-block submission.",
  vacationBalanceAdjustmentTitle: "Adjust balance",
  vacationBalanceAdjustmentValue: "Adjustment",
  vacationBalanceAdjustmentReason: "Reason",
  vacationBalanceSaveAdjustment: "Save adjustment",
  vacationBalanceHistoryTitle: "Adjustment history",
  vacationBalanceHistoryPrevious: "Previous",
  vacationBalanceHistoryNew: "New",
  vacationBalanceHistoryEmpty: "No manual adjustments yet.",
  vacationBalancePreviewControlsTitle: "Check vacation request",
  teamAdminTitle: "Team Admin Center",
  teamAdminLoading: "Loading Team Admin Center ...",
  teamAdminLoadError: "Team Admin Center could not be loaded.",
  teamAdminSaveError: "Team settings could not be saved.",
  teamAdminSavedToast: "Team settings saved",
  teamAdminAutoSaveEnabled: "Auto-save active",
  teamAdminAutoSaveSaving: "Saving changes ...",
  teamAdminNoManagedTeams: "No manageable teams found.",
  teamAdminTeamSelection: "Team selection",
  teamAdminTeamSelectionDescription: "Teams you are authorized to manage as Division Head or delegated administrator.",
  teamAdminActiveTeam: "Active team",
  teamAdminManagedTeam: "Managed team",
  teamAdminAllTeams: "All teams",
  teamAdminAllTeamsDescription: "Alphabetical overview of all team members for demo data maintenance.",
  teamAdminTeamInformation: "Team information",
  teamAdminTeamLead: "Division Head",
  teamAdminMemberCount: "Members",
  teamAdminDefaultApprover: "Default approver",
  teamAdminBackupApprover: "Backup approver",
  teamAdminNoBackupApprover: "No backup approver",
  teamAdminDisplaySettings: "",
  teamAdminDisplaySettingsDescription: "",
  teamAdminShowVacationSummary: "",
  teamAdminEventColorMode: "",
  teamAdminEventColorByType: "",
  teamAdminEventColorByTeam: "",
  teamAdminTeamColor: "",
  teamAdminTeamColorAuto: "",
  teamColorBlue: "",
  teamColorGreen: "",
  teamColorMarigold: "",
  teamColorBerry: "",
  teamColorTeal: "",
  teamColorPumpkin: "",
  teamColorLavender: "",
  teamColorSeafoam: "",
  teamColorCranberry: "",
  teamColorPlatinum: "",
  teamAdminApprovalPolicy: "Approval policy",
  teamAdminApprovalPolicyDescription: "This policy influences new vacation requests and personal settings for team members.",
  teamAdminAllowUserOverride: "Users may choose another approver",
  teamAdminOutlookSyncPolicy: "Outlook synchronization",
  teamAdminOutlookSyncOptional: "Optional",
  teamAdminOutlookSyncMandatory: "Mandatory",
  teamAdminOutlookSyncDisabled: "Disabled",
  teamAdminAbsenceEntryTypes: "Absence types",
  teamAdminAbsenceEntryTypesDescription: "Centrally manage absence types, approval requirements, and vacation balance behavior.",
  teamAdminEntryTypeName: "Type",
  teamAdminEntryTypeActive: "Active",
  teamAdminEntryTypeRequiresApproval: "Approval",
  teamAdminEntryTypeConsumesVacation: "Vacation balance",
  teamAdminEntryTypeActions: "Action",
  teamAdminEntryTypeNew: "New absence type",
  teamAdminEntryTypeNewPlaceholder: "e.g. Conference",
  teamAdminEntryTypeAdd: "Add",
  teamAdminEntryTypeDelete: "Delete absence type",
  teamAdminTeamMembers: "Team members",
  teamAdminTeamMembersDescription: "Assignment of default team, additional positions, employment, vacation balance, approval exemption, and effective approver.",
  teamAdminMemberAdd: "Add member",
  teamAdminMemberAddPlaceholder: "Choose person from Teams space",
  teamAdminMemberAddButton: "Add",
  teamAdminMemberName: "Name",
  teamAdminMemberEmail: "E-mail",
  teamAdminMemberPosition: "Position",
  teamAdminMemberActions: "Actions",
  teamAdminMemberRemove: "Remove",
  teamAdminMemberRemoveConfirm: "Remove \"{name}\" from RPP planning? The person may remain in the M365 team; absence history is kept.",
  teamAdminMemberRemoveHint: "Removes the person from all RPP teams on this host (after save).",
  teamAdminMemberRemoveError: "The person could not be removed from RPP planning. Try again or reload the page.",
  teamAdminMemberRemoveEmpty: "No RPP assignment was found for this person (already removed).",
  teamAdminPrimaryTeam: "Default team",
  teamAdminAdditionalPositions: "Additional positions",
  teamAdminEmploymentPercentage: "Employment",
  teamAdminVacationBalance: "Vacation balance",
  teamAdminActiveVacationRequests: "Active requests",
  teamAdminApprovalExempt: "No approval required",
  teamAdminNoApprovalRequired: "No approval required",
  teamAdminEffectiveApprover: "Effective approver",
  teamAdminNotAvailable: "Not available",
  teamAdminSaveChanges: "Save changes",
  teamAdminTeamManagement: "Team management",
  teamAdminTeamManagementDescription: "Create, rename, and delete teams and define a display order independent of alphabetical sorting.",
  teamAdminTeamManagementOrder: "Order",
  teamAdminTeamManagementName: "Team",
  teamAdminTeamManagementOrganization: "Organization",
  teamAdminTeamMoveUp: "Move up",
  teamAdminTeamMoveDown: "Move down",
  teamAdminTeamNew: "New team",
  teamAdminTeamNewPlaceholder: "e.g. Cloud Engineering",
  teamAdminTeamAdd: "Add team",
  teamAdminTeamDelete: "Delete team",
  teamAdminTeamManagementUpdatedToast: "Team management updated",
  teamAdminTeamNameRequired: "The team name must not be empty.",
  teamAdminTeamNameDuplicate: "A team with this name already exists.",
  teamAdminTeamHasMembers: "Teams with assigned members cannot be deleted.",
  teamAdminTeamLastTeam: "The last team cannot be deleted.",
  teamAdminTeamRequiredStaffing: "Required staffing",
  teamCapacityRequiredStaffing: "Required staffing",
  reportsSharedPlanningTitle: "Joint planning across organisations",
  reportsSharedPlanningSubtitle: "Clear separation/filtering by organization and location",
  reportsOrganizationLabel: "Organization",
  reportsOrgFilterAll: "All",
  reportsTableEmployee: "Employee",
  reportsTableLocation: "Location",
  reportsTableTeamsRoles: "Teams / roles",
  reportsTeamFilter: "Team",
  reportsFilterHint: "Filterable by organization, location, and team",
  reportsAnalysisTitle: "Analysis – Critical understaffing",
  reportsAnalysisSubtitle: "Visual analysis & trends (later with Power BI)",
  reportsCriticalWeeks: "Critical weeks",
  reportsCriticalWeeksHint: "Below required staffing",
  reportsWarnings: "Warnings",
  reportsWarningsHint: "Below warning threshold",
  reportsUtilization: "Utilization",
  reportsUtilizationHint: "Next 3 months",
  reportsChartTitle: "Utilization over time (all teams)",
  reportsLegendUtilization: "Utilization",
  reportsLegendMinStaffing: "Required staffing",
  reportsLegendWarnThreshold: "Warning threshold",
  reportsCriticalWeeksLabel: "Critical weeks:",
  reportsNoCriticalWeeks: "No critical weeks",
  reportsToPowerBi: "To Power BI",
  reportsCriticalTeams: "critical teams",
  reportsCriticalWeekUtilization: "Utilization",
  reportsMinimumAvailable: "Minimum available",
  reportsAvailableCapacity: "Available",
  reportsMyAbsencesTitle: "My absences & Outlook sync",
  reportsMyAbsencesSubtitle: "Personal overview and synchronization",
  reportsMyAbsencesHeading: "My absences 2026",
  reportsMyAbsencesEmpty: "No personal absences in the current period.",
  reportsDays: "days",
  reportsStatusRequested: "Requested",
  reportsStatusPlanned: "Planned",
  reportsOutlookSyncTitle: "Outlook synchronization",
  reportsOutlookSyncText: "Your absences are synchronized with Outlook.",
  reportsOutlookLastSync: "Last synchronization: Today, 08:45",
  reportsOutlookSyncPending: "Waiting for approval",
  personCardTabOverview: "Overview",
  personCardTabContact: "Contact",
  personCardTabOrganization: "Organization",
  personCardSendQuickMessage: "Send a quick message",
  personCardLastOnline: "Last online: 14 minutes ago • Available at 12:00",
  personCardWorkHours: "Work hours: 06:30 - 16:00",
  personCardInOffice: "Scheduled in office",
  personCardSameTimezone: "Same time zone as you",
  personCardContactInformation: "Contact information",
  personCardAssistant: "Assistant",
  personCardEmail: "E-mail",
  personCardChat: "Chat",
  personCardPhoneBusiness: "Phone (business)",
  personCardWorkLocation: "Work location",
  personCardCompany: "Company",
  personCardMoreContact: "Show more contact information",
  personCardDepartment: "Department",
  personCardBusinessAddress: "Address (business)",
  personCardClose: "Close",
  personCardTeams: "Teams",
  personCardManager: "Manager",
  demoDataSectionTitle: "Demo data",
  demoDataSectionDescription: "Changes to mock data (teams, required staffing, absences, settings, vacation balances, public holidays, and school holidays) are stored locally in the browser and survive a restart. Use export/import to maintain the publicHolidays JSON block.",
  demoDataChangesPresent: "Local changes are present.",
  demoDataResetButton: "Reset demo data",
  demoDataExportButton: "Export demo data",
  demoDataImportButton: "Import demo data",
  demoDataExportFailed: "Export failed. Please check your browser.",
  demoDataImportFailed: "Import failed. Please check the JSON file.",
  teamAdminSchoolHolidaySyncTitle: "Update school holiday calendars",
  teamAdminSchoolHolidaySyncDescription: "Loads school holidays for St. Gallen and Dübendorf/Zurich from the configured Open Data JSON sources and stores them in the local mock calendar.",
  teamAdminSchoolHolidaySyncYear: "Calendar year",
  teamAdminSchoolHolidaySyncButton: "Fetch school holidays",
  teamAdminSchoolHolidaySyncRunning: "Loading school holidays...",
  teamAdminSchoolHolidaySyncSuccess: "School holidays updated for",
  teamAdminSchoolHolidaySyncDays: "calendar days",
  teamAdminSchoolHolidaySyncError: "School holidays could not be loaded. Please check network/CORS or use JSON import.",
  teamAdminSchoolHolidaySyncStGallenNoData: "Note: St. Gallen returned no records for this year.",
  teamAdminSchoolHolidaySyncZurichNoData: "Note: Zurich/Dübendorf returned no records for this year.",
  teamAdminFederalHolidaySyncButton: "Fetch default Zurich holidays",
  teamAdminFederalHolidaySyncRunning: "Updating default Zurich holidays...",
  teamAdminFederalHolidaySyncSuccess: "Default Zurich holidays updated for",
  teamAdminFederalHolidaySyncError: "Default Zurich holidays could not be updated.",
  teamAdminAbsenceEntryTypesSaveHint: "New or changed absence types are persisted automatically and then appear in the absence form.",
  pageAppAdminDescription: "Central application administration for backend providers, configuration, and diagnostics.",
  appAdminEffectiveConfigTitle: "Effective configuration",
  appAdminEffectiveConfigDescription: "Currently active application configuration including the origin of every value.",
  appAdminFieldDataSource: "Data provider",
  appAdminFieldMembershipSource: "Membership source",
  appAdminFieldSharePointSiteUrl: "SharePoint site URL",
  appAdminFieldApiBaseUrl: "API base URL",
  appAdminFieldEnvironment: "Environment",
  appAdminFieldRelease: "Release",
  appAdminFieldRevision: "Revision",
  appAdminOriginLocalOverride: "Local override",
  appAdminOriginDeployment: "Deployment",
  appAdminOriginBuild: "Build",
  appAdminOriginDefault: "Default",
  appAdminOriginStandaloneBrowser: "Standalone browser (mock demo)",
  appAdminFieldStandaloneBrowserUsesMock: "Mock in standalone browser",
  appAdminStandaloneBrowserUsesMockOn: "On (browser ? mock, Teams ? deployment)",
  appAdminStandaloneBrowserUsesMockOff: "Off",
  appAdminProviderMock: "Mock data (demo)",
  appAdminProviderSharePoint: "SharePoint lists",
  appAdminProviderApi: "RPP Web API",
  appAdminMembershipMock: "Mock",
  appAdminMembershipGraph: "Microsoft Graph",
  appAdminProviderConfigTitle: "Backend provider",
  appAdminProviderConfigDescription: "Provider selection as a local override for this browser. The deployment configuration remains unchanged.",
  appAdminAccessDeniedTitle: "Unauthorized",
  appAdminAccessDeniedDescription: "The App Admin Center requires the Microsoft Entra role “Teams Administrator” (or “Global Administrator”). Please contact your IT administration.",
  teamAdminAccessDeniedTitle: "Unauthorized",
  teamAdminAccessDeniedDescription: "The Team Admin Center requires the owner role in the active Microsoft Teams team.",
  appAdminHolidayResetTitle: "Reset holiday calendar",
  appAdminHolidayResetDescription: "Clears this tenant's central public/school holiday calendar so individual calendars can be loaded fresh (Team Admin Center → calendar actions).",
  appAdminHolidayResetButton: "Clear holiday calendar",
  appAdminHolidayResetConfirm: "Really clear",
  appAdminHolidayResetSuccess: "The calendar was cleared. Reload the calendars in the Team Admin Center.",
  appAdminHolidayResetError: "The calendar could not be cleared (check permission or connection).",
  appAdminSharePointSiteUrlHint: "https and *.sharepoint.com only.",
  appAdminApiBaseUrlHint: "https only (http only for localhost).",
  appAdminCspHint: "Note: the deployment's Content Security Policy must allow the API origin in connect-src.",
  appAdminSaveOverride: "Apply locally",
  appAdminResetOverride: "Reset override",
  appAdminOverrideActive: "A local override is active for this browser.",
  appAdminReloadPrompt: "The configuration was changed. Reload the application for it to take effect.",
  appAdminReloadNow: "Reload now",
  appAdminValidationSharePointUrl: "Please provide a valid SharePoint site URL (https, *.sharepoint.com).",
  appAdminValidationApiUrl: "Please provide a valid API base URL (https, http only for localhost).",
  appAdminConnectionTestTitle: "Connection test",
  appAdminConnectionTestDescription: "Check provider reachability. Results show status and latency.",
  appAdminTestConnection: "Test connection",
  appAdminTestRunning: "Testing…",
  appAdminTestHealthy: "Reachable",
  appAdminTestFailed: "Failed",
  appAdminExportTitle: "Deployment configuration",
  appAdminExportDescription: "Generates a deployable config/runtime-config.js from the effective configuration.",
  appAdminExportButton: "Download runtime-config.js",
  appAdminNotConfigured: "Not configured",
  appAdminMailboxSyncTitle: "Outlook Mailbox Sync",
  appAdminMailboxSyncDescription: "Status and manual control of the inbound Outlook sync via the central mailbox. Emails with .ics calendar attachments are automatically imported as absences.",
  appAdminMailboxSyncEnabled: "Status",
  appAdminMailboxSyncEnabledYes: "Enabled",
  appAdminMailboxSyncEnabledNo: "Disabled",
  appAdminMailboxSyncRunning: "Running",
  appAdminMailboxSyncRunningYes: "Yes",
  appAdminMailboxSyncRunningNo: "No",
  appAdminMailboxSyncLastRun: "Last run",
  appAdminMailboxSyncNever: "Never",
  appAdminMailboxSyncProcessed: "Emails processed",
  appAdminMailboxSyncCreated: "Absences created",
  appAdminMailboxSyncUpdated: "Absences updated",
  appAdminMailboxSyncDeleted: "Absences deleted",
  appAdminMailboxSyncErrors: "Errors",
  appAdminMailboxSyncSkipped: "Skipped",
  appAdminMailboxSyncEntries: "Latest entries",
  appAdminMailboxSyncNoData: "No sync data available. Click Refresh status.",
  appAdminMailboxSyncRefresh: "Refresh status",
  appAdminMailboxSyncRefreshing: "Loading…",
  appAdminMailboxSyncTrigger: "Sync now",
  appAdminMailboxSyncTriggering: "Syncing…",
  appAdminMailboxSyncStatusError: "Could not load sync status.",
  appAdminMailboxSyncTriggerError: "Could not start sync.",
  infoRuntimeCardTitle: "Effective Configuration & Backend Diagnostics",
  infoRuntimeCardDescription: "Live frontend/backend metadata, provider status, and infrastructure targets for quick operational checks.",
  infoRuntimeFrontendTitle: "Frontend (Teams tab)",
  infoRuntimeBackendTitle: "Backend (RPP Web API)",
  infoRuntimeLabelEffectiveProvider: "Active provider mode",
  infoRuntimeLabelEnvironment: "Environment",
  infoRuntimeLabelApiBaseUrl: "API base URL",
  infoRuntimeLabelSharePointSiteUrl: "SharePoint site URL",
  infoRuntimeLabelHealthEndpoint: "Health endpoint",
  infoRuntimeLabelFrontendRelease: "Frontend release",
  infoRuntimeLabelFrontendRevision: "Frontend revision",
  infoRuntimeLabelFrontendBuild: "Frontend build time",
  infoRuntimeLabelBackendStatus: "Backend status",
  infoRuntimeLabelBackendVersion: "Backend version",
  infoRuntimeLabelBackendRevision: "Backend revision",
  infoRuntimeLabelBackendBuild: "Backend build time",
  infoRuntimeLabelBackendEnvironment: "Backend environment",
  infoRuntimeLabelBackendProvider: "Backend provider",
  infoRuntimeLabelBackendDatabaseServer: "Database server",
  infoRuntimeLabelBackendDatabaseName: "Database name",
  infoRuntimeLabelBackendWebServer: "Web server name",
  infoRuntimeLoading: "Loading backend metadata ...",
  infoRuntimeNotAvailable: "Not available",
  appAdminMailboxSyncAddress: "Mailbox email address",
  appAdminMailboxSyncAddressHint: "Email address of the shared mailbox that the sync service polls.",
  appAdminMailboxSyncAddressSave: "Save address",
  appAdminMailboxSyncAddressSaving: "Saving…",
  appAdminMailboxSyncAddressSaved: "Address saved.",
  appAdminMailboxSyncAddressError: "Could not save address.",
  appAdminMailboxSyncAddressValidation: "Please enter a valid email address.",
  navHelp: "Help ?",
  pageHelpDescription: "Ask about RPP in your own words – answered from the RPP help.",
  helpPageTitle: "Help",
  helpPageDescription: "Ask your question in your own words. Answers come exclusively from the RPP help.",
  helpIntroText: "What can we help with? Pick a question or write your own.",
  helpAboutThisPage: "Help with this page",
  helpInputLabel: "Your question",
  helpInputPlaceholder: "For example: how do I record a half-day absence?",
  helpSend: "Send",
  helpThinking: "Looking for an answer ...",
  helpAuthorYou: "You",
  helpAuthorAssistant: "RPP Help",
  helpSourceLabel: "Source",
  helpOpenPage: "Open",
  helpFeedbackQuestion: "Was this helpful?",
  helpFeedbackHelpful: "Helpful",
  helpFeedbackNotHelpful: "Not helpful",
  helpFeedbackThanks: "Thanks for the feedback.",
  helpErrorRequestFailed: "The question could not be answered. Please try again.",
  helpDisclaimer: "The help answers questions about using RPP. It cannot create absences, approve requests or change settings.",
  helpStarterHalfDay: "How do I record a half-day absence?",
  helpStarterApproval: "Why does my vacation request need approval?",
  helpStarterSecondaryTeam: "What does “secondary team” mean?",
  helpStarterOutlook: "How do I synchronize an absence with Outlook?",
  helpStarterPersonMissing: "Why can't I see a person in the planning?",
  helpStarterPresence: "What is the difference between an absence and presence status?",
  helpMockSourceAbsences: "Creating and editing absences",
  helpMockSourceApprovals: "Approvals",
  helpMockSourceCapacity: "Team capacity",
  helpMockSourceOutlookSync: "Outlook synchronization",
  helpMockSourceTimeline: "Planning timeline (Overview)",
  helpMockSourceGlossary: "RPP glossary",
  helpMockSourceReports: "Reports and analyses",
  helpMockSourceTeamsAndRoles: "Teams, organisations and roles",
  helpMockSourceSettings: "Personal settings",
  helpMockAnswerHalfDay: "Set the start and end date to the same day and pick the same day half for both – either “Morning” twice or “Afternoon” twice. That gives 0.5 days. If a multi-day absence should start in the afternoon, set only the start day half to “Afternoon”; if it should end in the morning, set the end day half to “Morning”.",
  helpMockAnswerApprovalRequired: "Whether approval is required follows from three rules set by your team: the team's approval policy, the setting per absence type, and a possible personal exemption. The decision is not made in RPP but in the Microsoft Teams “Approvals” app. You can track your requests under “Approvals”.",
  helpMockAnswerSecondaryTeam: "A secondary team is any team that is not a person's primary team. Depending on where you look, the interface calls it “Secondary teams” or “Additional positions”. Important: a person appears in the timeline only under their primary team, and their capacity counts only there – it is neither split nor counted twice.",
  helpMockAnswerOutlookSync: "For all absences, enable “Synchronize approved vacation with Outlook” in Settings under “Outlook calendar”. For an individual case, use the “Synchronize with Outlook” switch under “Synchronization” in the absence form. If your team dictates the setting, the switch is locked.",
  helpMockAnswerPersonMissing: "Check in order: whether a search term is still active under “Filter”, whether the selected period is too short, whether the person is assigned to your team, whether they are inside a collapsed team group, and whether they are a member of the Microsoft Teams team. A frequent special case: the person is assigned to your team only as a secondary team – they then appear under their primary team.",
  helpMockAnswerPresenceVsAbsence: "An absence means “not here” – Vacation, Compensation, Education, Training, Military, Unpaid leave, Other. It may require approval and reduces available capacity. A presence event means “here, but committed” – Home Office, Project, Maintenance, On Call, Standby. It is not approved and does not reduce capacity.",
  helpMockAnswerWhyRed: "Red means status “Critical” in Team capacity. There are two reasons: either utilization has fallen below the critical threshold, or – more often – the team's required staffing is missed on at least one day of the week. The second case occurs even at good utilization. “Affected employees” shows who is concerned.",
  helpMockAnswerVacationBalance: "Your vacation balance is made up of the annual entitlement, the carry forward from last year and manual adjustments, minus pending and approved vacation. The timeline shows the figures E (entitlement), B (booked) and R (remaining days). The values are always calculated and never stored separately – so correct the absence, not the balance.",
  helpMockAnswerReports: "The “Reports” page analyses the planning across all teams and organisations: a people overview with filters by organisation, location and team, plus critical weeks, warnings and the utilization trend. The calculation is the same as in Team capacity.",
  helpMockAnswerRoles: "The Team Admin Center requires the Owner role in the active Microsoft Teams team; the App Admin Center requires the Microsoft Entra role “Teams Administrator” or “Global Administrator”. Without the role the entry does not appear in the navigation. Roles are granted in Microsoft 365, not in RPP.",
  helpMockAnswerSettings: "In Settings you define who approves your requests, how you are notified, and whether your absences appear in Outlook. Language and time zone are taken from Microsoft 365 – there is deliberately no language switcher.",
  helpMockAnswerUnknown: "I can't find anything about that in the RPP help. Please rephrase the question or contact your team administration.",
  helpOpenLabel: "Open help",
  helpPanelClose: "Close help",
  appAdminMailboxSyncLastError: "Reason for the last failure",
  appAdminMailboxSyncBeta: "Beta",
  appAdminMailboxSyncBetaNote: "Beta feature: verified with Microsoft 365. Other senders and message formats are not fully tested yet — please check imported absences.",
  planningBootstrapNoTeamContextTitle: "No team selected.",
  planningBootstrapNoTeamContextMessage: "The planning view does not know which team to show yet. Open RPP as a tab inside a team, or choose a team.",
  teamContextPickerLoading: "Loading your teams …",
  teamContextPickerPrompt: "Which team would you like to plan?",
  teamContextPickerNoTeams: "You are not a member of any team yet. Ask your team lead to add you to one.",
  teamContextPickerFailed: "Your teams could not be loaded. Please try again.",
  planningBootstrapUnauthenticatedTitle: "Sign-in required.",
  planningBootstrapUnauthenticatedMessage: "RPP could not sign in to Microsoft 365. Accept the Microsoft Teams consent dialog and try again.",
  planningBootstrapForbiddenTitle: "No access to this team.",
  planningBootstrapForbiddenMessage: "Your account is known but has no access to this team's data. Please contact your team lead.",
  runtimeConfigUnavailableTitle: "Application configuration unavailable",
  runtimeConfigUnavailableDescription: "The application cannot show reliable planning data without a valid deployment configuration.",
  teamAdminCalendarSourceUrl: "Calendar URL",
  teamAdminCalendarSourceUrlPlaceholder: "https://.../calendar.json or https://.../calendar.ics",
  teamAdminCalendarSourceType: "Format",
  teamAdminHolidayCalendarsTitle: "Holiday calendars",
  teamAdminHolidayCalendarsDescription: "Configure each holiday calendar separately, including its color and its own fetch action.",
  teamAdminCalendarRefreshButton: "Fetch",
  teamAdminCalendarRefreshError: "The holiday calendar could not be refreshed.",
  helpMockSourceGettingStarted: "Getting started with RPP",
  helpMockSourceTeamAdmin: "Team Admin Center for team owners",
  helpMockAnswerGettingStarted: "RPP runs in Microsoft Teams. Use the top navigation for Overview, Team capacity, Approvals and more. Record absences on Overview; track requests under Approvals; check bottlenecks under Team capacity.",
  helpMockAnswerTeamAdmin: "As an owner, Team Admin Center lets you set approvers, absence types, required staffing, Outlook policy and members (Default team and additional positions). Switch the active team first. You still decide requests in the Teams Approvals app – not in Admin Center.",
  helpMockAnswerTeamAdminRestricted: "Team Admin Center and its how-to are only for team owners (Owner) in the Microsoft Teams team. Ask your team owner or IT if you need rules changed.",
  helpStarterTeamAdmin: "What can I configure in Team Admin Center?",
  helpStarterMinimumStaffing: "What does required staffing do?",
} satisfies Record<keyof typeof de, string>;